import { BadGatewayException, Controller, Get, NotFoundException, Param } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { In, Repository } from 'typeorm';
import { Company, CompanyStatus } from './entities/company.entity';
import { CompanyPage } from './entities/company-page.entity';

@Controller('public/company-pages')
export class CompanyPagesPublicController {
  constructor(@InjectRepository(Company) private readonly companies:Repository<Company>,@InjectRepository(CompanyPage) private readonly pages:Repository<CompanyPage>){}
  @Get('rapi10/catalog') async rapi10Catalog(){const companies=await this.companies.find({where:{verificationStatus:CompanyStatus.VERIFIED},order:{updatedAt:'DESC'}});if(!companies.length)return{complete:true,generatedAt:new Date().toISOString(),items:[]};const pages=await this.pages.find({where:{companyId:In(companies.map(c=>c.id))}});const byCompany=new Map(pages.map(p=>[p.companyId,p]));const items=companies.map(company=>{const page=byCompany.get(company.id);const config:any=(page?.published||page?.draft||{}) as any;const businessHours=config?.businessHours&&typeof config.businessHours==='object'?config.businessHours:null;return{id:company.id,slug:company.slug,name:company.name,description:company.description,phone:company.phone,whatsapp:config?.whatsapp||null,website:company.website,address:company.address,city:company.city,state:company.state,postalCode:company.commercialAddressSameAsLegal?company.legalZipCode:null,logoUrl:company.logoURL,heroUrl:null,catalogEnabled:company.rapi10CatalogEnabled!==false,businessHours,specialDates:Array.isArray(businessHours?.specialDates)?businessHours.specialDates:[],updatedAt:company.updatedAt};}).filter(item=>Boolean(item.name&&item.address&&item.city&&item.state));return{complete:true,generatedAt:new Date().toISOString(),items};}
  @Get('company/:companyId/reviews') async reviews(@Param('companyId') companyId:string){const company=await this.companies.findOne({where:{id:companyId,verificationStatus:CompanyStatus.VERIFIED},select:{id:true}});if(!company)throw new NotFoundException('Empresa pública não encontrada.');const base=String(process.env.RAPI10_PUBLIC_API_URL||'https://rapi10.piranegocios.com.br/api/v1').replace(/\/$/,'');const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),6500);try{const response=await fetch(`${base}/catalog/companies/${encodeURIComponent(companyId)}/reviews`,{method:'GET',headers:{accept:'application/json'},signal:controller.signal});if(response.status===404)return{place:{companyId},summary:{average:null,count:0},reviews:[]};if(!response.ok)throw new BadGatewayException('As avaliações estão temporariamente indisponíveis.');const payload:any=await response.json();return{place:payload?.place||{companyId},summary:{average:payload?.summary?.average==null?null:Number(payload.summary.average),count:Math.max(0,Number(payload?.summary?.count||0))},reviews:Array.isArray(payload?.reviews)?payload.reviews.slice(0,200):[]};}catch(error){if(error instanceof BadGatewayException)throw error;throw new BadGatewayException('As avaliações estão temporariamente indisponíveis.');}finally{clearTimeout(timeout);}}
  @Get('company/:companyId') async published(@Param('companyId') companyId:string){const company=await this.companies.findOne({where:{id:companyId,verificationStatus:CompanyStatus.VERIFIED}});if(!company)throw new NotFoundException('Empresa pública não encontrada.');const page=await this.pages.findOne({where:{companyId}});if(!page||page.status!=='PUBLISHED'||!page.published)return{page:null};return{page:page.published,siteType:page.siteType,revision:page.revision,publishedAt:page.publishedAt};}
}
