import { PUBLIC_SUPPORT_TOPICS } from './public';
import { CANDIDATE_SUPPORT_TOPICS } from './candidate';
import { COMPANY_SUPPORT_TOPICS } from './company';
import { ADMIN_SUPPORT_TOPICS } from './admin';
import { SHARED_SUPPORT_TOPICS } from './shared';

export const SUPPORT_KNOWLEDGE_TOPICS = [
  ...SHARED_SUPPORT_TOPICS,
  ...PUBLIC_SUPPORT_TOPICS,
  ...CANDIDATE_SUPPORT_TOPICS,
  ...COMPANY_SUPPORT_TOPICS,
  ...ADMIN_SUPPORT_TOPICS,
];

export {
  SHARED_SUPPORT_TOPICS,
  PUBLIC_SUPPORT_TOPICS,
  CANDIDATE_SUPPORT_TOPICS,
  COMPANY_SUPPORT_TOPICS,
  ADMIN_SUPPORT_TOPICS,
};
