import type { SupportKnowledgeTopic } from '../support-knowledge.types';

export const PUBLIC_SUPPORT_TOPICS: SupportKnowledgeTopic[] = [
  {
    id: 'public.navigation',
    title: 'Navegação pública e conta',
    audiences: ['PUBLIC'],
    routes: ['/', '/login', '/ajuda', '/termos'],
    keywords: ['entrar', 'login', 'conta', 'inicio', 'home', 'ajuda', 'termos', 'menu', 'navegar', 'cadastro'],
    summary: 'Área pública do PiraNegócios, entrada na conta, central de ajuda e navegação entre vagas, classificados e currículo.',
    functions: [
      'Acessar vagas públicas e páginas de empresas sem usar ferramentas administrativas.',
      'Entrar na conta pela rota /login e retornar ao destino solicitado quando houver returnTo.',
      'Consultar artigos publicados na Central de Ajuda em /ajuda.',
      'Abrir Termos em /termos.',
    ],
    procedures: [
      {
        title: 'Entrar na conta',
        intents: ['como entrar', 'fazer login', 'acessar minha conta'],
        steps: ['Abra Entrar.', 'Faça a autenticação disponível na tela.', 'Depois do login, o sistema direciona ao espaço compatível com a conta ou ao endereço de retorno solicitado.'],
      },
      {
        title: 'Encontrar ajuda',
        intents: ['central de ajuda', 'faq', 'artigo de ajuda'],
        steps: ['Abra /ajuda.', 'Procure o assunto disponível.', 'Abra o artigo correspondente. Se a dúvida for sobre a própria conta, use o suporte autenticado para não expor dados pessoais.'],
      },
    ],
    boundaries: ['Não inventar formas de login ou recuperação que não estejam visíveis na interface.', 'Não revelar rotas administrativas para perfis sem permissão.'],
    related: ['public.jobs', 'public.classifieds', 'public.resume', 'public.company-page'],
  },
  {
    id: 'public.jobs',
    title: 'Portal público de vagas',
    audiences: ['PUBLIC'],
    routes: ['/vagas', '/vagas-em/', '/vagas/'],
    keywords: ['vaga', 'vagas', 'emprego', 'trabalho', 'candidatar', 'salario', 'beneficios', 'requisitos', 'cidade', 'fonte'],
    summary: 'Busca e leitura pública de vagas, incluindo páginas por cidade e detalhe da oportunidade.',
    functions: [
      'Pesquisar oportunidades em /vagas.',
      'Abrir páginas regionais em /vagas-em/:citySlug.',
      'Abrir o detalhe público em /vagas/:slug.',
      'Ler cargo, empresa quando não confidencial, local, requisitos, benefícios, salário informado ou estimativa quando disponibilizada, origem e instrução de candidatura.',
    ],
    procedures: [
      {
        title: 'Encontrar uma vaga',
        intents: ['procurar vaga', 'buscar emprego', 'vaga na minha cidade'],
        steps: ['Abra Vagas.', 'Use busca e localização quando disponíveis.', 'Abra a oportunidade para conferir requisitos, local e forma de candidatura.', 'Se estiver logado e a vaga aceitar candidatura interna, siga o botão apresentado no detalhe.'],
      },
      {
        title: 'Entender salário estimado',
        intents: ['media salarial', 'salario estimado'],
        steps: ['Primeiro verifique se a empresa informou salário.', 'Quando não informou e existe estimativa cadastrada, a página pode exibir média estimada, região, fonte e aviso de que o valor real pode variar.', 'Nunca apresentar a estimativa como salário confirmado pela empresa.'],
      },
    ],
    consults: [{ label: 'Dados da vaga', source: 'GET /jobs e detalhe público da vaga', rule: 'Usar somente os campos públicos retornados; não prometer seleção nem contratação.' }],
    boundaries: ['Não revelar informações internas de candidatos ou da empresa.', 'Não afirmar que uma vaga continua aberta sem consultar o estado atual quando a resposta depender disso.'],
    related: ['candidate.jobs'],
  },
  {
    id: 'public.classifieds',
    title: 'Classificados públicos',
    audiences: ['PUBLIC'],
    routes: ['/classificados', '/classificados/busca', '/classificados/categoria/', '/classificados/anuncio/'],
    keywords: ['classificado', 'anuncio', 'anúncio', 'produto', 'comprar', 'vender', 'favorito', 'categoria', 'preco', 'whatsapp vendedor'],
    summary: 'Marketplace regional de classificados: vitrine, busca, categorias e detalhe do anúncio.',
    functions: [
      'Explorar a home /classificados.',
      'Pesquisar e filtrar em /classificados/busca.',
      'Navegar por categoria.',
      'Abrir detalhe com fotos, preço, descrição, características, localização e contatos liberados pelo anunciante.',
    ],
    procedures: [
      {
        title: 'Buscar um anúncio',
        intents: ['buscar produto', 'procurar classificado'],
        steps: ['Abra Classificados.', 'Digite o que procura e, se desejar, informe localização.', 'Aplique categoria, condição, faixa de preço ou tipo de anunciante quando esses filtros estiverem disponíveis.', 'Abra o anúncio para conferir todas as informações antes de entrar em contato.'],
      },
      {
        title: 'Entrar em contato com anunciante',
        intents: ['falar com vendedor', 'whatsapp do anuncio'],
        steps: ['Abra o detalhe do anúncio.', 'Use apenas telefone ou WhatsApp exibidos pelo próprio anúncio.', 'Confirme produto, condição, valor e forma de entrega diretamente com o anunciante.'],
        notes: ['O PiraNegócios não deve afirmar que verificou fisicamente o produto ou que garante uma negociação privada.'],
      },
    ],
    consults: [{ label: 'Anúncio público', source: 'GET /classifieds/:slug e busca pública de classificados', rule: 'Somente dados públicos do anúncio e do vendedor que a API já expõe.' }],
    boundaries: ['Não expor telefone ou dado do vendedor que não esteja presente no anúncio público.', 'Nunca solicitar pagamento fora dos fluxos efetivamente existentes no sistema.'],
    related: ['candidate.classifieds'],
  },
  {
    id: 'public.resume',
    title: 'Criador público de currículo',
    audiences: ['PUBLIC'],
    routes: ['/criador-de-curriculo', '/criar-curriculo', '/curriculo-online', '/transferir/'],
    keywords: ['criar curriculo', 'currículo público', 'curriculo online', 'transferir celular', 'qr code', 'documento base'],
    summary: 'Entrada pública para criação de currículo e transferência de arquivos pelo celular quando o fluxo oferece essa opção.',
    functions: [
      'Abrir /criador-de-curriculo para iniciar o currículo.',
      'Usar rotas antigas que redirecionam para o criador atual.',
      'Usar /transferir/:sessionId apenas quando uma sessão de transferência válida foi criada pelo sistema.',
    ],
    procedures: [
      {
        title: 'Começar um currículo',
        intents: ['criar curriculo', 'fazer curriculo'],
        steps: ['Abra Criador de currículo.', 'Preencha os dados solicitados pelo fluxo.', 'Quando o sistema pedir autenticação ou continuidade na conta, siga a instrução mostrada para salvar ou publicar.'],
      },
      {
        title: 'Enviar arquivo pelo celular',
        intents: ['transferir arquivo', 'qr', 'mandar curriculo pelo celular'],
        steps: ['Use o QR/link gerado pela tela que iniciou a transferência.', 'Abra a sessão no celular.', 'Envie somente os tipos e limites aceitos pela tela.', 'Retorne ao computador e aguarde a sincronização da sessão.'],
      },
    ],
    boundaries: ['Não inventar uma sessão de transferência; ela precisa ter sido criada pelo sistema.', 'Recursos de IA só devem ser descritos como disponíveis quando a IA global estiver habilitada e o produto correspondente estiver liberado.'],
    related: ['candidate.resume'],
  },
  {
    id: 'public.company-page',
    title: 'Página pública de empresa',
    audiences: ['PUBLIC'],
    routes: ['/preview/empresa/', '/:companySlug', '/:companySlug/termos', '/:companySlug/privacidade'],
    keywords: ['pagina da empresa', 'site da empresa', 'empresa verificada', 'selo', 'trabalhe conosco', 'pagina publica'],
    summary: 'Microsite público da empresa integrado ao PiraNegócios, com identidade visual própria, dados empresariais e vagas.',
    functions: [
      'Exibir identidade e conteúdo definido pela empresa.',
      'Exibir o selo visual somente quando a empresa está realmente verificada.',
      'Exibir vagas integradas e links para o fluxo de candidatura.',
      'Exibir termos ou privacidade da empresa quando configurados.',
    ],
    procedures: [{ title: 'Ver vagas de uma empresa', intents: ['vagas dessa empresa', 'trabalhar nessa empresa'], steps: ['Abra a página pública da empresa.', 'Localize a seção de vagas ou o link configurado pela empresa.', 'Abra a vaga desejada para seguir o fluxo de candidatura do PiraNegócios.'] }],
    boundaries: ['Não tratar a identidade visual da página como identidade obrigatória do PiraNegócios.', 'Não chamar uma empresa de verificada se o selo não estiver presente ou o status não for VERIFIED.'],
    related: ['company.page'],
  },
];
