import { DataSource } from 'typeorm';
import { PaymentsService } from '../payments/payments.service';
import { PaymentProviderManagerService, type PaymentCheckoutPayer } from '../payments/payment-provider-manager.service';
import { type CompanyPlanBenefitId, type CompanyWhatsAppFeature, type PaidCompanyPlan } from './company-plan-benefits';
export type CompanyPlan = 'FREE' | 'PLUS' | 'ELITE';
export type { CompanyWhatsAppFeature } from './company-plan-benefits';
export declare const COMPANY_PLAN_CATALOG: readonly [{
    readonly id: "FREE";
    readonly name: "Free";
    readonly priceCents: 0;
    readonly monthly: false;
    readonly description: "Mantém as operações atuais da assistente empresarial no WhatsApp.";
    readonly features: readonly ["WhatsApp: listar vagas da empresa", "WhatsApp: consultar quantidade de candidaturas por vaga", "WhatsApp: consultar candidatos compatíveis", "WhatsApp: criar vagas", "WhatsApp: editar vagas"];
}, {
    readonly id: "PLUS";
    readonly name: "Plus";
    readonly priceCents: 1990;
    readonly monthly: true;
    readonly productCode: "COMPANY_PLUS_MONTHLY";
    readonly description: "Amplia a operação da assistente no WhatsApp. O painel web continua com os recursos atuais.";
    readonly features: readonly ["Tudo do Free no WhatsApp", "WhatsApp: ativar vaga", "WhatsApp: desativar vaga", "WhatsApp: encerrar vaga", "WhatsApp: listar candidatos individualmente com detalhes", "WhatsApp: abrir perfil e currículo de candidato"];
}, {
    readonly id: "ELITE";
    readonly name: "Elite";
    readonly priceCents: 4990;
    readonly monthly: true;
    readonly productCode: "COMPANY_ELITE_MONTHLY";
    readonly description: "Gestão completa pelo WhatsApp, além dos benefícios promocionais exclusivos da contratação paga.";
    readonly features: readonly ["Tudo do Free e Plus no WhatsApp", "WhatsApp: mudar status da candidatura", "WhatsApp: adicionar observações internas", "WhatsApp: convidar e remover convite de candidato", "WhatsApp: adicionar e remover candidatos do Banco de Talentos e pastas", "WhatsApp: responder e gerenciar candidatos", "WhatsApp: consultar novas candidaturas por período", "WhatsApp: estatísticas avançadas das vagas", "Elegibilidade para destaque das vagas no PiraNegócios", "Elegibilidade aos destaques do PiraNegócios na Meta e Google"];
}];
export declare class CompanyPlansService {
    private readonly dataSource;
    private readonly payments;
    private readonly providers;
    constructor(dataSource: DataSource, payments: PaymentsService, providers: PaymentProviderManagerService);
    private normalizePlan;
    private paidPlan;
    private metadataObject;
    commercialBenefitCatalog(plan?: PaidCompanyPlan): {
        plan: PaidCompanyPlan;
        benefits: import("./company-plan-benefits").CompanyPlanBenefitDefinition[];
        defaultBenefitIds: CompanyPlanBenefitId[];
        PLUS?: undefined;
        ELITE?: undefined;
    } | {
        PLUS: {
            benefits: import("./company-plan-benefits").CompanyPlanBenefitDefinition[];
            defaultBenefitIds: CompanyPlanBenefitId[];
        };
        ELITE: {
            benefits: import("./company-plan-benefits").CompanyPlanBenefitDefinition[];
            defaultBenefitIds: CompanyPlanBenefitId[];
        };
        plan?: undefined;
        benefits?: undefined;
        defaultBenefitIds?: undefined;
    };
    resolveCommercialBenefitIds(plan: PaidCompanyPlan, configured: unknown): CompanyPlanBenefitId[];
    resolveCommercialBenefits(plan: PaidCompanyPlan, configured: unknown): import("./company-plan-benefits").CompanyPlanBenefitDefinition[];
    managedCompany(userId: string): Promise<any>;
    private trialForCompany;
    private configuredBenefitIds;
    getCompanyPlan(companyId: string): Promise<{
        plan: CompanyPlan;
        basePlan: CompanyPlan;
        rank: number;
        active: boolean;
        status: any;
        currentPeriodStart: any;
        currentPeriodEnd: any;
        paidCurrentPeriodEnd: any;
        cancelAtPeriodEnd: boolean;
        provider: any;
        providerSubscriptionId: any;
        isSimulation: boolean;
        isTrial: boolean;
        trialEndsAt: any;
        trialTargetPlan: CompanyPlan | null;
        hasPaidSubscription: boolean;
        purchaseMode: "SUBSCRIPTION" | "ONE_TIME" | null;
        benefitIds: CompanyPlanBenefitId[];
        benefits: import("./company-plan-benefits").CompanyPlanBenefitDefinition[];
        advertisingEligible: boolean;
        jobHighlightEligible: boolean;
    }>;
    getForUser(userId: string): Promise<{
        company: {
            id: any;
            name: any;
        };
        current: {
            plan: CompanyPlan;
            basePlan: CompanyPlan;
            rank: number;
            active: boolean;
            status: any;
            currentPeriodStart: any;
            currentPeriodEnd: any;
            paidCurrentPeriodEnd: any;
            cancelAtPeriodEnd: boolean;
            provider: any;
            providerSubscriptionId: any;
            isSimulation: boolean;
            isTrial: boolean;
            trialEndsAt: any;
            trialTargetPlan: CompanyPlan | null;
            hasPaidSubscription: boolean;
            purchaseMode: "SUBSCRIPTION" | "ONE_TIME" | null;
            benefitIds: CompanyPlanBenefitId[];
            benefits: import("./company-plan-benefits").CompanyPlanBenefitDefinition[];
            advertisingEligible: boolean;
            jobHighlightEligible: boolean;
        };
        trial: {
            days: number;
            active: boolean;
            eligibleOnSubscription: boolean;
            used: boolean;
            targetPlan: any;
            startedAt: any;
            endsAt: any;
            restrictions: string[];
        };
        plans: ({
            priceCents: number;
            originalPriceCents: number;
            effectivePriceCents: number;
            promotionalPriceCents: any;
            promotionActive: boolean;
            current: boolean;
            available: boolean;
            includesEliteTrial: boolean;
            eliteTrialDays: number;
            id: "FREE";
            name: "Free";
            monthly: false;
            description: "Mantém as operações atuais da assistente empresarial no WhatsApp.";
            features: readonly ["WhatsApp: listar vagas da empresa", "WhatsApp: consultar quantidade de candidaturas por vaga", "WhatsApp: consultar candidatos compatíveis", "WhatsApp: criar vagas", "WhatsApp: editar vagas"];
        } | {
            priceCents: number;
            originalPriceCents: number;
            effectivePriceCents: number;
            promotionalPriceCents: any;
            promotionActive: boolean;
            current: boolean;
            available: boolean;
            includesEliteTrial: boolean;
            eliteTrialDays: number;
            id: "PLUS";
            name: "Plus";
            monthly: true;
            productCode: "COMPANY_PLUS_MONTHLY";
            description: "Amplia a operação da assistente no WhatsApp. O painel web continua com os recursos atuais.";
            features: readonly ["Tudo do Free no WhatsApp", "WhatsApp: ativar vaga", "WhatsApp: desativar vaga", "WhatsApp: encerrar vaga", "WhatsApp: listar candidatos individualmente com detalhes", "WhatsApp: abrir perfil e currículo de candidato"];
        } | {
            priceCents: number;
            originalPriceCents: number;
            effectivePriceCents: number;
            promotionalPriceCents: any;
            promotionActive: boolean;
            current: boolean;
            available: boolean;
            includesEliteTrial: boolean;
            eliteTrialDays: number;
            id: "ELITE";
            name: "Elite";
            monthly: true;
            productCode: "COMPANY_ELITE_MONTHLY";
            description: "Gestão completa pelo WhatsApp, além dos benefícios promocionais exclusivos da contratação paga.";
            features: readonly ["Tudo do Free e Plus no WhatsApp", "WhatsApp: mudar status da candidatura", "WhatsApp: adicionar observações internas", "WhatsApp: convidar e remover convite de candidato", "WhatsApp: adicionar e remover candidatos do Banco de Talentos e pastas", "WhatsApp: responder e gerenciar candidatos", "WhatsApp: consultar novas candidaturas por período", "WhatsApp: estatísticas avançadas das vagas", "Elegibilidade para destaque das vagas no PiraNegócios", "Elegibilidade aos destaques do PiraNegócios na Meta e Google"];
        })[];
    }>;
    requiredWhatsAppPlan(feature: CompanyWhatsAppFeature): CompanyPlan;
    private currentHasWhatsAppFeature;
    hasWhatsAppFeature(companyId: string, feature: CompanyWhatsAppFeature): Promise<boolean>;
    assertWhatsAppFeature(companyId: string, feature: CompanyWhatsAppFeature): Promise<{
        plan: CompanyPlan;
        basePlan: CompanyPlan;
        rank: number;
        active: boolean;
        status: any;
        currentPeriodStart: any;
        currentPeriodEnd: any;
        paidCurrentPeriodEnd: any;
        cancelAtPeriodEnd: boolean;
        provider: any;
        providerSubscriptionId: any;
        isSimulation: boolean;
        isTrial: boolean;
        trialEndsAt: any;
        trialTargetPlan: CompanyPlan | null;
        hasPaidSubscription: boolean;
        purchaseMode: "SUBSCRIPTION" | "ONE_TIME" | null;
        benefitIds: CompanyPlanBenefitId[];
        benefits: import("./company-plan-benefits").CompanyPlanBenefitDefinition[];
        advertisingEligible: boolean;
        jobHighlightEligible: boolean;
    }>;
    createCheckout(userId: string, requestedPlan: unknown, payer?: PaymentCheckoutPayer): Promise<any>;
    latestCheckout(userId: string): Promise<any>;
    setCancelAtPeriodEnd(userId: string, enabled: boolean): Promise<any>;
}
