export interface Job {
  id: string;
  slug?: string;
  title: string;
  companyName: string;
  location: string;
  city?: string;
  state?: string;
  salary?: string;
  type: string;
  workModel?: string;
  isSponsored?: boolean;
  postedAt: string;
  description: string;
  requirements?: string;
  ownerId?: string;
  companyId?: string | null;
  isExternalListing?: boolean;
  sourceName?: string | null;
  sourceUrl?: string | null;
  reportCount?: number;
  isConfidential?: boolean;
  isCompanyVerified?: boolean;
  isTalentPool?: boolean;
  active?: boolean;
  isFlagged?: boolean;
  flagObservation?: string | null;
  flagReason?: string | null;
  lastVerifiedAt?: string | null;
  sourcePublishedAt?: string | null;
  acceptsPlatformApplications?: boolean;
  externalApplicationInstructions?: string;
  applicationEmail?: string;
  applicationWhatsApp?: string;
  views?: number;
  updatedAt?: string;
}
