"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CANDIDATE_SUPPORT_TOPICS = void 0;
exports.CANDIDATE_SUPPORT_TOPICS = [
    {
        id: 'candidate.home',
        title: 'Início do candidato',
        audiences: ['CANDIDATE'],
        routes: ['/user'],
        keywords: ['inicio', 'painel', 'dashboard', 'meu espaço', 'meu espaco'],
        summary: 'Visão inicial do espaço pessoal do candidato, com atalhos para vagas, currículo, perfil e demais recursos da conta.',
        functions: ['Acessar as áreas pessoais permitidas.', 'Visualizar atalhos e informações do próprio perfil.', 'Alternar para workspace empresarial somente quando a conta estiver legitimamente vinculada a empresa.'],
        procedures: [{ title: 'Encontrar uma área da conta', intents: ['onde fica', 'como acho'], steps: ['Use a navegação do Meu espaço.', 'Escolha Vagas, Currículo, Perfil profissional, Preferências, Classificados, Pagamentos, Notificações ou Configurações conforme o assunto.', 'No celular, use a navegação inferior e o menu para itens adicionais.'] }],
        boundaries: ['Não descrever ferramentas administrativas.', 'Não fornecer passo a passo do workspace empresarial para candidato sem vínculo empresarial.'],
        related: ['candidate.jobs', 'candidate.resume', 'candidate.profile', 'candidate.preferences', 'candidate.classifieds', 'candidate.payments'],
    },
    {
        id: 'candidate.jobs',
        title: 'Vagas do candidato',
        audiences: ['CANDIDATE'],
        routes: ['/user/vagas', '/user/vaga/'],
        keywords: ['minhas vagas', 'encontrar vaga', 'aderencia', 'aderência', 'compatibilidade', 'candidatura', 'candidatar', 'salvar vaga', 'vaga recomendada'],
        summary: 'Busca personalizada e visualização autenticada de vagas pelo candidato.',
        functions: [
            'Explorar vagas disponíveis ao candidato.',
            'Abrir detalhe de uma vaga no contexto autenticado.',
            'Iniciar candidatura quando a vaga e o fluxo permitirem.',
            'Exibir informações de compatibilidade/aderência quando o produto correspondente estiver disponível.',
        ],
        procedures: [
            { title: 'Candidatar-se', intents: ['me candidatar', 'enviar candidatura'], steps: ['Abra Encontrar vagas.', 'Escolha a oportunidade.', 'Leia requisitos, local e instruções.', 'Use o botão de candidatura apresentado. Se a vaga usar candidatura externa, siga o destino informado; se usar fluxo interno, conclua os passos dentro do PiraNegócios.'] },
            { title: 'Entender compatibilidade', intents: ['aderencia', 'compatibilidade com vaga', 'match'], steps: ['Abra a vaga no espaço do candidato.', 'Consulte o indicador de compatibilidade quando estiver visível.', 'Use os pontos apresentados como orientação, não como garantia de contratação.', 'Se o recurso estiver associado a IA, só o trate como disponível quando a IA global estiver ativa e o produto estiver liberado.'] },
        ],
        consults: [{ label: 'Vaga e candidatura próprias', source: 'rotas autenticadas de vagas/aplicações do próprio usuário', rule: 'Consultar somente a candidatura do usuário autenticado; nunca dados de outros candidatos.' }],
        boundaries: ['Não revelar anotações internas da empresa, ranking de outros candidatos ou decisões de RH.', 'Não prometer retorno, entrevista ou contratação.'],
        related: ['public.jobs', 'candidate.resume'],
    },
    {
        id: 'candidate.resume',
        title: 'Currículo do candidato',
        audiences: ['CANDIDATE'],
        routes: ['/user/curriculo', '/user/curriculo/evolucao'],
        keywords: ['curriculo', 'currículo', 'publicar curriculo', 'pdf', 'template', 'modelo', 'experiencia', 'formacao', 'formação', 'habilidades', 'idiomas', 'curso', 'documento base', 'analise ia', 'melhorar curriculo'],
        summary: 'Estúdio de currículo, publicação, histórico/evolução e recursos de IA condicionados à configuração global e ao produto.',
        functions: [
            'Editar dados pessoais, preferências profissionais, experiências, formação, cursos, idiomas e habilidades que alimentam o currículo.',
            'Escolher apresentação/modelo disponível e visualizar o documento.',
            'Gerar/imprimir PDF a partir do preview do currículo.',
            'Publicar ou atualizar a versão pública quando o fluxo permitir.',
            'Acompanhar evolução/histórico em /user/curriculo/evolucao.',
            'Usar análise, importação ou melhoria por IA apenas se o recurso estiver habilitado e a pessoa tiver direito de uso quando houver cobrança.',
        ],
        procedures: [
            { title: 'Editar currículo', intents: ['editar curriculo', 'mudar experiencia', 'adicionar formação'], steps: ['Abra Meu currículo.', 'Escolha a seção correspondente ao dado que deseja alterar.', 'Edite e salve conforme os controles da tela.', 'Confira o preview antes de publicar ou exportar.'] },
            { title: 'Publicar currículo', intents: ['publicar curriculo', 'deixar curriculo publico'], steps: ['Abra Meu currículo.', 'Confira se os dados e a prévia estão corretos.', 'Abra a ação de versões/publicação quando apresentada.', 'Confirme a publicação. A versão publicada é um snapshot; alterações posteriores no rascunho podem precisar de nova publicação.'] },
            { title: 'Gerar PDF', intents: ['baixar pdf', 'imprimir curriculo'], steps: ['Abra Meu currículo.', 'Confira o modelo no preview.', 'Use a ação de PDF/impressão.', 'Na janela de impressão do navegador, escolha Salvar como PDF. Se cabeçalhos/rodapés nativos do navegador aparecerem, desative-os nas opções de impressão.'] },
            { title: 'Usar análise ou melhoria com IA', intents: ['analisar curriculo com ia', 'melhorar curriculo com ia', 'importar curriculo'], steps: ['Primeiro confirme que o recurso de IA aparece na tela; se não aparece, ele pode estar globalmente desabilitado.', 'Escolha a ação de análise, importação ou melhoria disponível.', 'Se houver cobrança ou limite, a própria interface informa a condição antes da execução.', 'Revise o resultado antes de substituir ou publicar dados.'] },
        ],
        consults: [
            { label: 'Estado do currículo', source: 'perfil do usuário: resumeStatus, resumePublishedAt e dados do currículo', rule: 'Somente dados do próprio usuário.' },
            { label: 'Disponibilidade de IA', source: 'status global da IA + status/entitlement específico do produto', rule: 'Não oferecer IA oculta ou desabilitada.' },
        ],
        boundaries: ['Não inventar competências, experiências ou formação.', 'Não dizer que uma análise gratuita/paga está disponível sem o status atual do produto.', 'Não expor snapshot ou currículo de outra pessoa.'],
        related: ['candidate.profile', 'candidate.preferences', 'candidate.payments', 'candidate.jobs'],
    },
    {
        id: 'candidate.profile',
        title: 'Perfil profissional',
        audiences: ['CANDIDATE'],
        routes: ['/user/perfil'],
        keywords: ['perfil profissional', 'foto', 'bio', 'dados profissionais', 'telefone', 'linkedin', 'experiencias', 'habilidades'],
        summary: 'Perfil profissional do próprio usuário e dados que podem alimentar currículo e oportunidades.',
        functions: ['Editar informações profissionais permitidas.', 'Atualizar foto quando o campo estiver disponível.', 'Manter dados coerentes com currículo e preferências.'],
        procedures: [{ title: 'Atualizar perfil', intents: ['editar perfil', 'trocar foto', 'mudar bio'], steps: ['Abra Perfil profissional.', 'Localize o campo desejado.', 'Edite o dado e salve.', 'Se a alteração também precisa aparecer no currículo publicado, abra Meu currículo e confira se é necessário republicar.'] }],
        consults: [{ label: 'Perfil próprio', source: 'GET/POST /users/me e contexto autenticado', rule: 'Nunca consultar outro usuário para responder ao candidato.' }],
        boundaries: ['Informações PcD são sensíveis; não inferir diagnóstico nem expor detalhes além do que a própria pessoa configurou.', 'Melhoria de foto com IA só aparece para foto de pessoa e quando IA global + IA de imagem estiverem habilitadas.'],
        related: ['candidate.resume', 'candidate.preferences'],
    },
    {
        id: 'candidate.preferences',
        title: 'Preferências e notificações do candidato',
        audiences: ['CANDIDATE'],
        routes: ['/user/preferencias', '/user/notificacoes'],
        keywords: ['preferencias', 'preferências', 'cnh', 'veiculo proprio', 'veículo próprio', 'pcd', 'local de trabalho', 'notificacao', 'notificação', 'push'],
        summary: 'Preferências profissionais e controles de notificações do próprio candidato.',
        functions: [
            'Configurar localidades preferidas.',
            'Informar CNH e categorias quando desejar.',
            'Informar veículo próprio quando desejar.',
            'Configurar preferência por oportunidades PcD e consentimentos aplicáveis.',
            'Configurar quais notificações push deseja receber; o sino interno pode seguir funcionando independentemente do push.',
        ],
        procedures: [
            { title: 'Alterar preferências de trabalho', intents: ['mudar preferencias', 'cnh', 'veiculo proprio', 'pcd'], steps: ['Abra Preferências.', 'Atualize somente as informações que deseja informar.', 'Salve.', 'Se alguma informação deve aparecer no currículo, confira o preview do currículo e as opções de publicação.'] },
            { title: 'Alterar notificações', intents: ['parar notificacao', 'ativar push'], steps: ['Abra Notificações.', 'Ative ou desative as categorias de push oferecidas.', 'Se o navegador pedir permissão, ela também precisa estar habilitada no dispositivo.', 'Desativar push não significa necessariamente remover notificações internas do sino.'] },
        ],
        boundaries: ['Nunca pressionar a pessoa a informar PcD ou dado sensível.', 'Não dizer que desativar push apaga o histórico interno.'],
        related: ['candidate.resume', 'candidate.profile'],
    },
    {
        id: 'candidate.payments',
        title: 'Pagamentos e produtos do candidato',
        audiences: ['CANDIDATE'],
        routes: ['/user/pagamentos'],
        keywords: ['pagamento', 'pix', 'compra', 'cobrança', 'cobranca', 'analise paga', 'melhoria paga', 'historico pagamento', 'status pagamento'],
        summary: 'Área do usuário para produtos e histórico de pagamentos ligados à própria conta.',
        functions: ['Consultar produtos disponibilizados ao usuário.', 'Iniciar pagamento pelo método apresentado pelo sistema.', 'Acompanhar histórico/status das próprias compras.'],
        procedures: [
            { title: 'Pagar um produto', intents: ['como pagar', 'pix', 'comprar analise'], steps: ['Abra Pagamentos ou a ação de compra apresentada pelo recurso.', 'Confira produto, valor e condição exibidos.', 'Gere/inicie o pagamento pelo provedor disponível.', 'Aguarde a confirmação do sistema antes de repetir a compra.'] },
            { title: 'Pagamento não liberou recurso', intents: ['paguei e nao liberou', 'pagamento pendente'], steps: ['Abra Pagamentos e confira o status da transação.', 'Evite pagar novamente enquanto houver uma cobrança pendente sem antes conferir a atualização.', 'Se o status pago estiver confirmado e o direito não aparecer, encaminhe para suporte de cobrança com o identificador exibido ao usuário, sem pedir segredos ou credenciais bancárias.'] },
        ],
        consults: [{ label: 'Histórico próprio', source: 'endpoints autenticados de payments para o usuário', rule: 'Somente transações da própria conta; nunca configuração do provedor ou credenciais.' }],
        boundaries: ['Nunca expor chaves, tokens, credenciais ou configuração de gateways.', 'Não afirmar que um pagamento foi aprovado sem consultar o status real.'],
        related: ['candidate.resume'],
    },
    {
        id: 'candidate.classifieds',
        title: 'Meus classificados',
        audiences: ['CANDIDATE', 'COMPANY'],
        routes: ['/user/classificados', '/user/classificados/novo'],
        keywords: ['meus anuncios', 'meus anúncios', 'publicar anuncio', 'vender', 'favoritos', 'pausar anuncio', 'marcar vendido', 'fotos anuncio'],
        summary: 'Gestão autenticada de anúncios e favoritos, incluindo o fluxo de publicação em etapas.',
        functions: ['Criar anúncio.', 'Enviar até o limite de fotos aceito pela tela.', 'Salvar/publicar conforme o fluxo.', 'Pausar, marcar vendido ou arquivar anúncio próprio.', 'Consultar favoritos próprios.'],
        procedures: [
            { title: 'Publicar anúncio', intents: ['publicar anuncio', 'vender produto'], steps: ['Abra Meus classificados e escolha Novo anúncio, ou /user/classificados/novo.', 'Escolha a categoria.', 'Informe título, preço/condição e descrição.', 'Adicione fotos.', 'Preencha características específicas da categoria quando houver.', 'Informe localização e contato.', 'Revise e publique.'] },
            { title: 'Gerenciar anúncio', intents: ['pausar anuncio', 'vendi', 'arquivar'], steps: ['Abra Meus classificados.', 'Localize o anúncio.', 'Escolha a ação disponível: pausar, marcar como vendido, arquivar ou editar.', 'Confirme o novo estado na própria listagem.'] },
        ],
        consults: [{ label: 'Anúncios próprios', source: 'GET /classifieds/mine e endpoints autenticados de classifieds', rule: 'Somente anúncios cujo sellerUserId é o usuário autenticado.' }],
        boundaries: ['Não permitir alteração de anúncio de outro vendedor.', 'Vínculo simples com empresa não autoriza publicar em nome dela; somente proprietário/administrador empresarial deve usar identidade da empresa.'],
        related: ['public.classifieds'],
    },
    {
        id: 'candidate.onboarding',
        title: 'Onboarding e admissão do candidato',
        audiences: ['CANDIDATE'],
        routes: ['/user/onboarding', '/user/admissao/', '/convites/vaga/'],
        keywords: ['onboarding', 'cadastro inicial', 'admissao', 'admissão', 'convite', 'aceitar convite', 'documentos contratação'],
        summary: 'Fluxos de configuração inicial da conta, convite de vaga e etapas de admissão quando a empresa iniciou esse processo.',
        functions: ['Completar dados mínimos da conta.', 'Acessar convite por token válido.', 'Preencher etapas de admissão disponibilizadas para uma candidatura própria.'],
        procedures: [
            { title: 'Completar onboarding', intents: ['terminar cadastro', 'onboarding'], steps: ['Abra a etapa indicada pelo sistema.', 'Preencha os campos obrigatórios.', 'Salve/continue até o sistema liberar o workspace correspondente.'] },
            { title: 'Responder convite', intents: ['convite vaga', 'aceitar convite'], steps: ['Abra o link do convite recebido.', 'Confira a vaga e a empresa apresentadas.', 'Use a ação disponível para responder ao convite.', 'Depois de aceito/recusado, não orientar reenvio como se o convite ainda estivesse pendente.'] },
            { title: 'Acessar admissão', intents: ['documentos admissao', 'processo admissional'], steps: ['Abra a candidatura/admissão indicada.', 'Preencha apenas os dados solicitados para aquela etapa.', 'Envie documentos somente nos campos oficiais.', 'Acompanhe o andamento pelo próprio fluxo; a IA não deve declarar aprovação se o sistema não informa isso.'] },
        ],
        boundaries: ['Nunca expor etapas de admissão de outro candidato.', 'Não solicitar documentos pelo chat quando o sistema oferece campo próprio e seguro.'],
        related: ['candidate.jobs'],
    },
    {
        id: 'candidate.account',
        title: 'Configurações da conta',
        audiences: ['CANDIDATE', 'COMPANY'],
        routes: ['/user/configuracoes'],
        keywords: ['configuracoes', 'configurações', 'conta', 'senha', 'email', 'sair', 'dados da conta'],
        summary: 'Configurações pessoais da conta autenticada.',
        functions: ['Gerenciar opções expostas na tela de configurações.', 'Acessar preferências relacionadas à conta.', 'Sair da conta pelo controle de logout do workspace.'],
        procedures: [{ title: 'Alterar configuração da conta', intents: ['mudar configuracao', 'configurar conta'], steps: ['Abra Configurações.', 'Localize a opção disponível.', 'Altere e salve.', 'Se a opção não existe na tela, não invente um caminho; oriente a usar o suporte.'] }],
        boundaries: ['Nunca pedir senha, token Firebase, código de sessão ou segredo de autenticação no chat.'],
    },
];
//# sourceMappingURL=candidate.js.map