import { Repository } from 'typeorm';
import { WhatsAppApiKey } from './entities/whatsapp-api-key.entity';
import { WhatsAppService } from './whatsapp.service';
export declare class WhatsAppAdminController {
    private readonly whatsapp;
    private readonly keysRepository;
    constructor(whatsapp: WhatsAppService, keysRepository: Repository<WhatsAppApiKey>);
    capabilities(): import("./whatsapp.scopes").WhatsAppCapability[];
    listInstances(): Promise<{
        connected: boolean;
        qrCode: string | null;
        runtimeDetail: string | null;
        runtimeUpdatedAt: string | null;
        keyCount: number;
        messageCount: number;
        capabilities: {
            messages: boolean;
            contacts: boolean;
            groups: boolean;
            groupHistory: boolean;
            groupMedia: boolean;
            groupModeration: boolean;
            channels: string;
            status: boolean;
            multiSession: boolean;
            mcp: boolean;
            concierge: boolean;
            otp: boolean;
        };
        id: string;
        name: string;
        purpose: string | null;
        phoneNumber: string | null;
        sessionName: string;
        provider: string;
        status: import("./entities/whatsapp-instance.entity").WhatsAppConnectionStatus;
        allowedScopes: string[];
        active: boolean;
        isPrimarySupport: boolean;
        conciergeEnabled: boolean;
        lastError: string | null;
        lastConnectedAt: Date | null;
        lastSeenAt: Date | null;
        createdById: string;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    createInstance(req: any, body: Record<string, unknown>): Promise<{
        connected: boolean;
        qrCode: string | null;
        runtimeDetail: string | null;
        runtimeUpdatedAt: string | null;
        keyCount: number;
        messageCount: number;
        capabilities: {
            messages: boolean;
            contacts: boolean;
            groups: boolean;
            groupHistory: boolean;
            groupMedia: boolean;
            groupModeration: boolean;
            channels: string;
            status: boolean;
            multiSession: boolean;
            mcp: boolean;
            concierge: boolean;
            otp: boolean;
        };
        id: string;
        name: string;
        purpose: string | null;
        phoneNumber: string | null;
        sessionName: string;
        provider: string;
        status: import("./entities/whatsapp-instance.entity").WhatsAppConnectionStatus;
        allowedScopes: string[];
        active: boolean;
        isPrimarySupport: boolean;
        conciergeEnabled: boolean;
        lastError: string | null;
        lastConnectedAt: Date | null;
        lastSeenAt: Date | null;
        createdById: string;
        createdAt: Date;
        updatedAt: Date;
    }>;
    getInstance(id: string): Promise<{
        connected: boolean;
        qrCode: string | null;
        runtimeDetail: string | null;
        runtimeUpdatedAt: string | null;
        keyCount: number;
        messageCount: number;
        capabilities: {
            messages: boolean;
            contacts: boolean;
            groups: boolean;
            groupHistory: boolean;
            groupMedia: boolean;
            groupModeration: boolean;
            channels: string;
            status: boolean;
            multiSession: boolean;
            mcp: boolean;
            concierge: boolean;
            otp: boolean;
        };
        id: string;
        name: string;
        purpose: string | null;
        phoneNumber: string | null;
        sessionName: string;
        provider: string;
        status: import("./entities/whatsapp-instance.entity").WhatsAppConnectionStatus;
        allowedScopes: string[];
        active: boolean;
        isPrimarySupport: boolean;
        conciergeEnabled: boolean;
        lastError: string | null;
        lastConnectedAt: Date | null;
        lastSeenAt: Date | null;
        createdById: string;
        createdAt: Date;
        updatedAt: Date;
    }>;
    updateInstance(id: string, body: Record<string, unknown>): Promise<{
        connected: boolean;
        qrCode: string | null;
        runtimeDetail: string | null;
        runtimeUpdatedAt: string | null;
        keyCount: number;
        messageCount: number;
        capabilities: {
            messages: boolean;
            contacts: boolean;
            groups: boolean;
            groupHistory: boolean;
            groupMedia: boolean;
            groupModeration: boolean;
            channels: string;
            status: boolean;
            multiSession: boolean;
            mcp: boolean;
            concierge: boolean;
            otp: boolean;
        };
        id: string;
        name: string;
        purpose: string | null;
        phoneNumber: string | null;
        sessionName: string;
        provider: string;
        status: import("./entities/whatsapp-instance.entity").WhatsAppConnectionStatus;
        allowedScopes: string[];
        active: boolean;
        isPrimarySupport: boolean;
        conciergeEnabled: boolean;
        lastError: string | null;
        lastConnectedAt: Date | null;
        lastSeenAt: Date | null;
        createdById: string;
        createdAt: Date;
        updatedAt: Date;
    }>;
    removeInstance(id: string): Promise<{
        ok: boolean;
    }>;
    connect(id: string): Promise<{
        connected: boolean;
        qrCode: string | null;
        runtimeDetail: string | null;
        runtimeUpdatedAt: string | null;
        keyCount: number;
        messageCount: number;
        capabilities: {
            messages: boolean;
            contacts: boolean;
            groups: boolean;
            groupHistory: boolean;
            groupMedia: boolean;
            groupModeration: boolean;
            channels: string;
            status: boolean;
            multiSession: boolean;
            mcp: boolean;
            concierge: boolean;
            otp: boolean;
        };
        id: string;
        name: string;
        purpose: string | null;
        phoneNumber: string | null;
        sessionName: string;
        provider: string;
        status: import("./entities/whatsapp-instance.entity").WhatsAppConnectionStatus;
        allowedScopes: string[];
        active: boolean;
        isPrimarySupport: boolean;
        conciergeEnabled: boolean;
        lastError: string | null;
        lastConnectedAt: Date | null;
        lastSeenAt: Date | null;
        createdById: string;
        createdAt: Date;
        updatedAt: Date;
    }>;
    disconnect(id: string, body: {
        logout?: boolean;
    }): Promise<{
        connected: boolean;
        qrCode: string | null;
        runtimeDetail: string | null;
        runtimeUpdatedAt: string | null;
        keyCount: number;
        messageCount: number;
        capabilities: {
            messages: boolean;
            contacts: boolean;
            groups: boolean;
            groupHistory: boolean;
            groupMedia: boolean;
            groupModeration: boolean;
            channels: string;
            status: boolean;
            multiSession: boolean;
            mcp: boolean;
            concierge: boolean;
            otp: boolean;
        };
        id: string;
        name: string;
        purpose: string | null;
        phoneNumber: string | null;
        sessionName: string;
        provider: string;
        status: import("./entities/whatsapp-instance.entity").WhatsAppConnectionStatus;
        allowedScopes: string[];
        active: boolean;
        isPrimarySupport: boolean;
        conciergeEnabled: boolean;
        lastError: string | null;
        lastConnectedAt: Date | null;
        lastSeenAt: Date | null;
        createdById: string;
        createdAt: Date;
        updatedAt: Date;
    }>;
    contacts(id: string): Promise<any[]>;
    savedContacts(id: string): Promise<import("./entities/whatsapp-contact.entity").WhatsAppSavedContact[]>;
    saveContact(id: string, body: {
        phoneNumber?: string;
        name?: string;
        notes?: string;
    }): Promise<import("./entities/whatsapp-contact.entity").WhatsAppSavedContact>;
    groups(id: string): Promise<any[]>;
    channels(id: string): Promise<any[]>;
    messages(id: string, limit?: string): Promise<import("./entities/whatsapp-message.entity").WhatsAppMessage[]>;
    testMessage(id: string, body: {
        target?: string;
        text?: string;
    }): Promise<{
        ok: boolean;
        chatId: string;
        result: any;
    }>;
    keys(id: string): Promise<WhatsAppApiKey[]>;
    createKey(req: any, id: string, body: Record<string, unknown>): Promise<{
        key: {
            id: string;
            instanceId: string;
            name: string;
            keyPrefix: string;
            scopes: string[];
            active: boolean;
            createdById: string;
            lastUsedAt: Date | null;
            expiresAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        apiKey: string;
        warning: string;
    }>;
    updateKey(keyId: string, body: Record<string, unknown>): Promise<{
        id: string;
        instanceId: string;
        name: string;
        keyPrefix: string;
        scopes: string[];
        active: boolean;
        createdById: string;
        lastUsedAt: Date | null;
        expiresAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    rotateKey(keyId: string): Promise<{
        apiKey: string;
        warning: string;
    }>;
    removeKey(keyId: string): Promise<{
        ok: boolean;
    }>;
}
