import { Repository } from 'typeorm';
import { ResumeImportService } from '../ai/resume-import.service';
import { Application } from '../applications/entities/application.entity';
import { BillingSupportService } from '../payments/billing-support.service';
import { PaymentsService } from '../payments/payments.service';
import { Company } from '../companies/entities/company.entity';
import { CompanyPlansService } from '../company-plans/company-plans.service';
import { CompanyWhatsAppPremiumService } from '../company-plans/company-whatsapp-premium.service';
import { Job } from '../jobs/entities/job.entity';
import { JobsService } from '../jobs/jobs.service';
import { JobMatchService } from '../job-match/job-match.service';
import { User } from '../users/entities/user.entity';
import { WhatsAppConversation } from './entities/whatsapp-concierge.entity';
import { WhatsAppInstance } from './entities/whatsapp-instance.entity';
import { WhatsAppMessage } from './entities/whatsapp-message.entity';
import { WhatsAppAiService } from './whatsapp-ai.service';
import { WhatsAppAlertService } from './whatsapp-alert.service';
export declare class WhatsAppConciergeService {
    private readonly users;
    private readonly companies;
    private readonly jobs;
    private readonly applications;
    private readonly conversations;
    private readonly whatsappMessages;
    private readonly jobsService;
    private readonly jobMatch;
    private readonly resumeImport;
    private readonly payments;
    private readonly billingSupport;
    private readonly ai;
    private readonly alerts;
    private readonly companyPlans;
    private readonly companyPremium;
    private readonly logger;
    private readonly buffers;
    constructor(users: Repository<User>, companies: Repository<Company>, jobs: Repository<Job>, applications: Repository<Application>, conversations: Repository<WhatsAppConversation>, whatsappMessages: Repository<WhatsAppMessage>, jobsService: JobsService, jobMatch: JobMatchService, resumeImport: ResumeImportService, payments: PaymentsService, billingSupport: BillingSupportService, ai: WhatsAppAiService, alerts: WhatsAppAlertService, companyPlans: CompanyPlansService, companyPremium: CompanyWhatsAppPremiumService);
    handleInbound(instance: WhatsAppInstance, message: any, client: any): Promise<{
        accepted: boolean;
        buffered?: undefined;
        deadlineAt?: undefined;
    } | {
        accepted: boolean;
        buffered: number;
        deadlineAt: string;
    }>;
    private flush;
    private executeDecision;
    private handleCompanyPremiumDecision;
    private resolveCompanyJobId;
    private companyJobChoiceReply;
    private resumeCreationFlow;
    private jobCreationFlow;
    private jobEditFlow;
    private contextSnapshot;
    private collectResumeDocuments;
    private importResumeWithBilling;
    private applyImportedResume;
    private persistImageFromMessage;
    private resolvePlatformActor;
    private resolveWhatsAppIdentity;
    private isDirectHumanInbound;
    private toBufferedInbound;
    private touchConversation;
    private recentHistory;
    private sendText;
    private formatAdminReply;
    private readContextChoice;
    private firstName;
    private serializeWid;
    private canonicalBrazilPhone;
    private phoneVariants;
    private extensionForMime;
    private safeId;
    private isCompanyPlanRequired;
    private companyPlanPayload;
    private isPaymentRequired;
    private errorText;
}
