import { OnModuleDestroy, OnModuleInit } from '@nestjs/common';
import { Repository } from 'typeorm';
import { WhatsAppApiKey } from './entities/whatsapp-api-key.entity';
import { WhatsAppSavedContact } from './entities/whatsapp-contact.entity';
import { WhatsAppConnectionStatus, WhatsAppInstance } from './entities/whatsapp-instance.entity';
import { WhatsAppMessage } from './entities/whatsapp-message.entity';
import { WhatsAppAlertService } from './whatsapp-alert.service';
import { WhatsAppConciergeService } from './whatsapp-concierge.service';
export declare class WhatsAppService implements OnModuleInit, OnModuleDestroy {
    private readonly instances;
    private readonly keys;
    private readonly messages;
    private readonly savedContacts;
    private readonly concierge;
    private readonly alerts;
    private readonly logger;
    private readonly clients;
    private readonly states;
    private readonly connecting;
    private readonly expectedDisconnects;
    constructor(instances: Repository<WhatsAppInstance>, keys: Repository<WhatsAppApiKey>, messages: Repository<WhatsAppMessage>, savedContacts: Repository<WhatsAppSavedContact>, concierge: WhatsAppConciergeService, alerts: WhatsAppAlertService);
    onModuleInit(): Promise<void>;
    onModuleDestroy(): Promise<void>;
    listInstances(): Promise<{
        connected: boolean;
        qrCode: string | null;
        runtimeDetail: string | null;
        runtimeUpdatedAt: string | null;
        keyCount: number;
        messageCount: number;
        capabilities: {
            messages: boolean;
            contacts: boolean;
            groups: boolean;
            groupHistory: boolean;
            groupMedia: boolean;
            groupModeration: boolean;
            channels: string;
            status: boolean;
            multiSession: boolean;
            mcp: boolean;
            concierge: boolean;
            otp: boolean;
        };
        id: string;
        name: string;
        purpose: string | null;
        phoneNumber: string | null;
        sessionName: string;
        provider: string;
        status: WhatsAppConnectionStatus;
        allowedScopes: string[];
        active: boolean;
        isPrimarySupport: boolean;
        conciergeEnabled: boolean;
        lastError: string | null;
        lastConnectedAt: Date | null;
        lastSeenAt: Date | null;
        createdById: string;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    getInstance(id: string): Promise<WhatsAppInstance>;
    createInstance(createdById: string, data: Record<string, unknown>): Promise<{
        connected: boolean;
        qrCode: string | null;
        runtimeDetail: string | null;
        runtimeUpdatedAt: string | null;
        keyCount: number;
        messageCount: number;
        capabilities: {
            messages: boolean;
            contacts: boolean;
            groups: boolean;
            groupHistory: boolean;
            groupMedia: boolean;
            groupModeration: boolean;
            channels: string;
            status: boolean;
            multiSession: boolean;
            mcp: boolean;
            concierge: boolean;
            otp: boolean;
        };
        id: string;
        name: string;
        purpose: string | null;
        phoneNumber: string | null;
        sessionName: string;
        provider: string;
        status: WhatsAppConnectionStatus;
        allowedScopes: string[];
        active: boolean;
        isPrimarySupport: boolean;
        conciergeEnabled: boolean;
        lastError: string | null;
        lastConnectedAt: Date | null;
        lastSeenAt: Date | null;
        createdById: string;
        createdAt: Date;
        updatedAt: Date;
    }>;
    updateInstance(id: string, data: Record<string, unknown>): Promise<{
        connected: boolean;
        qrCode: string | null;
        runtimeDetail: string | null;
        runtimeUpdatedAt: string | null;
        keyCount: number;
        messageCount: number;
        capabilities: {
            messages: boolean;
            contacts: boolean;
            groups: boolean;
            groupHistory: boolean;
            groupMedia: boolean;
            groupModeration: boolean;
            channels: string;
            status: boolean;
            multiSession: boolean;
            mcp: boolean;
            concierge: boolean;
            otp: boolean;
        };
        id: string;
        name: string;
        purpose: string | null;
        phoneNumber: string | null;
        sessionName: string;
        provider: string;
        status: WhatsAppConnectionStatus;
        allowedScopes: string[];
        active: boolean;
        isPrimarySupport: boolean;
        conciergeEnabled: boolean;
        lastError: string | null;
        lastConnectedAt: Date | null;
        lastSeenAt: Date | null;
        createdById: string;
        createdAt: Date;
        updatedAt: Date;
    }>;
    removeInstance(id: string): Promise<{
        ok: boolean;
    }>;
    connect(id: string): Promise<{
        connected: boolean;
        qrCode: string | null;
        runtimeDetail: string | null;
        runtimeUpdatedAt: string | null;
        keyCount: number;
        messageCount: number;
        capabilities: {
            messages: boolean;
            contacts: boolean;
            groups: boolean;
            groupHistory: boolean;
            groupMedia: boolean;
            groupModeration: boolean;
            channels: string;
            status: boolean;
            multiSession: boolean;
            mcp: boolean;
            concierge: boolean;
            otp: boolean;
        };
        id: string;
        name: string;
        purpose: string | null;
        phoneNumber: string | null;
        sessionName: string;
        provider: string;
        status: WhatsAppConnectionStatus;
        allowedScopes: string[];
        active: boolean;
        isPrimarySupport: boolean;
        conciergeEnabled: boolean;
        lastError: string | null;
        lastConnectedAt: Date | null;
        lastSeenAt: Date | null;
        createdById: string;
        createdAt: Date;
        updatedAt: Date;
    }>;
    private connectInternal;
    disconnect(id: string, logout?: boolean): Promise<{
        connected: boolean;
        qrCode: string | null;
        runtimeDetail: string | null;
        runtimeUpdatedAt: string | null;
        keyCount: number;
        messageCount: number;
        capabilities: {
            messages: boolean;
            contacts: boolean;
            groups: boolean;
            groupHistory: boolean;
            groupMedia: boolean;
            groupModeration: boolean;
            channels: string;
            status: boolean;
            multiSession: boolean;
            mcp: boolean;
            concierge: boolean;
            otp: boolean;
        };
        id: string;
        name: string;
        purpose: string | null;
        phoneNumber: string | null;
        sessionName: string;
        provider: string;
        status: WhatsAppConnectionStatus;
        allowedScopes: string[];
        active: boolean;
        isPrimarySupport: boolean;
        conciergeEnabled: boolean;
        lastError: string | null;
        lastConnectedAt: Date | null;
        lastSeenAt: Date | null;
        createdById: string;
        createdAt: Date;
        updatedAt: Date;
    }>;
    status(id: string): Promise<{
        connected: boolean;
        qrCode: string | null;
        runtimeDetail: string | null;
        runtimeUpdatedAt: string | null;
        keyCount: number;
        messageCount: number;
        capabilities: {
            messages: boolean;
            contacts: boolean;
            groups: boolean;
            groupHistory: boolean;
            groupMedia: boolean;
            groupModeration: boolean;
            channels: string;
            status: boolean;
            multiSession: boolean;
            mcp: boolean;
            concierge: boolean;
            otp: boolean;
        };
        id: string;
        name: string;
        purpose: string | null;
        phoneNumber: string | null;
        sessionName: string;
        provider: string;
        status: WhatsAppConnectionStatus;
        allowedScopes: string[];
        active: boolean;
        isPrimarySupport: boolean;
        conciergeEnabled: boolean;
        lastError: string | null;
        lastConnectedAt: Date | null;
        lastSeenAt: Date | null;
        createdById: string;
        createdAt: Date;
        updatedAt: Date;
    }>;
    checkNumberStatus(id: string, phone: string): Promise<any>;
    resolvePnLid(id: string, phoneOrLid: string): Promise<any>;
    listContacts(id: string): Promise<any[]>;
    listGroups(id: string): Promise<any[]>;
    getGroupHistory(id: string, groupId: string, options: {
        count?: number;
        beforeMessageId?: string;
        media?: 'all' | 'image' | 'document' | 'url';
    }): Promise<{
        id: any;
        from: any;
        to: any;
        author: any;
        body: any;
        caption: any;
        type: string;
        timestamp: any;
        fromMe: boolean;
        isGroupMsg: boolean;
        isMedia: boolean;
        mimetype: any;
        quotedMsgId: any;
        mentionedJidList: any;
    }[]>;
    getGroupMedia(id: string, messageId: string): Promise<{
        message: {
            id: any;
            from: any;
            to: any;
            author: any;
            body: any;
            caption: any;
            type: string;
            timestamp: any;
            fromMe: boolean;
            isGroupMsg: boolean;
            isMedia: boolean;
            mimetype: any;
            quotedMsgId: any;
            mentionedJidList: any;
        };
        mimeType: string;
        data: string;
    }>;
    listGroupMembers(id: string, groupId: string): Promise<any[]>;
    joinGroup(id: string, inviteCodeOrLink: string): Promise<{
        ok: boolean;
        info: any;
        result: any;
    }>;
    addGroupParticipant(id: string, groupId: string, participantId: string): Promise<{
        ok: boolean;
        groupId: string;
        participantId: string;
        result: any;
    }>;
    removeGroupParticipant(id: string, groupId: string, participantId: string): Promise<{
        ok: boolean;
        groupId: string;
        participantId: string;
    }>;
    replyGroupMessage(id: string, groupId: string, messageId: string, text: string): Promise<{
        ok: boolean;
        groupId: string;
        quotedMessageId: string;
        result: any;
    }>;
    reactToGroupMessage(id: string, messageId: string, reaction: string | false): Promise<{
        ok: boolean;
        result: any;
    }>;
    deleteGroupMessage(id: string, groupId: string, messageId: string): Promise<{
        ok: boolean;
        groupId: string;
        messageId: string;
        result: any;
    }>;
    listGroupMembershipRequests(id: string, groupId: string): Promise<any[]>;
    approveGroupMembershipRequest(id: string, groupId: string, participantId: string): Promise<{
        ok: boolean;
        groupId: string;
        participantId: string;
        result: any;
    }>;
    rejectGroupMembershipRequest(id: string, groupId: string, participantId: string): Promise<{
        ok: boolean;
        groupId: string;
        participantId: string;
        result: any;
    }>;
    listChannels(id: string): Promise<any[]>;
    sendText(id: string, target: string, text: string): Promise<{
        ok: boolean;
        chatId: string;
        result: any;
    }>;
    sendMedia(id: string, target: string, media: string, filename?: string, caption?: string): Promise<{
        ok: boolean;
        chatId: string;
        result: any;
    }>;
    publishChannel(id: string, channelId: string, text: string): Promise<{
        ok: boolean;
        chatId: string;
        result: any;
    }>;
    publishStatus(id: string, data: {
        text?: string;
        media?: string;
        caption?: string;
    }): Promise<{
        ok: boolean;
    }>;
    listMessages(id: string, limit?: number): Promise<WhatsAppMessage[]>;
    saveContact(id: string, data: {
        phoneNumber?: string;
        name?: string;
        notes?: string;
    }): Promise<WhatsAppSavedContact>;
    listSavedContacts(id: string): Promise<WhatsAppSavedContact[]>;
    listKeys(instanceId: string): Promise<WhatsAppApiKey[]>;
    createKey(instanceId: string, createdById: string, data: Record<string, unknown>): Promise<{
        key: {
            id: string;
            instanceId: string;
            name: string;
            keyPrefix: string;
            scopes: string[];
            active: boolean;
            createdById: string;
            lastUsedAt: Date | null;
            expiresAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        apiKey: string;
        warning: string;
    }>;
    updateKey(keyId: string, data: Record<string, unknown>): Promise<{
        id: string;
        instanceId: string;
        name: string;
        keyPrefix: string;
        scopes: string[];
        active: boolean;
        createdById: string;
        lastUsedAt: Date | null;
        expiresAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    rotateKey(keyId: string): Promise<{
        apiKey: string;
        warning: string;
    }>;
    private requireClient;
    private decorateInstance;
    private setRuntime;
    private setStatus;
    private setStatusById;
    private notifyUnexpectedDisconnect;
    private capturePhoneNumber;
    private storeInbound;
    private storeOutbound;
    private publicMessage;
    private normalizeGroupId;
    private normalizeParticipantId;
    private normalizeChatId;
    private serializeWid;
    private onlyDigits;
    private newKey;
    private hash;
    private publicKey;
    private errorMessage;
}
