import { Repository } from 'typeorm';
import { ClassifiedsCategoryTaxonomyService } from './classifieds-category-taxonomy.service';
import { ClassifiedsCommerceService } from './classifieds-commerce.service';
import { ClassifiedsService } from './classifieds.service';
import { CompanyClassifiedProfile } from './entities/company-classified-profile.entity';
export declare class ClassifiedsPublicController {
    private readonly classifieds;
    private readonly taxonomy;
    private readonly commerce;
    private readonly companyProfiles;
    constructor(classifieds: ClassifiedsService, taxonomy: ClassifiedsCategoryTaxonomyService, commerce: ClassifiedsCommerceService, companyProfiles: Repository<CompanyClassifiedProfile>);
    categories(): Promise<any>;
    search(query: Record<string, unknown>): Promise<{
        items: {
            images: {
                id: string;
                url: string;
                sortOrder: number;
                isPrimary: boolean;
            }[];
            isFavorite: boolean;
            id: string;
            slug: string;
            sellerUserId: string;
            companyId: string | null;
            categorySlug: string;
            listingType: import("./entities/classified-listing.entity").ClassifiedListingType;
            title: string;
            description: string;
            price: string | null;
            priceType: import("./entities/classified-listing.entity").ClassifiedPriceType;
            condition: import("./entities/classified-listing.entity").ClassifiedCondition;
            city: string;
            state: string;
            neighborhood: string | null;
            zipCode: string | null;
            latitude: string | null;
            longitude: string | null;
            deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
            status: import("./entities/classified-listing.entity").ClassifiedListingStatus;
            isFeatured: boolean;
            sellerVerifiedSnapshot: boolean;
            viewsCount: number;
            favoritesCount: number;
            attributes: Record<string, string | number | boolean | null> | null;
            publicationChannels: import("./entities/classified-listing.entity").ClassifiedPublicationChannel[];
            catalogConfig: import("./entities/classified-listing.entity").ClassifiedCatalogConfig | null;
            commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
            contactPhone: string | null;
            contactWhatsapp: string | null;
            moderationReason: string | null;
            duplicateOfListingId: string | null;
            moderationReviewedAt: Date | null;
            publishedAt: Date | null;
            expiresAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        }[];
        total: number;
        page: number;
        limit: number;
        pages: number;
    }>;
    companyListings(companyId: string): Promise<{
        items: {
            images: {
                id: string;
                url: string;
                sortOrder: number;
                isPrimary: boolean;
            }[];
            isFavorite: boolean;
            id: string;
            slug: string;
            sellerUserId: string;
            companyId: string | null;
            categorySlug: string;
            listingType: import("./entities/classified-listing.entity").ClassifiedListingType;
            title: string;
            description: string;
            price: string | null;
            priceType: import("./entities/classified-listing.entity").ClassifiedPriceType;
            condition: import("./entities/classified-listing.entity").ClassifiedCondition;
            city: string;
            state: string;
            neighborhood: string | null;
            zipCode: string | null;
            latitude: string | null;
            longitude: string | null;
            deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
            status: import("./entities/classified-listing.entity").ClassifiedListingStatus;
            isFeatured: boolean;
            sellerVerifiedSnapshot: boolean;
            viewsCount: number;
            favoritesCount: number;
            attributes: Record<string, string | number | boolean | null> | null;
            publicationChannels: import("./entities/classified-listing.entity").ClassifiedPublicationChannel[];
            catalogConfig: import("./entities/classified-listing.entity").ClassifiedCatalogConfig | null;
            commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
            contactPhone: string | null;
            contactWhatsapp: string | null;
            moderationReason: string | null;
            duplicateOfListingId: string | null;
            moderationReviewedAt: Date | null;
            publishedAt: Date | null;
            expiresAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        }[];
        pageSectionLabel: string | null;
    }>;
    detail(slug: string): Promise<{
        seller: {
            id: string;
            type: string;
            name: string;
            photoURL: string | null;
            verified: boolean;
            memberSince: Date | null;
            city: string;
            state: string;
            companySlug: string | null;
        };
        related: {
            images: {
                id: string;
                url: string;
                sortOrder: number;
                isPrimary: boolean;
            }[];
            isFavorite: boolean;
            id: string;
            slug: string;
            sellerUserId: string;
            companyId: string | null;
            categorySlug: string;
            listingType: import("./entities/classified-listing.entity").ClassifiedListingType;
            title: string;
            description: string;
            price: string | null;
            priceType: import("./entities/classified-listing.entity").ClassifiedPriceType;
            condition: import("./entities/classified-listing.entity").ClassifiedCondition;
            city: string;
            state: string;
            neighborhood: string | null;
            zipCode: string | null;
            latitude: string | null;
            longitude: string | null;
            deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
            status: import("./entities/classified-listing.entity").ClassifiedListingStatus;
            isFeatured: boolean;
            sellerVerifiedSnapshot: boolean;
            viewsCount: number;
            favoritesCount: number;
            attributes: Record<string, string | number | boolean | null> | null;
            publicationChannels: import("./entities/classified-listing.entity").ClassifiedPublicationChannel[];
            catalogConfig: import("./entities/classified-listing.entity").ClassifiedCatalogConfig | null;
            commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
            contactPhone: string | null;
            contactWhatsapp: string | null;
            moderationReason: string | null;
            duplicateOfListingId: string | null;
            moderationReviewedAt: Date | null;
            publishedAt: Date | null;
            expiresAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        }[];
        images: {
            id: string;
            url: string;
            sortOrder: number;
            isPrimary: boolean;
        }[];
        isFavorite: boolean;
        id: string;
        slug: string;
        sellerUserId: string;
        companyId: string | null;
        categorySlug: string;
        listingType: import("./entities/classified-listing.entity").ClassifiedListingType;
        title: string;
        description: string;
        price: string | null;
        priceType: import("./entities/classified-listing.entity").ClassifiedPriceType;
        condition: import("./entities/classified-listing.entity").ClassifiedCondition;
        city: string;
        state: string;
        neighborhood: string | null;
        zipCode: string | null;
        latitude: string | null;
        longitude: string | null;
        deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
        status: import("./entities/classified-listing.entity").ClassifiedListingStatus;
        isFeatured: boolean;
        sellerVerifiedSnapshot: boolean;
        viewsCount: number;
        favoritesCount: number;
        attributes: Record<string, string | number | boolean | null> | null;
        publicationChannels: import("./entities/classified-listing.entity").ClassifiedPublicationChannel[];
        catalogConfig: import("./entities/classified-listing.entity").ClassifiedCatalogConfig | null;
        commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
        contactPhone: string | null;
        contactWhatsapp: string | null;
        moderationReason: string | null;
        duplicateOfListingId: string | null;
        moderationReviewedAt: Date | null;
        publishedAt: Date | null;
        expiresAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    event(id: string, body: any): Promise<{
        ok: boolean;
    }>;
}
