import { Repository } from 'typeorm';
import { Company } from '../companies/entities/company.entity';
import { User } from '../users/entities/user.entity';
import { ClassifiedsIdentityService } from './classifieds-identity.service';
import { ClassifiedCategory } from './entities/classified-category.entity';
import { ClassifiedFavorite } from './entities/classified-favorite.entity';
import { ClassifiedListingImage } from './entities/classified-listing-image.entity';
import { ClassifiedCatalogConfig, ClassifiedCondition, ClassifiedListing, ClassifiedListingStatus, ClassifiedListingType, ClassifiedPriceType, ClassifiedPublicationChannel } from './entities/classified-listing.entity';
export declare class ClassifiedsService {
    private readonly categoriesRepo;
    private readonly listingsRepo;
    private readonly imagesRepo;
    private readonly favoritesRepo;
    private readonly usersRepo;
    private readonly companiesRepo;
    private readonly identities;
    constructor(categoriesRepo: Repository<ClassifiedCategory>, listingsRepo: Repository<ClassifiedListing>, imagesRepo: Repository<ClassifiedListingImage>, favoritesRepo: Repository<ClassifiedFavorite>, usersRepo: Repository<User>, companiesRepo: Repository<Company>, identities: ClassifiedsIdentityService);
    categories(): Promise<ClassifiedCategory[]>;
    search(params: Record<string, unknown>): Promise<{
        items: {
            images: {
                id: string;
                url: string;
                sortOrder: number;
                isPrimary: boolean;
            }[];
            isFavorite: boolean;
            id: string;
            slug: string;
            sellerUserId: string;
            companyId: string | null;
            categorySlug: string;
            listingType: ClassifiedListingType;
            title: string;
            description: string;
            price: string | null;
            priceType: ClassifiedPriceType;
            condition: ClassifiedCondition;
            city: string;
            state: string;
            neighborhood: string | null;
            zipCode: string | null;
            latitude: string | null;
            longitude: string | null;
            deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
            status: ClassifiedListingStatus;
            isFeatured: boolean;
            sellerVerifiedSnapshot: boolean;
            viewsCount: number;
            favoritesCount: number;
            attributes: Record<string, string | number | boolean | null> | null;
            publicationChannels: ClassifiedPublicationChannel[];
            catalogConfig: ClassifiedCatalogConfig | null;
            commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
            contactPhone: string | null;
            contactWhatsapp: string | null;
            moderationReason: string | null;
            duplicateOfListingId: string | null;
            moderationReviewedAt: Date | null;
            publishedAt: Date | null;
            expiresAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        }[];
        total: number;
        page: number;
        limit: number;
        pages: number;
    }>;
    companyPageListings(companyId: string): Promise<{
        images: {
            id: string;
            url: string;
            sortOrder: number;
            isPrimary: boolean;
        }[];
        isFavorite: boolean;
        id: string;
        slug: string;
        sellerUserId: string;
        companyId: string | null;
        categorySlug: string;
        listingType: ClassifiedListingType;
        title: string;
        description: string;
        price: string | null;
        priceType: ClassifiedPriceType;
        condition: ClassifiedCondition;
        city: string;
        state: string;
        neighborhood: string | null;
        zipCode: string | null;
        latitude: string | null;
        longitude: string | null;
        deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
        status: ClassifiedListingStatus;
        isFeatured: boolean;
        sellerVerifiedSnapshot: boolean;
        viewsCount: number;
        favoritesCount: number;
        attributes: Record<string, string | number | boolean | null> | null;
        publicationChannels: ClassifiedPublicationChannel[];
        catalogConfig: ClassifiedCatalogConfig | null;
        commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
        contactPhone: string | null;
        contactWhatsapp: string | null;
        moderationReason: string | null;
        duplicateOfListingId: string | null;
        moderationReviewedAt: Date | null;
        publishedAt: Date | null;
        expiresAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    getPublicBySlug(slug: string): Promise<{
        seller: {
            id: string;
            type: string;
            name: string;
            photoURL: string | null;
            verified: boolean;
            memberSince: Date | null;
            city: string;
            state: string;
            companySlug: string | null;
        };
        related: {
            images: {
                id: string;
                url: string;
                sortOrder: number;
                isPrimary: boolean;
            }[];
            isFavorite: boolean;
            id: string;
            slug: string;
            sellerUserId: string;
            companyId: string | null;
            categorySlug: string;
            listingType: ClassifiedListingType;
            title: string;
            description: string;
            price: string | null;
            priceType: ClassifiedPriceType;
            condition: ClassifiedCondition;
            city: string;
            state: string;
            neighborhood: string | null;
            zipCode: string | null;
            latitude: string | null;
            longitude: string | null;
            deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
            status: ClassifiedListingStatus;
            isFeatured: boolean;
            sellerVerifiedSnapshot: boolean;
            viewsCount: number;
            favoritesCount: number;
            attributes: Record<string, string | number | boolean | null> | null;
            publicationChannels: ClassifiedPublicationChannel[];
            catalogConfig: ClassifiedCatalogConfig | null;
            commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
            contactPhone: string | null;
            contactWhatsapp: string | null;
            moderationReason: string | null;
            duplicateOfListingId: string | null;
            moderationReviewedAt: Date | null;
            publishedAt: Date | null;
            expiresAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        }[];
        images: {
            id: string;
            url: string;
            sortOrder: number;
            isPrimary: boolean;
        }[];
        isFavorite: boolean;
        id: string;
        slug: string;
        sellerUserId: string;
        companyId: string | null;
        categorySlug: string;
        listingType: ClassifiedListingType;
        title: string;
        description: string;
        price: string | null;
        priceType: ClassifiedPriceType;
        condition: ClassifiedCondition;
        city: string;
        state: string;
        neighborhood: string | null;
        zipCode: string | null;
        latitude: string | null;
        longitude: string | null;
        deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
        status: ClassifiedListingStatus;
        isFeatured: boolean;
        sellerVerifiedSnapshot: boolean;
        viewsCount: number;
        favoritesCount: number;
        attributes: Record<string, string | number | boolean | null> | null;
        publicationChannels: ClassifiedPublicationChannel[];
        catalogConfig: ClassifiedCatalogConfig | null;
        commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
        contactPhone: string | null;
        contactWhatsapp: string | null;
        moderationReason: string | null;
        duplicateOfListingId: string | null;
        moderationReviewedAt: Date | null;
        publishedAt: Date | null;
        expiresAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    mine(uid: string): Promise<{
        images: {
            id: string;
            url: string;
            sortOrder: number;
            isPrimary: boolean;
        }[];
        isFavorite: boolean;
        id: string;
        slug: string;
        sellerUserId: string;
        companyId: string | null;
        categorySlug: string;
        listingType: ClassifiedListingType;
        title: string;
        description: string;
        price: string | null;
        priceType: ClassifiedPriceType;
        condition: ClassifiedCondition;
        city: string;
        state: string;
        neighborhood: string | null;
        zipCode: string | null;
        latitude: string | null;
        longitude: string | null;
        deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
        status: ClassifiedListingStatus;
        isFeatured: boolean;
        sellerVerifiedSnapshot: boolean;
        viewsCount: number;
        favoritesCount: number;
        attributes: Record<string, string | number | boolean | null> | null;
        publicationChannels: ClassifiedPublicationChannel[];
        catalogConfig: ClassifiedCatalogConfig | null;
        commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
        contactPhone: string | null;
        contactWhatsapp: string | null;
        moderationReason: string | null;
        duplicateOfListingId: string | null;
        moderationReviewedAt: Date | null;
        publishedAt: Date | null;
        expiresAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    favorites(uid: string): Promise<{
        images: {
            id: string;
            url: string;
            sortOrder: number;
            isPrimary: boolean;
        }[];
        isFavorite: boolean;
        id: string;
        slug: string;
        sellerUserId: string;
        companyId: string | null;
        categorySlug: string;
        listingType: ClassifiedListingType;
        title: string;
        description: string;
        price: string | null;
        priceType: ClassifiedPriceType;
        condition: ClassifiedCondition;
        city: string;
        state: string;
        neighborhood: string | null;
        zipCode: string | null;
        latitude: string | null;
        longitude: string | null;
        deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
        status: ClassifiedListingStatus;
        isFeatured: boolean;
        sellerVerifiedSnapshot: boolean;
        viewsCount: number;
        favoritesCount: number;
        attributes: Record<string, string | number | boolean | null> | null;
        publicationChannels: ClassifiedPublicationChannel[];
        catalogConfig: ClassifiedCatalogConfig | null;
        commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
        contactPhone: string | null;
        contactWhatsapp: string | null;
        moderationReason: string | null;
        duplicateOfListingId: string | null;
        moderationReviewedAt: Date | null;
        publishedAt: Date | null;
        expiresAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    create(uid: string, body: Record<string, unknown>): Promise<{
        images: {
            id: string;
            url: string;
            sortOrder: number;
            isPrimary: boolean;
        }[];
        isFavorite: boolean;
        id: string;
        slug: string;
        sellerUserId: string;
        companyId: string | null;
        categorySlug: string;
        listingType: ClassifiedListingType;
        title: string;
        description: string;
        price: string | null;
        priceType: ClassifiedPriceType;
        condition: ClassifiedCondition;
        city: string;
        state: string;
        neighborhood: string | null;
        zipCode: string | null;
        latitude: string | null;
        longitude: string | null;
        deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
        status: ClassifiedListingStatus;
        isFeatured: boolean;
        sellerVerifiedSnapshot: boolean;
        viewsCount: number;
        favoritesCount: number;
        attributes: Record<string, string | number | boolean | null> | null;
        publicationChannels: ClassifiedPublicationChannel[];
        catalogConfig: ClassifiedCatalogConfig | null;
        commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
        contactPhone: string | null;
        contactWhatsapp: string | null;
        moderationReason: string | null;
        duplicateOfListingId: string | null;
        moderationReviewedAt: Date | null;
        publishedAt: Date | null;
        expiresAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    update(uid: string, id: string, body: Record<string, unknown>): Promise<{
        images: {
            id: string;
            url: string;
            sortOrder: number;
            isPrimary: boolean;
        }[];
        isFavorite: boolean;
        id: string;
        slug: string;
        sellerUserId: string;
        companyId: string | null;
        categorySlug: string;
        listingType: ClassifiedListingType;
        title: string;
        description: string;
        price: string | null;
        priceType: ClassifiedPriceType;
        condition: ClassifiedCondition;
        city: string;
        state: string;
        neighborhood: string | null;
        zipCode: string | null;
        latitude: string | null;
        longitude: string | null;
        deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
        status: ClassifiedListingStatus;
        isFeatured: boolean;
        sellerVerifiedSnapshot: boolean;
        viewsCount: number;
        favoritesCount: number;
        attributes: Record<string, string | number | boolean | null> | null;
        publicationChannels: ClassifiedPublicationChannel[];
        catalogConfig: ClassifiedCatalogConfig | null;
        commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
        contactPhone: string | null;
        contactWhatsapp: string | null;
        moderationReason: string | null;
        duplicateOfListingId: string | null;
        moderationReviewedAt: Date | null;
        publishedAt: Date | null;
        expiresAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    publish(uid: string, id: string): Promise<{
        images: {
            id: string;
            url: string;
            sortOrder: number;
            isPrimary: boolean;
        }[];
        isFavorite: boolean;
        id: string;
        slug: string;
        sellerUserId: string;
        companyId: string | null;
        categorySlug: string;
        listingType: ClassifiedListingType;
        title: string;
        description: string;
        price: string | null;
        priceType: ClassifiedPriceType;
        condition: ClassifiedCondition;
        city: string;
        state: string;
        neighborhood: string | null;
        zipCode: string | null;
        latitude: string | null;
        longitude: string | null;
        deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
        status: ClassifiedListingStatus;
        isFeatured: boolean;
        sellerVerifiedSnapshot: boolean;
        viewsCount: number;
        favoritesCount: number;
        attributes: Record<string, string | number | boolean | null> | null;
        publicationChannels: ClassifiedPublicationChannel[];
        catalogConfig: ClassifiedCatalogConfig | null;
        commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
        contactPhone: string | null;
        contactWhatsapp: string | null;
        moderationReason: string | null;
        duplicateOfListingId: string | null;
        moderationReviewedAt: Date | null;
        publishedAt: Date | null;
        expiresAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    setStatus(uid: string, id: string, statusRaw: unknown): Promise<{
        images: {
            id: string;
            url: string;
            sortOrder: number;
            isPrimary: boolean;
        }[];
        isFavorite: boolean;
        id: string;
        slug: string;
        sellerUserId: string;
        companyId: string | null;
        categorySlug: string;
        listingType: ClassifiedListingType;
        title: string;
        description: string;
        price: string | null;
        priceType: ClassifiedPriceType;
        condition: ClassifiedCondition;
        city: string;
        state: string;
        neighborhood: string | null;
        zipCode: string | null;
        latitude: string | null;
        longitude: string | null;
        deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
        status: ClassifiedListingStatus;
        isFeatured: boolean;
        sellerVerifiedSnapshot: boolean;
        viewsCount: number;
        favoritesCount: number;
        attributes: Record<string, string | number | boolean | null> | null;
        publicationChannels: ClassifiedPublicationChannel[];
        catalogConfig: ClassifiedCatalogConfig | null;
        commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
        contactPhone: string | null;
        contactWhatsapp: string | null;
        moderationReason: string | null;
        duplicateOfListingId: string | null;
        moderationReviewedAt: Date | null;
        publishedAt: Date | null;
        expiresAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    toggleFavorite(uid: string, listingId: string): Promise<{
        favorited: boolean;
        favoritesCount: number;
    }>;
    private getMineById;
    private hydrateListings;
    private replaceImages;
    private assertOwner;
    private assertCategory;
    private uniqueSlug;
}
