import { DataSource } from 'typeorm';
export declare class ClassifiedsAuctionPublicService {
    private readonly dataSource;
    constructor(dataSource: DataSource);
    list(): Promise<any>;
    detail(auctionId: string): Promise<{
        bids: any;
        settlement: {
            mode: string;
            onlinePaymentEnabled: boolean;
            protectedPayment: boolean;
            fulfillmentModes: string[];
            deliveryFeeCents: number;
            deliveryNote: any;
            pickupAddress: any;
            paymentStatus: any;
            paymentMethods: string[];
            cardMaxInstallments: number;
            auctionFeePayer: "BUYER" | "SELLER";
            auctionFeeRateBps: number | null;
            auctionFeePercentage: number | null;
            auctionFeeCents: number | null;
            buyerAuctionFeeCents: number | null;
            feeDisclosure: string;
            message: string;
        };
        id: any;
        listingId: any;
        companyId: any;
        status: any;
        title: any;
        slug: any;
        description: any;
        listingPrice: number | null;
        city: any;
        state: any;
        neighborhood: any;
        condition: any;
        sellerVerifiedSnapshot: boolean;
        companyName: any;
        companyLogo: any;
        image: any;
        startPrice: number;
        minIncrement: number;
        currentBid: number | null;
        bidCount: number;
        startsAt: any;
        endsAt: any;
        closedAt: any;
        finalAmount: number | null;
        nextMinimum: number;
        scheduled: boolean;
        live: boolean;
        onlinePaymentEnabled: boolean;
        auctionFeePayer: "BUYER" | "SELLER";
        auctionFeePercentage: number | null;
        paymentMethods: string[];
        pickupAddress: any;
    }>;
    forListings(listingIds: string[]): Promise<any>;
    private present;
    private fee;
    private feePayer;
    private feeDisclosure;
    private pickupAddress;
    private paymentMethods;
    private modes;
    private maskName;
}
