import { ChatGateway } from '../chat/chat.gateway';
import { IdentityComplianceService } from '../compliance/identity-compliance.service';
import { ClassifiedsAuctionService } from './classifieds-auction.service';
import { ClassifiedsCategoryTaxonomyService } from './classifieds-category-taxonomy.service';
import { ClassifiedsChatService } from './classifieds-chat.service';
import { ClassifiedsCommerceService } from './classifieds-commerce.service';
import { ClassifiedsEntitlementsService } from './classifieds-entitlements.service';
import { ClassifiedsIdentityService } from './classifieds-identity.service';
import { ClassifiedsLifecycleService } from './classifieds-lifecycle.service';
import { ClassifiedsOfferChatService } from './classifieds-offer-chat.service';
import { ClassifiedsService } from './classifieds.service';
export declare class ClassifiedsPrivateController {
    private readonly classifieds;
    private readonly taxonomy;
    private readonly identities;
    private readonly lifecycle;
    private readonly chats;
    private readonly commerce;
    private readonly entitlements;
    private readonly auctions;
    private readonly offerChat;
    private readonly chatGateway;
    private readonly compliance;
    constructor(classifieds: ClassifiedsService, taxonomy: ClassifiedsCategoryTaxonomyService, identities: ClassifiedsIdentityService, lifecycle: ClassifiedsLifecycleService, chats: ClassifiedsChatService, commerce: ClassifiedsCommerceService, entitlements: ClassifiedsEntitlementsService, auctions: ClassifiedsAuctionService, offerChat: ClassifiedsOfferChatService, chatGateway: ChatGateway, compliance: IdentityComplianceService);
    context(req: any): Promise<{
        termsVersion: string;
        needsIdentitySelection: boolean;
        activeIdentity: import("./entities/classified-user-preference.entity").ClassifiedIdentityType | null;
        personal: {
            available: boolean;
            termsAccepted: boolean;
            termsAcceptedAt: Date | null;
            name: string;
            photoURL: string | null;
        };
        company: {
            id: string;
            name: string;
            logoURL: string;
            available: boolean;
            verified: boolean;
            termsAccepted: boolean;
            requiresOnboarding: boolean;
            publishingSetupRequired: boolean;
            canSellProducts: boolean;
            canOfferServices: boolean;
            businessSegments: string[];
            defaultPublicationChannels: import("./entities/company-classified-profile.entity").ClassifiedPublicationChannel[];
            pageSectionLabel: string | null;
        } | null;
    }>;
    limits(req: any): Promise<{
        photoLimit: number;
        plan: string;
        paid: boolean;
        auctionCreation: boolean;
    }>;
    selectIdentity(req: any, body: any): Promise<{
        termsVersion: string;
        needsIdentitySelection: boolean;
        activeIdentity: import("./entities/classified-user-preference.entity").ClassifiedIdentityType | null;
        personal: {
            available: boolean;
            termsAccepted: boolean;
            termsAcceptedAt: Date | null;
            name: string;
            photoURL: string | null;
        };
        company: {
            id: string;
            name: string;
            logoURL: string;
            available: boolean;
            verified: boolean;
            termsAccepted: boolean;
            requiresOnboarding: boolean;
            publishingSetupRequired: boolean;
            canSellProducts: boolean;
            canOfferServices: boolean;
            businessSegments: string[];
            defaultPublicationChannels: import("./entities/company-classified-profile.entity").ClassifiedPublicationChannel[];
            pageSectionLabel: string | null;
        } | null;
    }>;
    acceptPersonalTerms(req: any, body: any): Promise<{
        termsVersion: string;
        needsIdentitySelection: boolean;
        activeIdentity: import("./entities/classified-user-preference.entity").ClassifiedIdentityType | null;
        personal: {
            available: boolean;
            termsAccepted: boolean;
            termsAcceptedAt: Date | null;
            name: string;
            photoURL: string | null;
        };
        company: {
            id: string;
            name: string;
            logoURL: string;
            available: boolean;
            verified: boolean;
            termsAccepted: boolean;
            requiresOnboarding: boolean;
            publishingSetupRequired: boolean;
            canSellProducts: boolean;
            canOfferServices: boolean;
            businessSegments: string[];
            defaultPublicationChannels: import("./entities/company-classified-profile.entity").ClassifiedPublicationChannel[];
            pageSectionLabel: string | null;
        } | null;
    }>;
    configureCompany(req: any, body: Record<string, unknown>): Promise<{
        termsVersion: string;
        needsIdentitySelection: boolean;
        activeIdentity: import("./entities/classified-user-preference.entity").ClassifiedIdentityType | null;
        personal: {
            available: boolean;
            termsAccepted: boolean;
            termsAcceptedAt: Date | null;
            name: string;
            photoURL: string | null;
        };
        company: {
            id: string;
            name: string;
            logoURL: string;
            available: boolean;
            verified: boolean;
            termsAccepted: boolean;
            requiresOnboarding: boolean;
            publishingSetupRequired: boolean;
            canSellProducts: boolean;
            canOfferServices: boolean;
            businessSegments: string[];
            defaultPublicationChannels: import("./entities/company-classified-profile.entity").ClassifiedPublicationChannel[];
            pageSectionLabel: string | null;
        } | null;
    }>;
    updateCompany(req: any, body: Record<string, unknown>): Promise<{
        termsVersion: string;
        needsIdentitySelection: boolean;
        activeIdentity: import("./entities/classified-user-preference.entity").ClassifiedIdentityType | null;
        personal: {
            available: boolean;
            termsAccepted: boolean;
            termsAcceptedAt: Date | null;
            name: string;
            photoURL: string | null;
        };
        company: {
            id: string;
            name: string;
            logoURL: string;
            available: boolean;
            verified: boolean;
            termsAccepted: boolean;
            requiresOnboarding: boolean;
            publishingSetupRequired: boolean;
            canSellProducts: boolean;
            canOfferServices: boolean;
            businessSegments: string[];
            defaultPublicationChannels: import("./entities/company-classified-profile.entity").ClassifiedPublicationChannel[];
            pageSectionLabel: string | null;
        } | null;
    }>;
    mine(req: any): Promise<{
        images: {
            id: string;
            url: string;
            sortOrder: number;
            isPrimary: boolean;
        }[];
        isFavorite: boolean;
        id: string;
        slug: string;
        sellerUserId: string;
        companyId: string | null;
        categorySlug: string;
        listingType: import("./entities/classified-listing.entity").ClassifiedListingType;
        title: string;
        description: string;
        price: string | null;
        priceType: import("./entities/classified-listing.entity").ClassifiedPriceType;
        condition: import("./entities/classified-listing.entity").ClassifiedCondition;
        city: string;
        state: string;
        neighborhood: string | null;
        zipCode: string | null;
        latitude: string | null;
        longitude: string | null;
        deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
        status: import("./entities/classified-listing.entity").ClassifiedListingStatus;
        isFeatured: boolean;
        sellerVerifiedSnapshot: boolean;
        viewsCount: number;
        favoritesCount: number;
        attributes: Record<string, string | number | boolean | null> | null;
        publicationChannels: import("./entities/classified-listing.entity").ClassifiedPublicationChannel[];
        catalogConfig: import("./entities/classified-listing.entity").ClassifiedCatalogConfig | null;
        commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
        contactPhone: string | null;
        contactWhatsapp: string | null;
        moderationReason: string | null;
        duplicateOfListingId: string | null;
        moderationReviewedAt: Date | null;
        publishedAt: Date | null;
        expiresAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    favorites(req: any): Promise<{
        images: {
            id: string;
            url: string;
            sortOrder: number;
            isPrimary: boolean;
        }[];
        isFavorite: boolean;
        id: string;
        slug: string;
        sellerUserId: string;
        companyId: string | null;
        categorySlug: string;
        listingType: import("./entities/classified-listing.entity").ClassifiedListingType;
        title: string;
        description: string;
        price: string | null;
        priceType: import("./entities/classified-listing.entity").ClassifiedPriceType;
        condition: import("./entities/classified-listing.entity").ClassifiedCondition;
        city: string;
        state: string;
        neighborhood: string | null;
        zipCode: string | null;
        latitude: string | null;
        longitude: string | null;
        deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
        status: import("./entities/classified-listing.entity").ClassifiedListingStatus;
        isFeatured: boolean;
        sellerVerifiedSnapshot: boolean;
        viewsCount: number;
        favoritesCount: number;
        attributes: Record<string, string | number | boolean | null> | null;
        publicationChannels: import("./entities/classified-listing.entity").ClassifiedPublicationChannel[];
        catalogConfig: import("./entities/classified-listing.entity").ClassifiedCatalogConfig | null;
        commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
        contactPhone: string | null;
        contactWhatsapp: string | null;
        moderationReason: string | null;
        duplicateOfListingId: string | null;
        moderationReviewedAt: Date | null;
        publishedAt: Date | null;
        expiresAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }[]>;
    analytics(req: any): Promise<{
        totals: any;
        listings: any;
        daily: any;
    }>;
    offers(req: any): Promise<any>;
    createOffer(req: any, listingId: string, body: any): Promise<any>;
    respondOffer(req: any, offerId: string, body: any): Promise<any>;
    withdrawOffer(req: any, offerId: string): Promise<any>;
    auctionsList(req: any): Promise<any>;
    auctionDetail(req: any, auctionId: string): Promise<any>;
    createAuction(req: any, body: Record<string, unknown>): Promise<any>;
    bidAuction(req: any, auctionId: string, body: any): Promise<any>;
    cancelAuction(req: any, auctionId: string): Promise<any>;
    create(req: any, body: Record<string, unknown>): Promise<{
        images: {
            id: string;
            url: string;
            sortOrder: number;
            isPrimary: boolean;
        }[];
        isFavorite: boolean;
        id: string;
        slug: string;
        sellerUserId: string;
        companyId: string | null;
        categorySlug: string;
        listingType: import("./entities/classified-listing.entity").ClassifiedListingType;
        title: string;
        description: string;
        price: string | null;
        priceType: import("./entities/classified-listing.entity").ClassifiedPriceType;
        condition: import("./entities/classified-listing.entity").ClassifiedCondition;
        city: string;
        state: string;
        neighborhood: string | null;
        zipCode: string | null;
        latitude: string | null;
        longitude: string | null;
        deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
        status: import("./entities/classified-listing.entity").ClassifiedListingStatus;
        isFeatured: boolean;
        sellerVerifiedSnapshot: boolean;
        viewsCount: number;
        favoritesCount: number;
        attributes: Record<string, string | number | boolean | null> | null;
        publicationChannels: import("./entities/classified-listing.entity").ClassifiedPublicationChannel[];
        catalogConfig: import("./entities/classified-listing.entity").ClassifiedCatalogConfig | null;
        commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
        contactPhone: string | null;
        contactWhatsapp: string | null;
        moderationReason: string | null;
        duplicateOfListingId: string | null;
        moderationReviewedAt: Date | null;
        publishedAt: Date | null;
        expiresAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    update(req: any, id: string, body: Record<string, unknown>): Promise<{
        images: {
            id: string;
            url: string;
            sortOrder: number;
            isPrimary: boolean;
        }[];
        isFavorite: boolean;
        id: string;
        slug: string;
        sellerUserId: string;
        companyId: string | null;
        categorySlug: string;
        listingType: import("./entities/classified-listing.entity").ClassifiedListingType;
        title: string;
        description: string;
        price: string | null;
        priceType: import("./entities/classified-listing.entity").ClassifiedPriceType;
        condition: import("./entities/classified-listing.entity").ClassifiedCondition;
        city: string;
        state: string;
        neighborhood: string | null;
        zipCode: string | null;
        latitude: string | null;
        longitude: string | null;
        deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
        status: import("./entities/classified-listing.entity").ClassifiedListingStatus;
        isFeatured: boolean;
        sellerVerifiedSnapshot: boolean;
        viewsCount: number;
        favoritesCount: number;
        attributes: Record<string, string | number | boolean | null> | null;
        publicationChannels: import("./entities/classified-listing.entity").ClassifiedPublicationChannel[];
        catalogConfig: import("./entities/classified-listing.entity").ClassifiedCatalogConfig | null;
        commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
        contactPhone: string | null;
        contactWhatsapp: string | null;
        moderationReason: string | null;
        duplicateOfListingId: string | null;
        moderationReviewedAt: Date | null;
        publishedAt: Date | null;
        expiresAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    publish(req: any, id: string): Promise<{
        images: {
            id: string;
            url: string;
            sortOrder: number;
            isPrimary: boolean;
        }[];
        isFavorite: boolean;
        id: string;
        slug: string;
        sellerUserId: string;
        companyId: string | null;
        categorySlug: string;
        listingType: import("./entities/classified-listing.entity").ClassifiedListingType;
        title: string;
        description: string;
        price: string | null;
        priceType: import("./entities/classified-listing.entity").ClassifiedPriceType;
        condition: import("./entities/classified-listing.entity").ClassifiedCondition;
        city: string;
        state: string;
        neighborhood: string | null;
        zipCode: string | null;
        latitude: string | null;
        longitude: string | null;
        deliveryModes: import("./entities/classified-listing.entity").ClassifiedFulfillmentMode[];
        status: import("./entities/classified-listing.entity").ClassifiedListingStatus;
        isFeatured: boolean;
        sellerVerifiedSnapshot: boolean;
        viewsCount: number;
        favoritesCount: number;
        attributes: Record<string, string | number | boolean | null> | null;
        publicationChannels: import("./entities/classified-listing.entity").ClassifiedPublicationChannel[];
        catalogConfig: import("./entities/classified-listing.entity").ClassifiedCatalogConfig | null;
        commerceConfig: import("./entities/classified-listing.entity").ClassifiedCommerceConfig | null;
        contactPhone: string | null;
        contactWhatsapp: string | null;
        moderationReason: string | null;
        duplicateOfListingId: string | null;
        moderationReviewedAt: Date | null;
        publishedAt: Date | null;
        expiresAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    status(req: any, id: string, body: {
        status?: unknown;
    }): Promise<any>;
    favorite(req: any, id: string): Promise<{
        favorited: boolean;
        favoritesCount: number;
    }>;
    conversations(req: any): Promise<any[]>;
    startConversation(req: any, listingId: string): Promise<{
        role: "BUYER" | "SELLER";
        unreadCount: number;
        listing: {
            id: string;
            slug: string;
            title: string;
            price: string | null;
            priceType: import("./entities/classified-listing.entity").ClassifiedPriceType;
            status: import("./entities/classified-listing.entity").ClassifiedListingStatus;
            image: string | null;
        } | null;
        buyer: {
            id: string;
            type: string;
            name: string;
            photoURL: string | null;
            verified: boolean;
        };
        seller: {
            id: string;
            type: string;
            name: string;
            photoURL: string | null;
            verified: boolean;
        };
        lastMessage: {
            id: string;
            senderId: string;
            senderRole: import("./entities/classified-conversation-message.entity").ClassifiedConversationSide;
            body: string;
            createdAt: Date;
        } | null;
        id: string;
        listingId: string;
        buyerUserId: string;
        buyerCompanyId: string | null;
        sellerUserId: string;
        sellerCompanyId: string | null;
        buyerLastReadAt: Date | null;
        sellerLastReadAt: Date | null;
        lastMessageAt: Date | null;
        buyerDeletedAt: Date | null;
        sellerDeletedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
    }>;
    renameConversation(req: any, conversationId: string, body: any): Promise<any>;
    archiveConversation(req: any, conversationId: string): Promise<{
        archived: boolean;
    }>;
    labels(req: any): Promise<any>;
    createLabel(req: any, body: any): Promise<any>;
    setConversationLabels(req: any, conversationId: string, body: any): Promise<any>;
    messages(req: any, conversationId: string): Promise<import("./entities/classified-conversation-message.entity").ClassifiedConversationMessage[]>;
    sendMessage(req: any, conversationId: string, body: any): Promise<import("./entities/classified-conversation-message.entity").ClassifiedConversationMessage>;
    readConversation(req: any, conversationId: string): Promise<{
        ok: boolean;
    }>;
}
