import { DataSource } from 'typeorm';
import { ChatGateway } from '../chat/chat.gateway';
import { PaymentsService } from './payments.service';
import { PaymentProviderConfigService } from './payment-provider-config.service';
export declare class PaymentCheckoutStatusService {
    private readonly dataSource;
    private readonly payments;
    private readonly providerConfig;
    private readonly realtime;
    private readonly watches;
    constructor(dataSource: DataSource, payments: PaymentsService, providerConfig: PaymentProviderConfigService, realtime: ChatGateway);
    getForUser(userId: string, paymentId: string): Promise<{
        id: any;
        paymentId: any;
        productCode: any;
        productName: any;
        productDescription: any;
        purchaseMode: string;
        billingType: string;
        amountCents: number;
        originalAmountCents: number;
        discountCents: number;
        status: any;
        provider: any;
        providerPaymentId: any;
        pixCopyPaste: any;
        qrCodeBase64: any;
        expiresAt: any;
        paidAt: any;
        checkoutReady: boolean;
        authorizationUrl: any;
        ticketUrl: any;
        recurring: boolean;
        subscriptionStatus: string | null;
        authorizationComplete: boolean;
        providerStatus: any;
        providerStatusDetail: any;
        completed: boolean;
        awaitingPayment: boolean;
        metadata: {
            purchaseMode: string;
            paymentType: string;
            checkoutApi: any;
            recurringApi: any;
            efiAutomaticPix: boolean;
        };
    }>;
    watchForUser(userId: string, paymentId: string): void;
    private runWatch;
    private find;
    private metadata;
    private isRecurring;
    private reconcileMercadoPago;
    private request;
    private cents;
    private reconcileOrder;
    private reconcileSubscription;
    private present;
}
