import { DataSource } from 'typeorm';
import { PaymentProviderVaultService } from './payment-provider-vault.service';
export type PaymentProviderCode = 'EFI' | 'MERCADO_PAGO';
export type PaymentType = 'PIX' | 'PIX_AUTOMATICO';
export interface EfiProviderConfig extends Record<string, unknown> {
    clientId?: string;
    clientSecret?: string;
    pixKey?: string;
    sandbox?: boolean;
    certificateBase64?: string;
    certificateFileName?: string;
    certificatePassphrase?: string;
    pixAutomaticEnabled?: boolean;
    receiverAgency?: string;
    receiverAccount?: string;
    receiverAccountType?: 'CORRENTE' | 'POUPANCA' | 'PAGAMENTO';
    publicApiBaseUrl?: string;
    webhookSecret?: string;
    skipMtlsChecking?: boolean;
    expirationSeconds?: number;
}
export interface MercadoPagoProviderConfig extends Record<string, unknown> {
    accessToken?: string;
    publicKey?: string;
    webhookSecret?: string;
    publicApiBaseUrl?: string;
    marketplaceClientId?: string;
    marketplaceClientSecret?: string;
    marketplaceRedirectUri?: string;
}
export declare class PaymentProviderConfigService {
    private readonly dataSource;
    private readonly vault;
    constructor(dataSource: DataSource, vault: PaymentProviderVaultService);
    normalizeCode(value: string): PaymentProviderCode;
    normalizePaymentType(value: string): PaymentType;
    private text;
    private bool;
    private publicApiBaseUrl;
    private certificateFromInput;
    private sanitizeEfi;
    private sanitizeMercadoPago;
    getRow(codeInput: string): Promise<any>;
    getSecretConfig<T extends Record<string, unknown>>(codeInput: string): Promise<T>;
    private safeDetails;
    private supportsType;
    private activeTypesFor;
    private presentRow;
    listSafe(): Promise<any[]>;
    getSafe(code: string): Promise<{
        code: PaymentProviderCode;
        name: any;
        description: any;
        active: boolean;
        activeFor: any;
        configured: boolean;
        configVersion: number;
        lastHealthCheckAt: any;
        lastHealthCheckOk: any;
        lastHealthCheckMessage: any;
        lastHealthCheckDetails: any;
        activatedAt: any;
        updatedAt: any;
        config: {
            environment: string;
            clientIdConfigured: boolean;
            clientSecretConfigured: boolean;
            pixKeyConfigured: boolean;
            certificateConfigured: boolean;
            certificateFileName: any;
            certificateHasPassphrase: boolean;
            pixAutomaticEnabled: boolean;
            receiverAccountConfigured: boolean;
            publicApiBaseUrl: any;
            skipMtlsChecking: boolean;
            capabilities: string[];
            accessTokenConfigured?: undefined;
            publicKeyConfigured?: undefined;
            webhookSecretConfigured?: undefined;
            marketplaceClientIdConfigured?: undefined;
            marketplaceClientId?: undefined;
            marketplaceClientSecretConfigured?: undefined;
            marketplaceRedirectUri?: undefined;
            checkoutApi?: undefined;
            recurringApi?: undefined;
            sdk?: undefined;
        } | {
            environment: string;
            accessTokenConfigured: boolean;
            publicKeyConfigured: boolean;
            webhookSecretConfigured: boolean;
            marketplaceClientIdConfigured: boolean;
            marketplaceClientId: any;
            marketplaceClientSecretConfigured: boolean;
            marketplaceRedirectUri: any;
            publicApiBaseUrl: any;
            capabilities: string[];
            checkoutApi: string;
            recurringApi: string;
            sdk: string;
            clientIdConfigured?: undefined;
            clientSecretConfigured?: undefined;
            pixKeyConfigured?: undefined;
            certificateConfigured?: undefined;
            certificateFileName?: undefined;
            certificateHasPassphrase?: undefined;
            pixAutomaticEnabled?: undefined;
            receiverAccountConfigured?: undefined;
            skipMtlsChecking?: undefined;
        };
    }>;
    listRoutesSafe(): Promise<any>;
    publicRoutes(): Promise<any>;
    saveConfig(codeInput: string, input: Record<string, unknown>, adminUserId: string): Promise<{
        code: PaymentProviderCode;
        name: any;
        description: any;
        active: boolean;
        activeFor: any;
        configured: boolean;
        configVersion: number;
        lastHealthCheckAt: any;
        lastHealthCheckOk: any;
        lastHealthCheckMessage: any;
        lastHealthCheckDetails: any;
        activatedAt: any;
        updatedAt: any;
        config: {
            environment: string;
            clientIdConfigured: boolean;
            clientSecretConfigured: boolean;
            pixKeyConfigured: boolean;
            certificateConfigured: boolean;
            certificateFileName: any;
            certificateHasPassphrase: boolean;
            pixAutomaticEnabled: boolean;
            receiverAccountConfigured: boolean;
            publicApiBaseUrl: any;
            skipMtlsChecking: boolean;
            capabilities: string[];
            accessTokenConfigured?: undefined;
            publicKeyConfigured?: undefined;
            webhookSecretConfigured?: undefined;
            marketplaceClientIdConfigured?: undefined;
            marketplaceClientId?: undefined;
            marketplaceClientSecretConfigured?: undefined;
            marketplaceRedirectUri?: undefined;
            checkoutApi?: undefined;
            recurringApi?: undefined;
            sdk?: undefined;
        } | {
            environment: string;
            accessTokenConfigured: boolean;
            publicKeyConfigured: boolean;
            webhookSecretConfigured: boolean;
            marketplaceClientIdConfigured: boolean;
            marketplaceClientId: any;
            marketplaceClientSecretConfigured: boolean;
            marketplaceRedirectUri: any;
            publicApiBaseUrl: any;
            capabilities: string[];
            checkoutApi: string;
            recurringApi: string;
            sdk: string;
            clientIdConfigured?: undefined;
            clientSecretConfigured?: undefined;
            pixKeyConfigured?: undefined;
            certificateConfigured?: undefined;
            certificateFileName?: undefined;
            certificateHasPassphrase?: undefined;
            pixAutomaticEnabled?: undefined;
            receiverAccountConfigured?: undefined;
            skipMtlsChecking?: undefined;
        };
    }>;
    recordHealth(codeInput: string, operational: boolean, message: string, details?: Record<string, unknown>, adminUserId?: string): Promise<{
        code: PaymentProviderCode;
        name: any;
        description: any;
        active: boolean;
        activeFor: any;
        configured: boolean;
        configVersion: number;
        lastHealthCheckAt: any;
        lastHealthCheckOk: any;
        lastHealthCheckMessage: any;
        lastHealthCheckDetails: any;
        activatedAt: any;
        updatedAt: any;
        config: {
            environment: string;
            clientIdConfigured: boolean;
            clientSecretConfigured: boolean;
            pixKeyConfigured: boolean;
            certificateConfigured: boolean;
            certificateFileName: any;
            certificateHasPassphrase: boolean;
            pixAutomaticEnabled: boolean;
            receiverAccountConfigured: boolean;
            publicApiBaseUrl: any;
            skipMtlsChecking: boolean;
            capabilities: string[];
            accessTokenConfigured?: undefined;
            publicKeyConfigured?: undefined;
            webhookSecretConfigured?: undefined;
            marketplaceClientIdConfigured?: undefined;
            marketplaceClientId?: undefined;
            marketplaceClientSecretConfigured?: undefined;
            marketplaceRedirectUri?: undefined;
            checkoutApi?: undefined;
            recurringApi?: undefined;
            sdk?: undefined;
        } | {
            environment: string;
            accessTokenConfigured: boolean;
            publicKeyConfigured: boolean;
            webhookSecretConfigured: boolean;
            marketplaceClientIdConfigured: boolean;
            marketplaceClientId: any;
            marketplaceClientSecretConfigured: boolean;
            marketplaceRedirectUri: any;
            publicApiBaseUrl: any;
            capabilities: string[];
            checkoutApi: string;
            recurringApi: string;
            sdk: string;
            clientIdConfigured?: undefined;
            clientSecretConfigured?: undefined;
            pixKeyConfigured?: undefined;
            certificateConfigured?: undefined;
            certificateFileName?: undefined;
            certificateHasPassphrase?: undefined;
            pixAutomaticEnabled?: undefined;
            receiverAccountConfigured?: undefined;
            skipMtlsChecking?: undefined;
        };
    }>;
    activateRoute(codeInput: string, paymentTypeInput: string, adminUserId: string): Promise<any>;
    deactivateRoute(paymentTypeInput: string, adminUserId: string): Promise<any>;
    activeProvider(paymentTypeInput: string): Promise<PaymentProviderCode | null>;
    vaultStatus(): {
        encryptedAtRest: boolean;
        algorithm: string;
        keyStorage: string;
        keyPathHint: string;
    };
}
