import { DataSource } from 'typeorm';
import { EfiPixService, type EfiPayerInput } from './efi-pix.service';
import { MercadoPagoService, type MercadoPagoPayerInput } from './mercado-pago.service';
import { PaymentProviderConfigService, type PaymentProviderCode } from './payment-provider-config.service';
export interface PaymentCheckoutPayer extends EfiPayerInput, MercadoPagoPayerInput {
    documentType?: 'CPF' | 'CNPJ';
}
export declare class PaymentProviderManagerService {
    private readonly dataSource;
    private readonly providerConfig;
    private readonly efi;
    private readonly mercadoPago;
    constructor(dataSource: DataSource, providerConfig: PaymentProviderConfigService, efi: EfiPixService, mercadoPago: MercadoPagoService);
    private isNativeAutomaticPixProvider;
    private efiAutomaticEnabled;
    list(): Promise<any[]>;
    routes(): Promise<any>;
    publicRoutes(): Promise<any>;
    get(code: string): Promise<{
        code: PaymentProviderCode;
        name: any;
        description: any;
        active: boolean;
        activeFor: any;
        configured: boolean;
        configVersion: number;
        lastHealthCheckAt: any;
        lastHealthCheckOk: any;
        lastHealthCheckMessage: any;
        lastHealthCheckDetails: any;
        activatedAt: any;
        updatedAt: any;
        config: {
            environment: string;
            clientIdConfigured: boolean;
            clientSecretConfigured: boolean;
            pixKeyConfigured: boolean;
            certificateConfigured: boolean;
            certificateFileName: any;
            certificateHasPassphrase: boolean;
            pixAutomaticEnabled: boolean;
            receiverAccountConfigured: boolean;
            publicApiBaseUrl: any;
            skipMtlsChecking: boolean;
            capabilities: string[];
            accessTokenConfigured?: undefined;
            publicKeyConfigured?: undefined;
            webhookSecretConfigured?: undefined;
            marketplaceClientIdConfigured?: undefined;
            marketplaceClientId?: undefined;
            marketplaceClientSecretConfigured?: undefined;
            marketplaceRedirectUri?: undefined;
            checkoutApi?: undefined;
            recurringApi?: undefined;
            sdk?: undefined;
        } | {
            environment: string;
            accessTokenConfigured: boolean;
            publicKeyConfigured: boolean;
            webhookSecretConfigured: boolean;
            marketplaceClientIdConfigured: boolean;
            marketplaceClientId: any;
            marketplaceClientSecretConfigured: boolean;
            marketplaceRedirectUri: any;
            publicApiBaseUrl: any;
            capabilities: string[];
            checkoutApi: string;
            recurringApi: string;
            sdk: string;
            clientIdConfigured?: undefined;
            clientSecretConfigured?: undefined;
            pixKeyConfigured?: undefined;
            certificateConfigured?: undefined;
            certificateFileName?: undefined;
            certificateHasPassphrase?: undefined;
            pixAutomaticEnabled?: undefined;
            receiverAccountConfigured?: undefined;
            skipMtlsChecking?: undefined;
        };
    }>;
    save(code: string, body: Record<string, unknown>, adminUserId: string): Promise<{
        code: PaymentProviderCode;
        name: any;
        description: any;
        active: boolean;
        activeFor: any;
        configured: boolean;
        configVersion: number;
        lastHealthCheckAt: any;
        lastHealthCheckOk: any;
        lastHealthCheckMessage: any;
        lastHealthCheckDetails: any;
        activatedAt: any;
        updatedAt: any;
        config: {
            environment: string;
            clientIdConfigured: boolean;
            clientSecretConfigured: boolean;
            pixKeyConfigured: boolean;
            certificateConfigured: boolean;
            certificateFileName: any;
            certificateHasPassphrase: boolean;
            pixAutomaticEnabled: boolean;
            receiverAccountConfigured: boolean;
            publicApiBaseUrl: any;
            skipMtlsChecking: boolean;
            capabilities: string[];
            accessTokenConfigured?: undefined;
            publicKeyConfigured?: undefined;
            webhookSecretConfigured?: undefined;
            marketplaceClientIdConfigured?: undefined;
            marketplaceClientId?: undefined;
            marketplaceClientSecretConfigured?: undefined;
            marketplaceRedirectUri?: undefined;
            checkoutApi?: undefined;
            recurringApi?: undefined;
            sdk?: undefined;
        } | {
            environment: string;
            accessTokenConfigured: boolean;
            publicKeyConfigured: boolean;
            webhookSecretConfigured: boolean;
            marketplaceClientIdConfigured: boolean;
            marketplaceClientId: any;
            marketplaceClientSecretConfigured: boolean;
            marketplaceRedirectUri: any;
            publicApiBaseUrl: any;
            capabilities: string[];
            checkoutApi: string;
            recurringApi: string;
            sdk: string;
            clientIdConfigured?: undefined;
            clientSecretConfigured?: undefined;
            pixKeyConfigured?: undefined;
            certificateConfigured?: undefined;
            certificateFileName?: undefined;
            certificateHasPassphrase?: undefined;
            pixAutomaticEnabled?: undefined;
            receiverAccountConfigured?: undefined;
            skipMtlsChecking?: undefined;
        };
    }>;
    vaultStatus(): {
        encryptedAtRest: boolean;
        algorithm: string;
        keyStorage: string;
        keyPathHint: string;
    };
    private adapter;
    test(codeInput: string, adminUserId?: string): Promise<{
        code: PaymentProviderCode;
        name: any;
        description: any;
        active: boolean;
        activeFor: any;
        configured: boolean;
        configVersion: number;
        lastHealthCheckAt: any;
        lastHealthCheckOk: any;
        lastHealthCheckMessage: any;
        lastHealthCheckDetails: any;
        activatedAt: any;
        updatedAt: any;
        config: {
            environment: string;
            clientIdConfigured: boolean;
            clientSecretConfigured: boolean;
            pixKeyConfigured: boolean;
            certificateConfigured: boolean;
            certificateFileName: any;
            certificateHasPassphrase: boolean;
            pixAutomaticEnabled: boolean;
            receiverAccountConfigured: boolean;
            publicApiBaseUrl: any;
            skipMtlsChecking: boolean;
            capabilities: string[];
            accessTokenConfigured?: undefined;
            publicKeyConfigured?: undefined;
            webhookSecretConfigured?: undefined;
            marketplaceClientIdConfigured?: undefined;
            marketplaceClientId?: undefined;
            marketplaceClientSecretConfigured?: undefined;
            marketplaceRedirectUri?: undefined;
            checkoutApi?: undefined;
            recurringApi?: undefined;
            sdk?: undefined;
        } | {
            environment: string;
            accessTokenConfigured: boolean;
            publicKeyConfigured: boolean;
            webhookSecretConfigured: boolean;
            marketplaceClientIdConfigured: boolean;
            marketplaceClientId: any;
            marketplaceClientSecretConfigured: boolean;
            marketplaceRedirectUri: any;
            publicApiBaseUrl: any;
            capabilities: string[];
            checkoutApi: string;
            recurringApi: string;
            sdk: string;
            clientIdConfigured?: undefined;
            clientSecretConfigured?: undefined;
            pixKeyConfigured?: undefined;
            certificateConfigured?: undefined;
            certificateFileName?: undefined;
            certificateHasPassphrase?: undefined;
            pixAutomaticEnabled?: undefined;
            receiverAccountConfigured?: undefined;
            skipMtlsChecking?: undefined;
        };
    }>;
    activate(codeInput: string, paymentTypeInput: string, adminUserId: string): Promise<{
        provider: {
            code: PaymentProviderCode;
            name: any;
            description: any;
            active: boolean;
            activeFor: any;
            configured: boolean;
            configVersion: number;
            lastHealthCheckAt: any;
            lastHealthCheckOk: any;
            lastHealthCheckMessage: any;
            lastHealthCheckDetails: any;
            activatedAt: any;
            updatedAt: any;
            config: {
                environment: string;
                clientIdConfigured: boolean;
                clientSecretConfigured: boolean;
                pixKeyConfigured: boolean;
                certificateConfigured: boolean;
                certificateFileName: any;
                certificateHasPassphrase: boolean;
                pixAutomaticEnabled: boolean;
                receiverAccountConfigured: boolean;
                publicApiBaseUrl: any;
                skipMtlsChecking: boolean;
                capabilities: string[];
                accessTokenConfigured?: undefined;
                publicKeyConfigured?: undefined;
                webhookSecretConfigured?: undefined;
                marketplaceClientIdConfigured?: undefined;
                marketplaceClientId?: undefined;
                marketplaceClientSecretConfigured?: undefined;
                marketplaceRedirectUri?: undefined;
                checkoutApi?: undefined;
                recurringApi?: undefined;
                sdk?: undefined;
            } | {
                environment: string;
                accessTokenConfigured: boolean;
                publicKeyConfigured: boolean;
                webhookSecretConfigured: boolean;
                marketplaceClientIdConfigured: boolean;
                marketplaceClientId: any;
                marketplaceClientSecretConfigured: boolean;
                marketplaceRedirectUri: any;
                publicApiBaseUrl: any;
                capabilities: string[];
                checkoutApi: string;
                recurringApi: string;
                sdk: string;
                clientIdConfigured?: undefined;
                clientSecretConfigured?: undefined;
                pixKeyConfigured?: undefined;
                certificateConfigured?: undefined;
                certificateFileName?: undefined;
                certificateHasPassphrase?: undefined;
                pixAutomaticEnabled?: undefined;
                receiverAccountConfigured?: undefined;
                skipMtlsChecking?: undefined;
            };
        };
        routes: any;
    }>;
    deactivate(paymentType: string, adminUserId: string): Promise<any>;
    createCheckout(payment: any, payerInput?: PaymentCheckoutPayer, options?: {
        trialDays?: number;
    }): Promise<{
        provider: string;
        providerPaymentId: string;
        pixCopyPaste: string | null;
        qrCodeBase64: null;
        expiresAt: null;
        metadata: {
            efiAutomaticPix: boolean;
            efiJourney: string;
            efiRecurrenceId: string;
            efiRecurrenceStatus: string;
            efiRecurrenceLocationId: number;
            efiRecurrenceLocation: string | null;
            efiNextChargeDate: string;
            efiTrialDays: number;
            requiresAuthorization: boolean;
            efiSandbox: boolean;
        };
    } | {
        provider: string;
        providerPaymentId: string;
        pixCopyPaste: string | null;
        qrCodeBase64: null;
        expiresAt: Date;
        metadata: {
            efiAutomaticPix: boolean;
            efiRecurrenceId: string;
            efiRecurrenceStatus: string;
            efiRecurrenceLocationId: number;
            efiRecurrenceLocation: string | null;
            efiNextChargeDate: string;
            efiSandbox: boolean;
            efiJourney?: undefined;
            efiTrialDays?: undefined;
            requiresAuthorization?: undefined;
        };
    } | {
        provider: string;
        providerPaymentId: string;
        pixCopyPaste: string | null;
        qrCodeBase64: string | null;
        expiresAt: Date;
        metadata: {
            efiStatus: string | null;
            efiLocationId: number | null;
            efiLocation: string | null;
            efiPaymentLink: string | null;
            efiSandbox: boolean;
        };
    } | {
        provider: string;
        providerPaymentId: string;
        pixCopyPaste: any;
        qrCodeBase64: any;
        expiresAt: null;
        metadata: {
            mercadoPagoOrderId: string;
            mercadoPagoOrderStatus: any;
            mercadoPagoTransactionId: any;
            mercadoPagoTransactionStatus: any;
            mercadoPagoStatusDetail: any;
            ticketUrl: any;
            externalReference: string;
            checkoutApi: string;
            payerDocumentType: "CNPJ" | "CPF" | null;
        };
    }>;
}
