import { Repository } from 'typeorm';
import type { Response } from 'express';
import { Company } from '../companies/entities/company.entity';
import { Job } from '../jobs/entities/job.entity';
import { CompanySlugAlias } from '../companies/entities/company-slug-alias.entity';
export declare class PublicSeoController {
    private readonly companies;
    private readonly jobs;
    private readonly companySlugAliases;
    private readonly recentJobViews;
    constructor(companies: Repository<Company>, jobs: Repository<Job>, companySlugAliases: Repository<CompanySlugAlias>);
    locationHint(req: any): {
        city: any;
        state: any;
        country: any;
        latitude: number | null;
        longitude: number | null;
        source: string | null;
    };
    jobsIndex(): Promise<{
        count: number;
        cities: {
            city: string;
            state: string | null;
            count: number;
            updatedAt: Date;
            slug: string;
        }[];
        jobs: {
            id: string;
            slug: string | null;
            title: string;
            companyName: string;
            sourceName: string | null;
            location: string;
            city: string | null;
            state: string | null;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            sourcePublishedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        }[];
    }>;
    slugAvailability(value?: string): Promise<{
        slug: string;
        available: boolean;
    }>;
    company(slug: string): Promise<{
        company: {
            id: string;
            name: string;
            slug: string | null;
            description: string;
            website: string;
            address: string;
            cityState: string | null;
            city: string | null;
            state: string | null;
            phone: string;
            logoURL: string;
            socialInstagram: string;
            socialLinkedin: string;
            socialFacebook: string;
            updatedAt: Date;
        };
        jobs: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            location: string;
            city: string | null;
            state: string | null;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            isTalentPool: boolean;
            acceptsPlatformApplications: boolean;
            requiresResumeFile: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            deadlineDate: string | null;
            sourcePublishedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            views: number;
            company: {
                id: string;
                name: string;
                slug: string | null;
                description: string;
                website: string;
                address: string;
                cityState: string | null;
                city: string | null;
                state: string | null;
                phone: string;
                logoURL: string;
                socialInstagram: string;
                socialLinkedin: string;
                socialFacebook: string;
                updatedAt: Date;
            } | null;
            companyName: string | null;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
        }[];
        resolvedFromAlias: boolean;
    }>;
    job(slug: string): Promise<{
        id: string;
        slug: string | null;
        title: string;
        description: string;
        requirements: string | null;
        location: string;
        city: string | null;
        state: string | null;
        type: string;
        workModel: string;
        salary: string | null;
        estimatedSalary: string | null;
        estimatedSalarySource: string | null;
        estimatedSalarySourceUrl: string | null;
        estimatedSalaryRegion: string | null;
        estimatedSalaryUpdatedAt: Date | null;
        pcdMode: string;
        isTalentPool: boolean;
        acceptsPlatformApplications: boolean;
        requiresResumeFile: boolean;
        externalApplicationInstructions: string | null;
        applicationEmail: string | null;
        applicationWhatsApp: string | null;
        applicationUrl: string | null;
        applicationUrlTitle: string | null;
        deadlineDate: string | null;
        sourcePublishedAt: Date | null;
        createdAt: Date;
        updatedAt: Date;
        views: number;
        company: {
            id: string;
            name: string;
            slug: string | null;
            description: string;
            website: string;
            address: string;
            cityState: string | null;
            city: string | null;
            state: string | null;
            phone: string;
            logoURL: string;
            socialInstagram: string;
            socialLinkedin: string;
            socialFacebook: string;
            updatedAt: Date;
        } | null;
        companyName: string | null;
        isExternalListing: boolean;
        sourceName: string | null;
        sourceUrl: string | null;
    }>;
    jobsByCity(citySlug: string): Promise<{
        city: string;
        state: string | null;
        slug: string;
        count: number;
        jobs: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            location: string;
            city: string | null;
            state: string | null;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            isTalentPool: boolean;
            acceptsPlatformApplications: boolean;
            requiresResumeFile: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            deadlineDate: string | null;
            sourcePublishedAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
            views: number;
            company: {
                id: string;
                name: string;
                slug: string | null;
                description: string;
                website: string;
                address: string;
                cityState: string | null;
                city: string | null;
                state: string | null;
                phone: string;
                logoURL: string;
                socialInstagram: string;
                socialLinkedin: string;
                socialFacebook: string;
                updatedAt: Date;
            } | null;
            companyName: string | null;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
        }[];
        updatedAt: Date | null;
    }>;
    registerJobView(id: string, req: any): Promise<{
        views: number;
        counted: boolean;
    }>;
    registerJobViewBySlug(slug: string, req: any): Promise<{
        views: number;
        counted: boolean;
    }>;
    sitemap(response: Response): Promise<void>;
    private incrementJobView;
    private publicJobsQuery;
    private cityName;
    private stateFromLocation;
    private findPublicJob;
    private publicJobCompany;
    private publicCompany;
    private publicJob;
    private escapeXml;
}
