import { DataSource } from 'typeorm';
export declare const IDENTITY_COMPLIANCE_CONSENT_VERSION = "2026-08-26-simple";
export declare class IdentityComplianceService {
    private readonly dataSource;
    constructor(dataSource: DataSource);
    resolveUserId(firebaseUid: string, email?: string): Promise<string>;
    myStatus(uid: string): Promise<{
        consentVersion: string;
        user: {
            id: any;
            name: any;
            email: any;
            phone: any;
            phoneVerified: boolean;
            contactReady: boolean;
        };
        company: {
            id: any;
            name: any;
            cnpj: any;
            hasCnpj: boolean;
            legalName: any;
            registryTradeName: any;
            legalAddress: any;
            legalCity: any;
            legalState: any;
            legalZipCode: any;
            commercialAddress: any;
            commercialCity: any;
            commercialState: any;
            commercialAddressSameAsLegal: boolean;
            cnpjSituation: any;
            cnpjDataSource: any;
            cnpjDataCheckedAt: any;
            cnpjDataUpdatedAt: any;
            cnpjSnapshot: any;
            cnpjChangeAlert: any;
            verified: boolean;
            verificationStatus: any;
            complianceStatus: any;
            membership: any;
            authorizations: any;
        } | null;
        verifications: any;
    }>;
    saveProfile(uid: string, body: Record<string, unknown>): Promise<{
        id: any;
        userId: any;
        companyId: any;
        context: any;
        relationship: any;
        selectedQsaName: any;
        selectedQsaQualification: any;
        declaresAtLeast25Percent: boolean;
        status: any;
        consentVersion: any;
        consentAcceptedAt: any;
        submittedAt: any;
        reviewedAt: any;
        reviewReason: any;
        documents: any;
        createdAt: any;
        updatedAt: any;
    }>;
    replacePartners(uid: string, partnersRaw: unknown): Promise<{
        consentVersion: string;
        user: {
            id: any;
            name: any;
            email: any;
            phone: any;
            phoneVerified: boolean;
            contactReady: boolean;
        };
        company: {
            id: any;
            name: any;
            cnpj: any;
            hasCnpj: boolean;
            legalName: any;
            registryTradeName: any;
            legalAddress: any;
            legalCity: any;
            legalState: any;
            legalZipCode: any;
            commercialAddress: any;
            commercialCity: any;
            commercialState: any;
            commercialAddressSameAsLegal: boolean;
            cnpjSituation: any;
            cnpjDataSource: any;
            cnpjDataCheckedAt: any;
            cnpjDataUpdatedAt: any;
            cnpjSnapshot: any;
            cnpjChangeAlert: any;
            verified: boolean;
            verificationStatus: any;
            complianceStatus: any;
            membership: any;
            authorizations: any;
        } | null;
        verifications: any;
    }>;
    uploadDocument(uid: string, kindRaw: string, file: Express.Multer.File, body: Record<string, unknown>): Promise<any>;
    submit(uid: string, body: Record<string, unknown>): Promise<{
        id: any;
        userId: any;
        companyId: any;
        context: any;
        relationship: any;
        selectedQsaName: any;
        selectedQsaQualification: any;
        declaresAtLeast25Percent: boolean;
        status: any;
        consentVersion: any;
        consentAcceptedAt: any;
        submittedAt: any;
        reviewedAt: any;
        reviewReason: any;
        documents: any;
        createdAt: any;
        updatedAt: any;
    }>;
    adminList(statusRaw?: string): Promise<any>;
    adminDetail(verificationId: string): Promise<{
        verification: {
            id: any;
            userId: any;
            companyId: any;
            context: any;
            relationship: any;
            selectedQsaName: any;
            selectedQsaQualification: any;
            declaresAtLeast25Percent: boolean;
            status: any;
            consentVersion: any;
            consentAcceptedAt: any;
            submittedAt: any;
            reviewedAt: any;
            reviewReason: any;
            documents: any;
            createdAt: any;
            updatedAt: any;
        };
        profile: any;
        documents: any;
        authorizations: any;
        accessLogs: any;
    }>;
    readDocument(actorUserId: string, documentId: string, ip?: string): Promise<{
        buffer: Buffer<ArrayBufferLike>;
        mimeType: any;
        originalName: any;
    }>;
    adminReview(actorUserId: string, verificationId: string, body: Record<string, unknown>): Promise<{
        id: any;
        userId: any;
        companyId: any;
        context: any;
        relationship: any;
        selectedQsaName: any;
        selectedQsaQualification: any;
        declaresAtLeast25Percent: boolean;
        status: any;
        consentVersion: any;
        consentAcceptedAt: any;
        submittedAt: any;
        reviewedAt: any;
        reviewReason: any;
        documents: any;
        createdAt: any;
        updatedAt: any;
    }>;
    assertSellerEligible(uid: string, identity: {
        type?: string;
        company?: {
            id?: string;
        } | null;
    }): Promise<boolean>;
    enforceCompanyDeadlines(): Promise<{
        checked: number;
        disabledBySimplifiedFlow: boolean;
    }>;
    private restoreCompanyResources;
    private hasApprovedIdentity;
    private upsertVerification;
    private companyForUser;
    private assertMembership;
    private assertPrimaryAdmin;
    private context;
    private relationship;
    private percentage;
    private normalizeName;
    private presentVerification;
    private vaultDir;
    private encryptionKey;
}
