import type { Response } from 'express';
import { CompanyContextRepairService } from './company-context-repair.service';
import { IdentityComplianceService } from './identity-compliance.service';
export declare class IdentityComplianceController {
    private readonly compliance;
    private readonly companyContext;
    constructor(compliance: IdentityComplianceService, companyContext: CompanyContextRepairService);
    me(req: any): Promise<{
        consentVersion: string;
        user: {
            id: any;
            name: any;
            email: any;
            phone: any;
            phoneVerified: boolean;
            contactReady: boolean;
        };
        company: {
            id: any;
            name: any;
            cnpj: any;
            hasCnpj: boolean;
            legalName: any;
            registryTradeName: any;
            legalAddress: any;
            legalCity: any;
            legalState: any;
            legalZipCode: any;
            commercialAddress: any;
            commercialCity: any;
            commercialState: any;
            commercialAddressSameAsLegal: boolean;
            cnpjSituation: any;
            cnpjDataSource: any;
            cnpjDataCheckedAt: any;
            cnpjDataUpdatedAt: any;
            cnpjSnapshot: any;
            cnpjChangeAlert: any;
            verified: boolean;
            verificationStatus: any;
            complianceStatus: any;
            membership: any;
            authorizations: any;
        } | null;
        verifications: any;
    }>;
    profile(req: any, body: Record<string, unknown>): Promise<{
        id: any;
        userId: any;
        companyId: any;
        context: any;
        relationship: any;
        selectedQsaName: any;
        selectedQsaQualification: any;
        declaresAtLeast25Percent: boolean;
        status: any;
        consentVersion: any;
        consentAcceptedAt: any;
        submittedAt: any;
        reviewedAt: any;
        reviewReason: any;
        documents: any;
        createdAt: any;
        updatedAt: any;
    }>;
    partners(req: any, body: any): Promise<{
        consentVersion: string;
        user: {
            id: any;
            name: any;
            email: any;
            phone: any;
            phoneVerified: boolean;
            contactReady: boolean;
        };
        company: {
            id: any;
            name: any;
            cnpj: any;
            hasCnpj: boolean;
            legalName: any;
            registryTradeName: any;
            legalAddress: any;
            legalCity: any;
            legalState: any;
            legalZipCode: any;
            commercialAddress: any;
            commercialCity: any;
            commercialState: any;
            commercialAddressSameAsLegal: boolean;
            cnpjSituation: any;
            cnpjDataSource: any;
            cnpjDataCheckedAt: any;
            cnpjDataUpdatedAt: any;
            cnpjSnapshot: any;
            cnpjChangeAlert: any;
            verified: boolean;
            verificationStatus: any;
            complianceStatus: any;
            membership: any;
            authorizations: any;
        } | null;
        verifications: any;
    }>;
    upload(req: any, kind: string, file: Express.Multer.File, body: Record<string, unknown>): Promise<any>;
    submit(req: any, body: Record<string, unknown>): Promise<{
        id: any;
        userId: any;
        companyId: any;
        context: any;
        relationship: any;
        selectedQsaName: any;
        selectedQsaQualification: any;
        declaresAtLeast25Percent: boolean;
        status: any;
        consentVersion: any;
        consentAcceptedAt: any;
        submittedAt: any;
        reviewedAt: any;
        reviewReason: any;
        documents: any;
        createdAt: any;
        updatedAt: any;
    }>;
}
export declare class IdentityComplianceAdminController {
    private readonly compliance;
    constructor(compliance: IdentityComplianceService);
    list(status?: string): Promise<any>;
    detail(id: string): Promise<{
        verification: {
            id: any;
            userId: any;
            companyId: any;
            context: any;
            relationship: any;
            selectedQsaName: any;
            selectedQsaQualification: any;
            declaresAtLeast25Percent: boolean;
            status: any;
            consentVersion: any;
            consentAcceptedAt: any;
            submittedAt: any;
            reviewedAt: any;
            reviewReason: any;
            documents: any;
            createdAt: any;
            updatedAt: any;
        };
        profile: any;
        documents: any;
        authorizations: any;
        accessLogs: any;
    }>;
    document(req: any, documentId: string, res: Response): Promise<void>;
    review(req: any, id: string, body: Record<string, unknown>): Promise<{
        id: any;
        userId: any;
        companyId: any;
        context: any;
        relationship: any;
        selectedQsaName: any;
        selectedQsaQualification: any;
        declaresAtLeast25Percent: boolean;
        status: any;
        consentVersion: any;
        consentAcceptedAt: any;
        submittedAt: any;
        reviewedAt: any;
        reviewReason: any;
        documents: any;
        createdAt: any;
        updatedAt: any;
    }>;
}
