import React, { useEffect, useMemo, useState } from 'react';
import { BadgeCheck, Building2, CheckCircle2, ChevronRight, FileSearch, Loader2, RefreshCw, ShieldAlert, ShieldCheck, UserRound, UsersRound, X, XCircle } from 'lucide-react';
import { api } from '../lib/api';

type VerificationRow={id:string;userId:string;companyId?:string|null;context:'PERSONAL'|'COMPANY';relationship:'PERSONAL'|'EMPLOYEE'|'PARTNER';partnerPercentage?:number|null;status:string;submittedAt?:string|null;createdAt:string;userName:string;email?:string|null;phone?:string|null;whatsappPhoneE164?:string|null;companyName?:string|null;companyVerificationStatus?:string|null;complianceStatus?:string|null;complianceGraceDeadline?:string|null;documentCount:number};
type Detail={verification:any;profile:any;documents:any[];partners:any[];accessLogs:any[]};
const FILTERS=['PENDING','NEEDS_CHANGES','REJECTED','APPROVED','ALL'] as const;

export default function AdminIdentityVerificationsPage(){
  const[filter,setFilter]=useState<(typeof FILTERS)[number]>('PENDING');
  const[rows,setRows]=useState<VerificationRow[]>([]);
  const[loading,setLoading]=useState(true);
  const[selected,setSelected]=useState<string|null>(null);
  const[detail,setDetail]=useState<Detail|null>(null);
  const[detailLoading,setDetailLoading]=useState(false);
  const[working,setWorking]=useState('');
  const[reason,setReason]=useState('');
  const[message,setMessage]=useState('');
  const[document,setDocument]=useState<{url:string;mimeType:string;name:string}|null>(null);

  const load=async()=>{setLoading(true);try{const r=await api.get(`/admin/compliance/verifications?status=${filter}`);setRows(Array.isArray(r.data)?r.data:[])}catch(e:any){setMessage(e?.response?.data?.message||'Não foi possível carregar a fila de validação.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[filter]);
  const open=async(id:string)=>{setSelected(id);setDetail(null);setReason('');setDetailLoading(true);try{const r=await api.get(`/admin/compliance/verifications/${id}`);setDetail(r.data)}catch(e:any){setMessage(e?.response?.data?.message||'Não foi possível abrir o dossiê.')}finally{setDetailLoading(false)}};
  const close=()=>{setSelected(null);setDetail(null);setReason('');if(document){URL.revokeObjectURL(document.url);setDocument(null)}};
  const review=async(decision:'APPROVE'|'REJECT'|'NEEDS_CHANGES')=>{if(!selected)return;setWorking(decision);setMessage('');try{await api.post(`/admin/compliance/verifications/${selected}/review`,{decision,reason});setMessage(decision==='APPROVE'?'Verificação aprovada.':decision==='REJECT'?'Verificação reprovada.':'Ajustes solicitados.');close();await load()}catch(e:any){setMessage(e?.response?.data?.message||'Não foi possível registrar a decisão.')}finally{setWorking('')}};
  const viewDocument=async(doc:any)=>{setWorking(`doc-${doc.id}`);try{const r=await api.get(`/admin/compliance/documents/${doc.id}`,{responseType:'blob'});if(document)URL.revokeObjectURL(document.url);const blob=r.data as Blob;setDocument({url:URL.createObjectURL(blob),mimeType:blob.type||doc.mimeType,name:doc.originalName||'Documento'})}catch(e:any){setMessage(e?.response?.data?.message||'Não foi possível abrir o documento.')}finally{setWorking('')}};

  return <div className="mx-auto max-w-7xl space-y-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-violet-700">Compliance · Marketplace</p><h1 className="mt-1 font-serif text-3xl font-black">Validação cadastral</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-stone-500">Analise identidade, documentos, endereço e vínculo empresarial. Abrir um documento descriptografa apenas para esta sessão administrativa e registra a visualização na trilha de auditoria.</p></div><button onClick={()=>void load()} className="inline-flex h-11 items-center gap-2 rounded-2xl bg-white px-4 text-xs font-black ring-1 ring-stone-200"><RefreshCw className="h-4 w-4"/>Atualizar fila</button></header>
    {message&&<div className="rounded-2xl bg-stone-900 px-4 py-3 text-sm font-bold text-white">{message}</div>}
    <div className="flex gap-2 overflow-x-auto pb-1">{FILTERS.map(item=><button key={item} onClick={()=>setFilter(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-[10px] font-black uppercase tracking-[.1em] ${filter===item?'bg-stone-950 text-white':'bg-white text-stone-500 ring-1 ring-stone-200'}`}>{filterLabel(item)}</button>)}</div>
    <section className="overflow-hidden rounded-[28px] bg-white ring-1 ring-stone-200">{loading?<div className="flex min-h-64 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-stone-400"/></div>:rows.length?<div className="divide-y divide-stone-100">{rows.map(row=><button key={row.id} onClick={()=>void open(row.id)} className="grid w-full gap-3 p-4 text-left transition hover:bg-stone-50 sm:grid-cols-[minmax(0,1.5fr)_minmax(0,1fr)_auto] sm:items-center sm:p-5"><div className="flex min-w-0 items-center gap-3"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl ${row.context==='COMPANY'?'bg-[#eef8f6] text-[#397c75]':'bg-violet-50 text-violet-700'}`}>{row.context==='COMPANY'?<Building2 className="h-5 w-5"/>:<UserRound className="h-5 w-5"/>}</span><div className="min-w-0"><p className="truncate text-sm font-black text-stone-950">{row.userName}</p><p className="mt-0.5 truncate text-[11px] text-stone-400">{row.email||'Sem e-mail'} · {relationshipLabel(row.relationship)}</p>{row.companyName&&<p className="mt-1 truncate text-[11px] font-bold text-[#397c75]">{row.companyName}</p>}</div></div><div className="text-xs text-stone-500"><p><strong>{row.documentCount}</strong> documento(s)</p><p className="mt-1">Enviado {row.submittedAt?dateTime(row.submittedAt):'ainda não enviado'}</p>{row.companyName&&<p className="mt-1">Empresa: <strong>{row.complianceStatus||'sem compliance'}</strong></p>}</div><div className="flex items-center justify-between gap-3 sm:justify-end"><Status status={row.status}/><ChevronRight className="h-4 w-4 text-stone-300"/></div></button>)}</div>:<div className="flex min-h-64 flex-col items-center justify-center p-6 text-center"><ShieldCheck className="h-8 w-8 text-emerald-500"/><p className="mt-3 text-sm font-black">Nada nesta fila</p><p className="mt-1 text-xs text-stone-400">As novas solicitações aparecerão aqui.</p></div>}</section>
    {selected&&<div className="fixed inset-0 z-[180] overflow-y-auto bg-black/60 p-3 sm:p-6" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="mx-auto my-3 max-w-6xl overflow-hidden rounded-[30px] bg-[#f7f5f2] shadow-2xl"><header className="sticky top-0 z-20 flex items-start justify-between gap-4 border-b border-stone-200 bg-white/95 px-5 py-5 backdrop-blur sm:px-7"><div><p className="text-[9px] font-black uppercase tracking-[.16em] text-violet-700">Dossiê de validação</p><h2 className="mt-1 font-serif text-2xl font-black">{detail?.profile?.userName||'Carregando...'}</h2></div><button onClick={close} className="flex h-10 w-10 items-center justify-center rounded-full bg-stone-100"><X className="h-4 w-4"/></button></header>{detailLoading?<div className="flex min-h-[55vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-stone-400"/></div>:detail&&<Dossier detail={detail} onDocument={doc=>void viewDocument(doc)} working={working} reason={reason} setReason={setReason} onReview={decision=>void review(decision)}/>}</section></div>}
    {document&&<div className="fixed inset-0 z-[220] flex items-center justify-center bg-black/80 p-3"><div className="relative flex h-[92vh] w-full max-w-5xl flex-col overflow-hidden rounded-[24px] bg-white"><div className="flex items-center justify-between border-b px-4 py-3"><div><p className="text-[9px] font-black uppercase tracking-[.12em] text-stone-400">Visualização auditada</p><p className="text-sm font-black">{document.name}</p></div><button onClick={()=>{URL.revokeObjectURL(document.url);setDocument(null)}} className="flex h-9 w-9 items-center justify-center rounded-full bg-stone-100"><X className="h-4 w-4"/></button></div><div className="min-h-0 flex-1 bg-stone-950">{document.mimeType.includes('pdf')?<iframe src={document.url} title={document.name} className="h-full w-full bg-white"/>:<img src={document.url} alt={document.name} className="h-full w-full object-contain"/>}</div></div></div>}
  </div>;
}

function Dossier({detail,onDocument,working,reason,setReason,onReview}:{detail:Detail;onDocument:(doc:any)=>void;working:string;reason:string;setReason:(v:string)=>void;onReview:(d:'APPROVE'|'REJECT'|'NEEDS_CHANGES')=>void}){const p=detail.profile;const v=detail.verification;const primary=p.membershipRole==='PRIMARY_ADMIN';const partner=v.relationship==='PARTNER';return <div className="space-y-5 p-4 sm:p-6">
  <div className="grid gap-4 lg:grid-cols-3"><Info title="Pessoa" icon={<UserRound className="h-5 w-5"/>}><Line label="Nome" value={p.userName}/><Line label="E-mail" value={p.email}/><Line label="Telefone" value={p.whatsappPhoneE164||p.phone}/><Line label="Endereço cadastrado" value={[p.address,[p.city,p.state].filter(Boolean).join('/')].filter(Boolean).join(', ')}/></Info><Info title="Vínculo" icon={<UsersRound className="h-5 w-5"/>}><Line label="Contexto" value={v.context==='COMPANY'?'Empresa':'Pessoal'}/><Line label="Relação" value={relationshipLabel(v.relationship)}/><Line label="Participação" value={v.partnerPercentage==null?'Não informada':`${v.partnerPercentage}%`}/><Line label="Papel na empresa" value={membershipLabel(p.membershipRole)}/><Line label="Poderes declarados" value={v.declaresRepresentationPowers?'Sim':'Não'}/></Info><Info title="Empresa" icon={<Building2 className="h-5 w-5"/>}><Line label="Nome" value={p.companyName||'Não vinculada'}/><Line label="CNPJ/CPF" value={p.cnpj||p.cpf||'Não informado'}/><Line label="Verificação empresarial" value={p.companyVerificationStatus||'N/A'}/><Line label="Compliance" value={p.complianceStatus||'N/A'}/><Line label="Prazo" value={p.complianceGraceDeadline?dateTime(p.complianceGraceDeadline):'Sem prazo ativo'}/></Info></div>
  {v.context==='COMPANY'&&<section className={`rounded-2xl border p-4 ${primary&&partner?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`}><div className="flex gap-3">{primary&&partner?<BadgeCheck className="h-5 w-5 text-emerald-700"/>:<ShieldAlert className="h-5 w-5 text-amber-700"/>}<div><p className="text-sm font-black">{primary&&partner?'Sócio/representante é o administrador principal':'Esta validação não valida a empresa'}</p><p className="mt-1 text-xs leading-5 text-stone-600">{primary&&partner?'Se aprovada, valida a pessoa e o vínculo principal da empresa.':'Funcionário ou sócio que não seja o administrador principal tem sua identidade validada, mas não altera o status jurídico/compliance da empresa.'}</p></div></div></section>}
  <section className="rounded-[24px] bg-white p-5 ring-1 ring-stone-200"><h3 className="text-sm font-black">Documentos</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{detail.documents.map(doc=><button key={doc.id} onClick={()=>onDocument(doc)} className="flex items-center gap-3 rounded-2xl bg-stone-50 p-4 text-left ring-1 ring-stone-200 hover:bg-stone-100"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white"><FileSearch className="h-4 w-4"/></span><div className="min-w-0 flex-1"><p className="text-xs font-black">{documentLabel(doc.kind)}</p><p className="mt-0.5 truncate text-[10px] text-stone-400">{doc.originalName}</p></div>{working===`doc-${doc.id}`?<Loader2 className="h-4 w-4 animate-spin"/>:<ChevronRight className="h-4 w-4 text-stone-300"/>}</button>)}</div></section>
  {detail.partners.length>0&&<section className="rounded-[24px] bg-white p-5 ring-1 ring-stone-200"><h3 className="text-sm font-black">Quadro societário declarado</h3><p className="mt-1 text-xs text-stone-500">Declaração informativa. O sistema não exige aceite documental de todos os sócios por padrão.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="text-[9px] uppercase tracking-[.1em] text-stone-400"><tr><th className="pb-2">Sócio</th><th>Participação</th><th>Beneficiário final declarado</th><th>Poderes administrativos</th><th>Contato</th></tr></thead><tbody>{detail.partners.map(partner=><tr key={partner.id} className="border-t border-stone-100"><td className="py-3 font-black">{partner.name}</td><td>{Number(partner.participationPercentage).toLocaleString('pt-BR')}%</td><td>{partner.isBeneficialOwner?'Sim':'Não'}</td><td>{partner.hasAdministrativePowers?'Sim':'Não'}</td><td>{partner.email||partner.phone||'Não informado'}</td></tr>)}</tbody></table></div></section>}
  <section className="rounded-[24px] bg-white p-5 ring-1 ring-stone-200"><div className="flex items-center justify-between gap-3"><div><h3 className="text-sm font-black">Decisão da análise</h3><p className="mt-1 text-xs text-stone-500">Aprovar libera a identidade. Se este for o sócio/representante e administrador principal, também regulariza a empresa.</p></div><Status status={v.status}/></div><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={4} placeholder="Observações internas ou motivo para ajustes/reprovação" className="mt-4 w-full rounded-2xl border border-stone-200 bg-stone-50 p-4 text-sm outline-none focus:border-violet-400"/><div className="mt-4 grid gap-2 sm:grid-cols-3"><button disabled={Boolean(working)} onClick={()=>onReview('APPROVE')} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-emerald-700 text-xs font-black text-white disabled:opacity-50"><CheckCircle2 className="h-4 w-4"/>Aprovar</button><button disabled={Boolean(working)} onClick={()=>onReview('NEEDS_CHANGES')} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-amber-500 text-xs font-black text-amber-950 disabled:opacity-50"><ShieldAlert className="h-4 w-4"/>Pedir ajustes</button><button disabled={Boolean(working)} onClick={()=>onReview('REJECT')} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-red-700 text-xs font-black text-white disabled:opacity-50"><XCircle className="h-4 w-4"/>Reprovar</button></div></section>
  {detail.accessLogs.length>0&&<section className="rounded-[24px] bg-white p-5 ring-1 ring-stone-200"><h3 className="text-sm font-black">Trilha de acesso aos documentos</h3><div className="mt-3 space-y-2">{detail.accessLogs.map(log=><div key={log.id} className="flex items-center justify-between gap-3 rounded-xl bg-stone-50 px-3 py-2 text-[11px]"><span><strong>{log.actorName||log.actorUserId}</strong> · {log.action}</span><span className="text-stone-400">{dateTime(log.createdAt)}</span></div>)}</div></section>}
</div>}
function Info({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="rounded-[24px] bg-white p-5 ring-1 ring-stone-200"><div className="flex items-center gap-2 text-stone-800">{icon}<h3 className="text-sm font-black">{title}</h3></div><div className="mt-4 space-y-3">{children}</div></section>}
function Line({label,value}:{label:string;value:any}){return <div><p className="text-[9px] font-black uppercase tracking-[.1em] text-stone-400">{label}</p><p className="mt-0.5 break-words text-xs font-semibold text-stone-700">{value||'Não informado'}</p></div>}
function Status({status}:{status:string}){const cls=status==='APPROVED'?'bg-emerald-50 text-emerald-700':status==='PENDING'?'bg-amber-50 text-amber-700':status==='REJECTED'?'bg-red-50 text-red-700':status==='NEEDS_CHANGES'?'bg-orange-50 text-orange-700':'bg-stone-100 text-stone-500';return <span className={`rounded-full px-3 py-1.5 text-[9px] font-black uppercase tracking-[.1em] ${cls}`}>{filterLabel(status)}</span>}
function filterLabel(value:string){return({PENDING:'Em análise',NEEDS_CHANGES:'Ajustes',REJECTED:'Reprovadas',APPROVED:'Aprovadas',ALL:'Todas',DRAFT:'Rascunho'} as any)[value]||value}
function relationshipLabel(value:string){return value==='PARTNER'?'Sócio(a) / representante':value==='EMPLOYEE'?'Funcionário(a) / colaborador(a)':'Pessoal'}
function membershipLabel(value?:string){return value==='PRIMARY_ADMIN'?'Administrador principal':value==='ADMIN'?'Administrador':value==='EMPLOYEE'?'Funcionário':'Não identificado'}
function documentLabel(kind:string){return({SELFIE:'Selfie',ID_FRONT:'Documento oficial',ID_BACK:'Verso do documento',ADDRESS_PROOF:'Comprovante de endereço',REPRESENTATION_PROOF:'Prova de representação'} as any)[kind]||kind}
function dateTime(value:string){try{return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value))}catch{return value}}
