import React, { useEffect, useState } from 'react';
import { BriefcaseBusiness, Building2, Check, Eye, Globe2, Loader2, ShoppingBag, Wrench } from 'lucide-react';
import { api } from '../lib/api';
import { useAuth } from '../contexts/AuthContext';
import { COMPANY_SITE_TYPES, resolveCompanySiteType, type CompanySiteConfig, type CompanySiteType } from '../components/company-site/types';

const iconByType:Record<CompanySiteType,React.ReactNode>={store:<ShoppingBag className="h-5 w-5"/>,institutional:<Building2 className="h-5 w-5"/>,services:<Wrench className="h-5 w-5"/>,careers:<BriefcaseBusiness className="h-5 w-5"/>};

export function CompanySiteSettingsPage(){
 const {profile}=useAuth(); const companyId=profile?.companyId||'';
 const [config,setConfig]=useState<CompanySiteConfig>({version:3,siteType:'institutional'}); const [status,setStatus]=useState<'DRAFT'|'PUBLISHED'>('DRAFT');
 const [company,setCompany]=useState<any>(null); const [loading,setLoading]=useState(true); const [working,setWorking]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
 useEffect(()=>{if(!companyId)return;let active=true;setLoading(true);api.get(`/companies/${companyId}/page`).then(r=>{if(!active)return;setConfig(r.data?.draft||{version:3,siteType:'institutional'});setStatus(r.data?.status==='PUBLISHED'?'PUBLISHED':'DRAFT');setCompany(r.data?.company||null)}).catch((e:any)=>active&&setError(e?.response?.data?.message||'Não foi possível carregar o site da empresa.')).finally(()=>active&&setLoading(false));return()=>{active=false}},[companyId]);
 const current=resolveCompanySiteType(config);
 const choose=(siteType:CompanySiteType)=>{setConfig(c=>({...c,version:3,siteType}));setMessage('');};
 const publish=async()=>{if(!companyId)return;setWorking(true);setError('');setMessage('');try{await api.put(`/companies/${companyId}/page/draft`,{config:{...config,version:3,siteType:current}});const r=await api.post(`/companies/${companyId}/page/publish`,{config:{...config,version:3,siteType:current}});setConfig(r.data?.draft||config);setStatus('PUBLISHED');setMessage('Site publicado. Os dados continuam sendo atualizados pelos módulos da empresa no PiraNegócios.');}catch(e:any){setError(e?.response?.data?.message||'Não foi possível publicar o site.');}finally{setWorking(false)}};
 const unpublish=async()=>{if(!companyId||!window.confirm('Tirar o site público do ar? O perfil e os dados da empresa não serão apagados.'))return;setWorking(true);try{await api.delete(`/companies/${companyId}/page/published`);setStatus('DRAFT');setMessage('Site retirado do ar.');}catch(e:any){setError(e?.response?.data?.message||'Não foi possível retirar o site do ar.');}finally{setWorking(false)}};
 if(loading)return <div className="flex min-h-[55vh] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-stone-400"/></div>;
 return <div className="mx-auto max-w-7xl space-y-6 pb-16"><section className="overflow-hidden rounded-[30px] bg-stone-950 p-7 text-white sm:p-9"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-emerald-300">Site da empresa</p><h1 className="mt-2 text-4xl font-black tracking-[-.055em] sm:text-5xl">Escolha uma experiência. Não monte uma página.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/55">O site usa automaticamente identidade, endereço, catálogo, serviços, vagas, avaliações e canais oficiais da empresa. Você escolhe apenas a arquitetura que melhor representa o negócio.</p></div><span className={`rounded-full px-3 py-2 text-[10px] font-black ${status==='PUBLISHED'?'bg-emerald-400/15 text-emerald-300':'bg-white/10 text-white/60'}`}>{status==='PUBLISHED'?'PUBLICADO':'FORA DO AR'}</span></div></section>
 {message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-900">{message}</div>}{error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-800">{error}</div>}
 <section className="grid gap-4 lg:grid-cols-2">{COMPANY_SITE_TYPES.map(item=><button key={item.id} type="button" onClick={()=>choose(item.id)} className={`group overflow-hidden rounded-[28px] border bg-white text-left shadow-sm transition hover:-translate-y-0.5 ${current===item.id?'border-stone-950 ring-2 ring-stone-950/10':'border-stone-200'}`}><SitePreview type={item.id}/><div className="p-5 sm:p-6"><div className="flex items-start gap-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl ${current===item.id?'bg-stone-950 text-white':'bg-stone-100 text-stone-600'}`}>{iconByType[item.id]}</span><div className="min-w-0 flex-1"><p className="text-[9px] font-black uppercase tracking-[.14em] text-stone-400">{item.eyebrow}</p><h2 className="mt-1 text-xl font-black text-stone-950">{item.name}</h2></div>{current===item.id&&<span className="flex h-7 w-7 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><Check className="h-4 w-4"/></span>}</div><p className="mt-4 text-sm leading-6 text-stone-600">{item.description}</p><p className="mt-3 text-[11px] font-bold text-stone-400">Indicado para: {item.bestFor}</p></div></button>)}</section>
 <section className="sticky bottom-4 z-20 flex flex-col gap-3 rounded-[24px] border border-stone-200 bg-white/95 p-4 shadow-2xl backdrop-blur sm:flex-row sm:items-center sm:justify-between"><div><strong className="text-sm text-stone-950">{COMPANY_SITE_TYPES.find(x=>x.id===current)?.name}</strong><p className="mt-1 text-xs text-stone-500">Sem seções manuais, sem código customizado e sem tema Frankenstein. O conteúdo acompanha a empresa.</p></div><div className="flex flex-wrap gap-2">{status==='PUBLISHED'&&company?.slug&&<a href={`/${encodeURIComponent(company.slug)}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-stone-200 px-4 py-3 text-xs font-black"><Eye className="h-4 w-4"/>Ver site</a>}{status==='PUBLISHED'&&<button onClick={unpublish} disabled={working} className="rounded-xl border border-red-200 px-4 py-3 text-xs font-black text-red-700">Tirar do ar</button>}<button onClick={publish} disabled={working} className="inline-flex items-center gap-2 rounded-xl bg-stone-950 px-5 py-3 text-xs font-black text-white disabled:opacity-50">{working?<Loader2 className="h-4 w-4 animate-spin"/>:<Globe2 className="h-4 w-4"/>}{status==='PUBLISHED'?'Atualizar site':'Publicar site'}</button></div></section></div>;
}
function SitePreview({type}:{type:CompanySiteType}){const schemes={store:'bg-[#121216]',institutional:'bg-[#0c2742]',services:'bg-[#f5f1e8]',careers:'bg-[#181b3a]'};return <div className={`h-44 p-4 ${schemes[type]}`}><div className={`h-full overflow-hidden rounded-xl ${type==='services'?'bg-white/55':'bg-white/[.06]'} ring-1 ring-black/5`}><div className={`flex h-8 items-center gap-1.5 px-3 ${type==='services'?'bg-[#173b35]':'border-b border-white/10'}`}><span className="h-2 w-2 rounded-full bg-white/35"/><span className="h-2 w-16 rounded-full bg-white/20"/></div><div className="grid h-[calc(100%-2rem)] grid-cols-[1.2fr_.8fr] gap-3 p-4"><div><span className={`block h-2 w-16 rounded ${type==='services'?'bg-[#b15e3f]/40':'bg-white/20'}`}/><span className={`mt-3 block h-5 w-4/5 rounded ${type==='services'?'bg-[#173b35]/80':'bg-white/80'}`}/><span className={`mt-2 block h-5 w-2/3 rounded ${type==='services'?'bg-[#173b35]/55':'bg-white/55'}`}/><span className={`mt-4 block h-2 w-3/4 rounded ${type==='services'?'bg-[#173b35]/20':'bg-white/15'}`}/><span className={`mt-1.5 block h-2 w-1/2 rounded ${type==='services'?'bg-[#173b35]/20':'bg-white/15'}`}/></div><div className={`rounded-xl ${type==='store'?'bg-[#f1ff3d]/15':type==='services'?'bg-white':'bg-white/10'}`}/></div></div></div>}
export default CompanySiteSettingsPage;
