import React, { useEffect, useMemo, useState } from 'react';
import { BadgeCheck, Building2, CheckCircle2, FileCheck2, FileText, Loader2, RefreshCw, ShieldCheck, Upload, UserRound, UsersRound } from 'lucide-react';
import { Link, useLocation } from 'react-router-dom';
import { api } from '../lib/api';

type Context = 'PERSONAL' | 'COMPANY';
type Relationship = 'PERSONAL' | 'EMPLOYEE' | 'PARTNER';
type DocumentKind = 'SELFIE' | 'ID_FRONT' | 'ID_BACK' | 'ADDRESS_PROOF' | 'REPRESENTATION_PROOF';

type Verification = {
  id: string;
  context: Context;
  relationship: Relationship;
  partnerPercentage?: number | null;
  declaresRepresentationPowers?: boolean;
  status: 'DRAFT'|'PENDING'|'APPROVED'|'REJECTED'|'NEEDS_CHANGES';
  reviewReason?: string | null;
  submittedAt?: string | null;
  documents?: Array<{ id:string; kind:DocumentKind; originalName:string; uploadedAt:string }>;
};

type Partner = { name:string; email:string; phone:string; participationPercentage:string; hasAdministrativePowers:boolean };

export default function IdentityVerificationPage() {
  const location = useLocation();
  const routeContext: Context = location.pathname.startsWith('/company/') ? 'COMPANY' : 'PERSONAL';
  const [data,setData]=useState<any>(null);
  const [loading,setLoading]=useState(true);
  const [working,setWorking]=useState('');
  const [message,setMessage]=useState('');
  const [relationship,setRelationship]=useState<Relationship>(routeContext==='COMPANY'?'EMPLOYEE':'PERSONAL');
  const [partnerPercentage,setPartnerPercentage]=useState('');
  const [declaresRepresentation,setDeclaresRepresentation]=useState(false);
  const [accepted,setAccepted]=useState(false);
  const [partners,setPartners]=useState<Partner[]>([]);

  const load=async()=>{setLoading(true);try{const response=await api.get('/compliance/me');setData(response.data);const current=(response.data?.verifications||[]).find((item:Verification)=>item.context===routeContext);if(current){setRelationship(current.relationship);setPartnerPercentage(current.partnerPercentage==null?'':String(current.partnerPercentage).replace('.',','));setDeclaresRepresentation(Boolean(current.declaresRepresentationPowers));}const declared=response.data?.company?.partners||[];setPartners(declared.map((item:any)=>({name:item.name||'',email:item.email||'',phone:item.phone||'',participationPercentage:String(item.participationPercentage??'').replace('.',','),hasAdministrativePowers:Boolean(item.hasAdministrativePowers)})));}catch(error:any){setMessage(error?.response?.data?.message||'Não foi possível carregar sua verificação.');}finally{setLoading(false)}};
  useEffect(()=>{void load()},[routeContext]);

  const verification:Verification|undefined=useMemo(()=>data?.verifications?.find((item:Verification)=>item.context===routeContext),[data,routeContext]);
  const docs=new Map((verification?.documents||[]).map((item)=>[item.kind,item]));
  const company=data?.company;
  const membership=company?.membership;
  const primaryAdmin=membership?.role==='PRIMARY_ADMIN';
  const locked=verification?.status==='PENDING'||verification?.status==='APPROVED';
  const canSubmit=['SELFIE','ID_FRONT','ADDRESS_PROOF'].every((kind)=>docs.has(kind as DocumentKind));

  const saveProfile=async(nextRelationship=relationship)=>{setWorking('profile');setMessage('');try{await api.patch('/compliance/me/profile',{context:routeContext,relationship:nextRelationship,partnerPercentage:nextRelationship==='PARTNER'?partnerPercentage:null,declaresRepresentationPowers:nextRelationship==='PARTNER'?declaresRepresentation:false});await load();}catch(error:any){setMessage(error?.response?.data?.message||'Não foi possível salvar os dados da verificação.');}finally{setWorking('')}};
  const upload=async(kind:DocumentKind,file:File|null)=>{if(!file)return;setWorking(kind);setMessage('');try{const body=new FormData();body.append('file',file);body.append('context',routeContext);await api.post(`/compliance/me/documents/${kind}`,body,{headers:{'Content-Type':'multipart/form-data'}});await load();}catch(error:any){setMessage(error?.response?.data?.message||'Não foi possível enviar o arquivo.');}finally{setWorking('')}};
  const savePartners=async()=>{setWorking('partners');setMessage('');try{await api.patch('/compliance/me/company-partners',{partners:partners.map((item)=>({...item,participationPercentage:Number(item.participationPercentage.replace(',','.'))}))});setMessage('Declaração societária salva.');await load();}catch(error:any){setMessage(error?.response?.data?.message||'Não foi possível salvar os sócios declarados.');}finally{setWorking('')}};
  const submit=async()=>{setWorking('submit');setMessage('');try{await saveProfile();await api.post('/compliance/me/submit',{context:routeContext,accepted,consentVersion:data?.consentVersion});setAccepted(false);setMessage('Documentação enviada para análise. O prazo estimado é de até 48 horas.');await load();}catch(error:any){setMessage(error?.response?.data?.message||'Não foi possível enviar a verificação.');}finally{setWorking('')}};

  if(loading)return <div className="flex min-h-[50vh] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-stone-400"/></div>;
  if(routeContext==='COMPANY'&&!company)return <div className="mx-auto max-w-2xl rounded-3xl bg-amber-50 p-7 text-amber-900"><h1 className="font-serif text-3xl font-black">Sem empresa vinculada</h1><p className="mt-2 text-sm">Vincule ou cadastre uma empresa antes de usar a verificação empresarial.</p><Link to="/company/perfil" className="mt-4 inline-flex rounded-xl bg-stone-900 px-4 py-2.5 text-xs font-black text-white">Ir para Empresa</Link></div>;

  return <div className="mx-auto max-w-6xl space-y-6 pb-14">
    <header className="rounded-[30px] bg-stone-950 p-6 text-white sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-300">Segurança do Marketplace</p><h1 className="mt-2 font-serif text-3xl font-black sm:text-4xl">Verificação cadastral</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/60">Para vender ou publicar, precisamos validar quem está por trás do anúncio. Comprar, favoritar e navegar não exige este processo.</p></div><StatusBadge status={verification?.status||'DRAFT'}/></div></header>

    {message&&<div className="rounded-2xl bg-stone-900 px-4 py-3 text-sm font-bold text-white">{message}</div>}
    {verification?.reviewReason&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Retorno da análise:</strong> {verification.reviewReason}</div>}

    {routeContext==='COMPANY'&&<section className="rounded-[28px] bg-white p-5 ring-1 ring-stone-200 sm:p-6"><div className="flex gap-3"><Building2 className="mt-0.5 h-5 w-5 text-[#397c75]"/><div><p className="text-[10px] font-black uppercase tracking-[.12em] text-stone-400">Empresa</p><h2 className="text-xl font-black">{company?.name}</h2><p className="mt-1 text-xs text-stone-500">Vínculo: {membershipLabel(membership?.role)} · compliance da empresa: {company?.complianceStatus||'não iniciado'}</p>{company?.graceDeadline&&<p className="mt-2 text-xs font-bold text-amber-700">Prazo para regularização do administrador principal: {dateTime(company.graceDeadline)}</p>}</div></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2"><Choice selected={relationship==='EMPLOYEE'} disabled={primaryAdmin} icon={<UsersRound className="h-5 w-5"/>} title="Sou funcionário(a) / colaborador(a)" text="A verificação valida somente a sua identidade e não valida juridicamente a empresa." onClick={()=>{setRelationship('EMPLOYEE');setDeclaresRepresentation(false);void saveProfile('EMPLOYEE')}}/><Choice selected={relationship==='PARTNER'} icon={<BadgeCheck className="h-5 w-5"/>} title="Sou sócio(a) / representante" text={primaryAdmin?'Como administrador principal, esta é a modalidade usada para validar você e a empresa.':'Valida sua identidade. Só valida a empresa quando você é o administrador principal autorizado.'} onClick={()=>{setRelationship('PARTNER');void saveProfile('PARTNER')}}/></div>
      {relationship==='PARTNER'&&<div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Minha participação societária (%)"><input value={partnerPercentage} onChange={e=>setPartnerPercentage(e.target.value)} inputMode="decimal" placeholder="Ex.: 50" className={inputClass}/></Field><label className="flex items-start gap-3 rounded-2xl bg-stone-50 p-4 ring-1 ring-stone-200"><input type="checkbox" checked={declaresRepresentation} onChange={e=>setDeclaresRepresentation(e.target.checked)} className="mt-1 h-4 w-4"/><span className="text-xs leading-5 text-stone-600"><strong className="block text-stone-900">Declaro poderes de representação</strong>Confirmo que sou sócio(a) com poderes para representar a empresa ou possuo autorização válida para agir em nome dela.</span></label></div>}
    </section>}

    <section className="rounded-[28px] bg-white p-5 ring-1 ring-stone-200 sm:p-6"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-violet-700"/><div><h2 className="text-xl font-black">Documentos protegidos</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-stone-500">Selfie, documento e comprovante são guardados fora da área pública, criptografados em repouso. Não use o upload comum de fotos do site para documentos pessoais.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><DocumentCard kind="SELFIE" title="Selfie atual" text="Foto frontal e nítida do titular." uploaded={docs.get('SELFIE')} working={working==='SELFIE'} locked={locked} onFile={file=>void upload('SELFIE',file)}/><DocumentCard kind="ID_FRONT" title="Documento oficial" text="RG, CIN ou CNH. Frente/página principal." uploaded={docs.get('ID_FRONT')} working={working==='ID_FRONT'} locked={locked} onFile={file=>void upload('ID_FRONT',file)}/><DocumentCard kind="ID_BACK" title="Verso do documento" text="Opcional quando o documento tiver verso relevante." uploaded={docs.get('ID_BACK')} working={working==='ID_BACK'} locked={locked} onFile={file=>void upload('ID_BACK',file)}/><DocumentCard kind="ADDRESS_PROOF" title="Comprovante de endereço" text="Documento legível com endereço atual." uploaded={docs.get('ADDRESS_PROOF')} working={working==='ADDRESS_PROOF'} locked={locked} onFile={file=>void upload('ADDRESS_PROOF',file)}/></div>{routeContext==='COMPANY'&&relationship==='PARTNER'&&<div className="mt-3"><DocumentCard kind="REPRESENTATION_PROOF" title="Prova de representação, se aplicável" text="Contrato social, alteração, ata ou procuração. É opcional no envio inicial e pode ser exigido na análise." uploaded={docs.get('REPRESENTATION_PROOF')} working={working==='REPRESENTATION_PROOF'} locked={locked} onFile={file=>void upload('REPRESENTATION_PROOF',file)}/></div>}</section>

    {routeContext==='COMPANY'&&primaryAdmin&&relationship==='PARTNER'&&<section className="rounded-[28px] bg-white p-5 ring-1 ring-stone-200 sm:p-6"><div className="flex items-start gap-3"><UsersRound className="mt-0.5 h-5 w-5 text-blue-700"/><div><h2 className="text-xl font-black">Quadro societário declarado</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-stone-500">Informe os demais sócios relevantes. Sócios com mais de 25% são marcados como beneficiários finais declarados para a ficha de compliance. Nesta modalidade de marketplace, isso não dispara selfie/aceite obrigatório de todos automaticamente.</p></div></div><div className="mt-5 space-y-3">{partners.map((partner,index)=><div key={index} className="grid gap-2 rounded-2xl bg-stone-50 p-4 sm:grid-cols-[1.5fr_1.3fr_1fr_.55fr_auto]"><input value={partner.name} onChange={e=>setPartners(current=>current.map((item,i)=>i===index?{...item,name:e.target.value}:item))} placeholder="Nome do sócio" className={miniInput}/><input value={partner.email} onChange={e=>setPartners(current=>current.map((item,i)=>i===index?{...item,email:e.target.value}:item))} placeholder="E-mail" className={miniInput}/><input value={partner.phone} onChange={e=>setPartners(current=>current.map((item,i)=>i===index?{...item,phone:e.target.value}:item))} placeholder="Telefone" className={miniInput}/><input value={partner.participationPercentage} onChange={e=>setPartners(current=>current.map((item,i)=>i===index?{...item,participationPercentage:e.target.value}:item))} placeholder="%" className={miniInput}/><button type="button" onClick={()=>setPartners(current=>current.filter((_,i)=>i!==index))} className="rounded-xl px-3 text-xs font-black text-red-600">Remover</button><label className="sm:col-span-5 flex items-center gap-2 text-xs text-stone-500"><input type="checkbox" checked={partner.hasAdministrativePowers} onChange={e=>setPartners(current=>current.map((item,i)=>i===index?{...item,hasAdministrativePowers:e.target.checked}:item))}/> Possui poderes de administração/representação</label></div>)}</div><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={()=>setPartners(current=>[...current,{name:'',email:'',phone:'',participationPercentage:'',hasAdministrativePowers:false}])} className="rounded-xl bg-stone-100 px-4 py-2.5 text-xs font-black">Adicionar sócio</button><button type="button" onClick={()=>void savePartners()} disabled={working==='partners'} className="rounded-xl bg-blue-700 px-4 py-2.5 text-xs font-black text-white disabled:opacity-50">{working==='partners'?'Salvando...':'Salvar declaração societária'}</button></div></section>}

    <section className="rounded-[28px] border border-emerald-200 bg-emerald-50 p-5 sm:p-6"><div className="flex items-start gap-3"><FileCheck2 className="mt-0.5 h-5 w-5 text-emerald-700"/><div><h2 className="font-black text-emerald-950">Consentimento e finalidade</h2><p className="mt-1 text-xs leading-5 text-emerald-900/75">Os dados são usados para segurança das intermediações, prevenção de fraude, análise cadastral, exercício regular de direitos e atendimento de obrigações legais aplicáveis. Quando houver ordem ou fundamento jurídico válido, informações poderão ser preservadas ou disponibilizadas às autoridades competentes nos limites da legislação. O acesso administrativo aos documentos é auditado.</p></div></div>{!locked&&<label className="mt-4 flex items-start gap-3 rounded-2xl bg-white/70 p-4"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)} className="mt-1 h-4 w-4"/><span className="text-xs leading-5 text-stone-600">Li e concordo com os <Link to="/classificados/termos" className="font-black text-emerald-800 underline">Termos do Marketplace e da verificação cadastral</Link>, versão {data?.consentVersion}.</span></label>}<div className="mt-4 flex flex-wrap gap-3"><button type="button" onClick={()=>void submit()} disabled={locked||!canSubmit||!accepted||working==='submit'} className="inline-flex h-12 items-center justify-center gap-2 rounded-2xl bg-emerald-800 px-5 text-sm font-black text-white disabled:opacity-40">{working==='submit'?<Loader2 className="h-4 w-4 animate-spin"/>:<ShieldCheck className="h-4 w-4"/>}{verification?.status==='NEEDS_CHANGES'||verification?.status==='REJECTED'?'Reenviar para análise':'Enviar para análise'}</button><button type="button" onClick={()=>void load()} className="inline-flex h-12 items-center gap-2 rounded-2xl bg-white px-4 text-xs font-black text-stone-600 ring-1 ring-stone-200"><RefreshCw className="h-4 w-4"/>Atualizar</button></div>{!canSubmit&&<p className="mt-3 text-xs font-bold text-amber-800">Para enviar, precisamos de selfie, documento oficial e comprovante de endereço.</p>}</section>
  </div>;
}

function StatusBadge({status}:{status:string}){const map:any={DRAFT:['Não enviada','bg-white/10 text-white/70'],PENDING:['Em análise','bg-amber-300 text-amber-950'],APPROVED:['Verificada','bg-emerald-300 text-emerald-950'],REJECTED:['Reprovada','bg-red-300 text-red-950'],NEEDS_CHANGES:['Ajustes necessários','bg-orange-300 text-orange-950']};const [label,cls]=map[status]||map.DRAFT;return <span className={`inline-flex rounded-full px-4 py-2 text-[10px] font-black uppercase tracking-[.12em] ${cls}`}>{label}</span>}
function Choice({selected,disabled,icon,title,text,onClick}:{selected:boolean;disabled?:boolean;icon:React.ReactNode;title:string;text:string;onClick:()=>void}){return <button type="button" disabled={disabled} onClick={onClick} className={`rounded-2xl border p-4 text-left disabled:cursor-not-allowed disabled:opacity-45 ${selected?'border-[#397c75] bg-[#eef8f6]':'border-stone-200 bg-white'}`}><span className="flex items-center gap-2 font-black">{icon}{title}</span><span className="mt-2 block text-xs leading-5 text-stone-500">{text}</span></button>}
function DocumentCard({title,text,uploaded,working,locked,onFile}:{kind:DocumentKind;title:string;text:string;uploaded?:any;working:boolean;locked:boolean;onFile:(file:File|null)=>void}){return <div className={`rounded-2xl border p-4 ${uploaded?'border-emerald-200 bg-emerald-50':'border-stone-200 bg-stone-50'}`}><div className="flex items-center gap-2">{uploaded?<CheckCircle2 className="h-5 w-5 text-emerald-700"/>:<FileText className="h-5 w-5 text-stone-400"/>}<p className="text-sm font-black">{title}</p></div><p className="mt-2 min-h-10 text-xs leading-5 text-stone-500">{text}</p>{uploaded&&<p className="mt-2 truncate text-[10px] font-bold text-emerald-800">{uploaded.originalName}</p>}{!locked&&<label className="mt-3 inline-flex cursor-pointer items-center gap-2 rounded-xl bg-white px-3 py-2 text-[10px] font-black ring-1 ring-stone-200"><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" className="hidden" onChange={e=>{onFile(e.target.files?.[0]||null);e.currentTarget.value=''}} disabled={working}/>{working?<Loader2 className="h-3.5 w-3.5 animate-spin"/>:<Upload className="h-3.5 w-3.5"/>}{uploaded?'Substituir':'Enviar'}</label>}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-[10px] font-black uppercase tracking-[.12em] text-stone-400">{label}</span>{children}</label>}
function membershipLabel(value?:string){return value==='PRIMARY_ADMIN'?'Administrador principal':value==='ADMIN'?'Administrador':'Funcionário/colaborador'}
function dateTime(value:string){return new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}
const inputClass='h-12 w-full rounded-2xl border border-stone-200 bg-white px-4 text-sm font-semibold outline-none focus:border-[#397c75]';
const miniInput='h-10 min-w-0 rounded-xl border border-stone-200 bg-white px-3 text-xs font-semibold outline-none';
