import { DataSource } from 'typeorm';
import { JobMatchService } from '../job-match/job-match.service';
import { ExternalJobsService } from './external-jobs.service';
import type { ExternalJobInput, JobCatalogQuery } from './external-jobs.service';
type ExternalJobWithMatchInput = ExternalJobInput & {
    matchProfile?: unknown;
};
export declare class ExternalApiController {
    private readonly jobs;
    private readonly jobMatch;
    private readonly dataSource;
    constructor(jobs: ExternalJobsService, jobMatch: JobMatchService, dataSource: DataSource);
    matchProfileSchema(): {
        field: string;
        optional: boolean;
        purpose: string;
        requiredFields: string[];
        requirementTypes: string[];
        schema: {
            canonicalRole: string;
            occupationalFamily: string;
            occupationKeywords: string[];
            technicalSkills: {
                name: string;
                required: string;
                weight: string;
                evidenceTerms: string[];
            }[];
            requirements: {
                label: string;
                type: string;
                required: string;
                weight: string;
                evidenceTerms: string[];
            }[];
            softSkills: string[];
            summary: string;
        };
        example: {
            canonicalRole: string;
            occupationalFamily: string;
            occupationKeywords: string[];
            technicalSkills: {
                name: string;
                required: boolean;
                weight: number;
                evidenceTerms: string[];
            }[];
            requirements: {
                label: string;
                type: string;
                required: boolean;
                weight: number;
                evidenceTerms: string[];
            }[];
            softSkills: string[];
            summary: string;
        };
        note: string;
    };
    matchProfileStatus(ready?: string, active?: string, limit?: string, city?: string, state?: string): Promise<{
        data: any;
        count: any;
        filters: {
            ready: string;
            active: string;
            city: string | null;
            state: string | null;
            limit: number;
            algorithmVersion: string;
        };
    }>;
    list(req: any, query: JobCatalogQuery): Promise<{
        data: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        }[];
        pagination: {
            limit: number;
            count: number;
            hasMore: boolean;
            nextCursor: string | null;
        };
        filters: {
            q: string;
            active: boolean | null;
            external: boolean | null;
            city: string;
            state: string;
            type: string;
            workModel: string;
            companyId: string;
            pcdMode: string;
        };
    }>;
    check(req: any, input: ExternalJobWithMatchInput): Promise<{
        duplicate: boolean;
        matchType: "EXACT";
        confidence: number;
        job: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        fingerprint: string;
        data: {
            title: string;
            description: string;
            city: string;
            state: string;
            location: string;
            sourceName: string;
            sourceUrl: string | null;
            requirements: string | null;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            externalApplicationInstructions: string | null;
            deadlineDate: string | null;
            isTalentPool: boolean;
            isFlagged: boolean;
            flagObservation: string | null;
            companyName: string;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
        };
        signals: {
            sameSourceExternalId: boolean | "" | null;
            sameSourceUrl: boolean | "" | null;
        };
        closestJob?: undefined;
    } | {
        duplicate: boolean;
        matchType: "LIKELY";
        confidence: number;
        job: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        fingerprint: string;
        data: {
            title: string;
            description: string;
            city: string;
            state: string;
            location: string;
            sourceName: string;
            sourceUrl: string | null;
            requirements: string | null;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            externalApplicationInstructions: string | null;
            deadlineDate: string | null;
            isTalentPool: boolean;
            isFlagged: boolean;
            flagObservation: string | null;
            companyName: string;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
        };
        signals: any;
        closestJob?: undefined;
    } | {
        duplicate: boolean;
        matchType: "SIMILAR";
        confidence: number;
        closestJob: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        fingerprint: string;
        data: {
            title: string;
            description: string;
            city: string;
            state: string;
            location: string;
            sourceName: string;
            sourceUrl: string | null;
            requirements: string | null;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            externalApplicationInstructions: string | null;
            deadlineDate: string | null;
            isTalentPool: boolean;
            isFlagged: boolean;
            flagObservation: string | null;
            companyName: string;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
        };
        signals: any;
        job?: undefined;
    } | {
        duplicate: boolean;
        matchType: null;
        confidence: number;
        closestJob: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        fingerprint: string;
        data: {
            title: string;
            description: string;
            city: string;
            state: string;
            location: string;
            sourceName: string;
            sourceUrl: string | null;
            requirements: string | null;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            externalApplicationInstructions: string | null;
            deadlineDate: string | null;
            isTalentPool: boolean;
            isFlagged: boolean;
            flagObservation: string | null;
            companyName: string;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
        };
        signals: any;
        job?: undefined;
    }>;
    create(req: any, input: ExternalJobWithMatchInput): Promise<any>;
    update(req: any, id: string, input: ExternalJobWithMatchInput): Promise<any>;
    verify(req: any, id: string, input: any): Promise<any>;
}
export {};
