import { JobMatchService } from '../job-match/job-match.service';
import { ExternalJobsService } from './external-jobs.service';
import type { ExternalJobInput, JobCatalogQuery } from './external-jobs.service';
import { JobsOperationsService } from './jobs-operations.service';
type ExternalJobWithMatchInput = ExternalJobInput & {
    matchProfile?: unknown;
};
export declare class ExternalApiV2Controller {
    private readonly jobs;
    private readonly operations;
    private readonly jobMatch;
    constructor(jobs: ExternalJobsService, operations: JobsOperationsService, jobMatch: JobMatchService);
    stats(req: any): Promise<{
        total: number;
        active: number;
        inactive: number;
        flagged: number;
        moderationPending: number;
        review: Record<string, number>;
    }>;
    reviewQueue(req: any, query: {
        status?: string;
        active?: string;
        city?: string;
        state?: string;
        page?: string;
        pageSize?: string;
    }): Promise<{
        data: import("../jobs/entities/job.entity").Job[];
        pagination: {
            page: number;
            pageSize: number;
            total: number;
            totalPages: number;
        };
    }>;
    list(req: any, query: JobCatalogQuery): Promise<{
        data: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        }[];
        pagination: {
            limit: number;
            count: number;
            hasMore: boolean;
            nextCursor: string | null;
        };
        filters: {
            q: string;
            active: boolean | null;
            external: boolean | null;
            city: string;
            state: string;
            type: string;
            workModel: string;
            companyId: string;
            pcdMode: string;
        };
    }>;
    get(req: any, id: string): Promise<import("../jobs/entities/job.entity").Job>;
    check(req: any, input: ExternalJobWithMatchInput): Promise<{
        duplicate: boolean;
        matchType: "EXACT";
        confidence: number;
        job: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        fingerprint: string;
        data: {
            title: string;
            description: string;
            city: string;
            state: string;
            location: string;
            sourceName: string;
            sourceUrl: string | null;
            requirements: string | null;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            externalApplicationInstructions: string | null;
            deadlineDate: string | null;
            isTalentPool: boolean;
            isFlagged: boolean;
            flagObservation: string | null;
            companyName: string;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
        };
        signals: {
            sameSourceExternalId: boolean | "" | null;
            sameSourceUrl: boolean | "" | null;
        };
        closestJob?: undefined;
    } | {
        duplicate: boolean;
        matchType: "LIKELY";
        confidence: number;
        job: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        fingerprint: string;
        data: {
            title: string;
            description: string;
            city: string;
            state: string;
            location: string;
            sourceName: string;
            sourceUrl: string | null;
            requirements: string | null;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            externalApplicationInstructions: string | null;
            deadlineDate: string | null;
            isTalentPool: boolean;
            isFlagged: boolean;
            flagObservation: string | null;
            companyName: string;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
        };
        signals: any;
        closestJob?: undefined;
    } | {
        duplicate: boolean;
        matchType: "SIMILAR";
        confidence: number;
        closestJob: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        fingerprint: string;
        data: {
            title: string;
            description: string;
            city: string;
            state: string;
            location: string;
            sourceName: string;
            sourceUrl: string | null;
            requirements: string | null;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            externalApplicationInstructions: string | null;
            deadlineDate: string | null;
            isTalentPool: boolean;
            isFlagged: boolean;
            flagObservation: string | null;
            companyName: string;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
        };
        signals: any;
        job?: undefined;
    } | {
        duplicate: boolean;
        matchType: null;
        confidence: number;
        closestJob: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        fingerprint: string;
        data: {
            title: string;
            description: string;
            city: string;
            state: string;
            location: string;
            sourceName: string;
            sourceUrl: string | null;
            requirements: string | null;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            externalApplicationInstructions: string | null;
            deadlineDate: string | null;
            isTalentPool: boolean;
            isFlagged: boolean;
            flagObservation: string | null;
            companyName: string;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
        };
        signals: any;
        job?: undefined;
    }>;
    create(req: any, input: ExternalJobWithMatchInput): Promise<any>;
    update(req: any, id: string, input: ExternalJobWithMatchInput): Promise<any>;
    verify(req: any, id: string, input: any): Promise<any>;
    activate(req: any, id: string, body: {
        note?: string;
    }): Promise<import("../jobs/entities/job.entity").Job>;
    deactivate(req: any, id: string, body: {
        note?: string;
    }): Promise<import("../jobs/entities/job.entity").Job>;
    review(req: any, id: string, body: {
        status?: string;
        note?: string;
    }): Promise<import("../jobs/entities/job.entity").Job>;
    flag(req: any, id: string, body: {
        reason?: string;
        observation?: string;
    }): Promise<import("../jobs/entities/job.entity").Job>;
    unflag(req: any, id: string, body: {
        note?: string;
    }): Promise<import("../jobs/entities/job.entity").Job>;
    remove(req: any, id: string): Promise<{
        success: boolean;
        id: string;
    }>;
    private requireScope;
    private actor;
}
export {};
