import { Repository } from 'typeorm';
import { Job } from '../jobs/entities/job.entity';
import { ExternalApiClient } from './entities/external-api-client.entity';
import { ExternalApiRequest } from './entities/external-api-request.entity';
export type ExternalJobInput = {
    title?: unknown;
    sourceName?: unknown;
    sourceUrl?: unknown;
    city?: unknown;
    state?: unknown;
    description?: unknown;
    requirements?: unknown;
    type?: unknown;
    workModel?: unknown;
    salary?: unknown;
    estimatedSalary?: unknown;
    estimatedSalarySource?: unknown;
    estimatedSalarySourceUrl?: unknown;
    estimatedSalaryRegion?: unknown;
    estimatedSalaryUpdatedAt?: unknown;
    pcdMode?: unknown;
    applicationEmail?: unknown;
    applicationWhatsApp?: unknown;
    applicationUrl?: unknown;
    applicationUrlTitle?: unknown;
    externalApplicationInstructions?: unknown;
    deadlineDate?: unknown;
    allowSimilarDuplicate?: unknown;
    isTalentPool?: unknown;
    isFlagged?: unknown;
    flagObservation?: unknown;
    companyName?: unknown;
    sourceExternalId?: unknown;
    sourcePublishedAt?: unknown;
    lastVerifiedAt?: unknown;
    lastSeenAt?: unknown;
    flagReason?: unknown;
    flaggedAt?: unknown;
    flaggedBy?: unknown;
};
type SanitizedExternalJob = {
    title: string;
    description: string;
    city: string;
    state: string;
    location: string;
    sourceName: string;
    sourceUrl: string | null;
    requirements: string | null;
    type: string;
    workModel: string;
    salary: string | null;
    estimatedSalary: string | null;
    estimatedSalarySource: string | null;
    estimatedSalarySourceUrl: string | null;
    estimatedSalaryRegion: string | null;
    estimatedSalaryUpdatedAt: Date | null;
    pcdMode: string;
    applicationEmail: string | null;
    applicationWhatsApp: string | null;
    applicationUrl: string | null;
    applicationUrlTitle: string | null;
    externalApplicationInstructions: string | null;
    deadlineDate: string | null;
    isTalentPool: boolean;
    isFlagged: boolean;
    flagObservation: string | null;
    companyName: string;
    sourceExternalId: string | null;
    sourcePublishedAt: Date | null;
    lastVerifiedAt: Date | null;
    lastSeenAt: Date | null;
    flagReason: string | null;
    flaggedAt: Date | null;
    flaggedBy: string | null;
};
export type JobCatalogQuery = {
    q?: string;
    limit?: string;
    cursor?: string;
    active?: string;
    external?: string;
    city?: string;
    state?: string;
    type?: string;
    workModel?: string;
    companyId?: string;
    pcdMode?: string;
};
type CatalogFilters = {
    q: string;
    active: boolean | null;
    external: boolean | null;
    city: string;
    state: string;
    type: string;
    workModel: string;
    companyId: string;
    pcdMode: string;
};
export declare class ExternalJobsService {
    private readonly jobs;
    private readonly requests;
    private readonly validStates;
    constructor(jobs: Repository<Job>, requests: Repository<ExternalApiRequest>);
    check(input: ExternalJobInput, client: ExternalApiClient): Promise<{
        duplicate: boolean;
        matchType: "EXACT";
        confidence: number;
        job: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        fingerprint: string;
        data: SanitizedExternalJob;
        signals: {
            sameSourceExternalId: boolean | "" | null;
            sameSourceUrl: boolean | "" | null;
        };
        closestJob?: undefined;
    } | {
        duplicate: boolean;
        matchType: "LIKELY";
        confidence: number;
        job: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        fingerprint: string;
        data: SanitizedExternalJob;
        signals: any;
        closestJob?: undefined;
    } | {
        duplicate: boolean;
        matchType: "SIMILAR";
        confidence: number;
        closestJob: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        fingerprint: string;
        data: SanitizedExternalJob;
        signals: any;
        job?: undefined;
    } | {
        duplicate: boolean;
        matchType: null;
        confidence: number;
        closestJob: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        fingerprint: string;
        data: SanitizedExternalJob;
        signals: any;
        job?: undefined;
    }>;
    findDuplicate(input: ExternalJobInput, client: ExternalApiClient): Promise<{
        duplicate: boolean;
        matchType: "EXACT";
        confidence: number;
        job: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        fingerprint: string;
        data: SanitizedExternalJob;
        signals: {
            sameSourceExternalId: boolean | "" | null;
            sameSourceUrl: boolean | "" | null;
        };
        closestJob?: undefined;
    } | {
        duplicate: boolean;
        matchType: "LIKELY";
        confidence: number;
        job: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        fingerprint: string;
        data: SanitizedExternalJob;
        signals: any;
        closestJob?: undefined;
    } | {
        duplicate: boolean;
        matchType: "SIMILAR";
        confidence: number;
        closestJob: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        fingerprint: string;
        data: SanitizedExternalJob;
        signals: any;
        job?: undefined;
    } | {
        duplicate: boolean;
        matchType: null;
        confidence: number;
        closestJob: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        fingerprint: string;
        data: SanitizedExternalJob;
        signals: any;
        job?: undefined;
    }>;
    create(input: ExternalJobInput, client: ExternalApiClient): Promise<{
        duplicate: boolean;
        matchType: "EXACT";
        confidence: number;
        job: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        fingerprint: string;
        data: SanitizedExternalJob;
        signals: {
            sameSourceExternalId: boolean | "" | null;
            sameSourceUrl: boolean | "" | null;
        };
        closestJob?: undefined;
    } | {
        duplicate: boolean;
        matchType: "LIKELY";
        confidence: number;
        job: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        fingerprint: string;
        data: SanitizedExternalJob;
        signals: any;
        closestJob?: undefined;
    } | {
        duplicate: boolean;
        matchType: "SIMILAR";
        confidence: number;
        closestJob: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
        fingerprint: string;
        data: SanitizedExternalJob;
        signals: any;
        job?: undefined;
    } | {
        duplicate: boolean;
        matchType: null;
        confidence: number;
        closestJob: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        fingerprint: string;
        data: SanitizedExternalJob;
        signals: any;
        job?: undefined;
    } | {
        duplicate: boolean;
        created: boolean;
        moderationStatus: string;
        similarMatchOverridden: boolean;
        job: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
    }>;
    update(id: string, input: ExternalJobInput, client: ExternalApiClient): Promise<{
        updated: boolean;
        job: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
    }>;
    verify(id: string, input: any, client: ExternalApiClient): Promise<{
        verified: boolean;
        job: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        };
    }>;
    list(query: JobCatalogQuery, client: ExternalApiClient): Promise<{
        data: {
            id: string;
            slug: string | null;
            title: string;
            description: string;
            requirements: string | null;
            companyId: string | null;
            companyName: string;
            isExternalListing: boolean;
            sourceName: string | null;
            sourceUrl: string | null;
            city: string | null;
            state: string | null;
            location: string;
            type: string;
            workModel: string;
            salary: string | null;
            estimatedSalary: string | null;
            estimatedSalarySource: string | null;
            estimatedSalarySourceUrl: string | null;
            estimatedSalaryRegion: string | null;
            estimatedSalaryUpdatedAt: Date | null;
            pcdMode: string;
            deadlineDate: string | null;
            acceptsPlatformApplications: boolean;
            externalApplicationInstructions: string | null;
            applicationEmail: string | null;
            applicationWhatsApp: string | null;
            applicationUrl: string | null;
            applicationUrlTitle: string | null;
            isConfidential: boolean;
            isTalentPool: boolean;
            isSponsored: boolean;
            active: boolean;
            moderationStatus: string;
            reportCount: number;
            ingestionSourceId: string | null;
            ingestionSourceName: string | null;
            isFlagged: boolean;
            flagObservation: string | null;
            flagReason: string | null;
            flaggedAt: Date | null;
            flaggedBy: string | null;
            sourceExternalId: string | null;
            sourcePublishedAt: Date | null;
            lastVerifiedAt: Date | null;
            lastSeenAt: Date | null;
            createdAt: Date;
            updatedAt: Date;
        }[];
        pagination: {
            limit: number;
            count: number;
            hasMore: boolean;
            nextCursor: string | null;
        };
        filters: CatalogFilters;
    }>;
    private sanitize;
    private optionalBoolean;
    private optionalDate;
    private requiredText;
    private optionalText;
    private isIsoDate;
    private normalize;
    private tokens;
    private similarity;
    private catalogFilters;
    private queryText;
    private queryBoolean;
    private encodeCursor;
    private decodeCursor;
    private cursorSignature;
    private catalogResult;
    private publicResult;
    private nextSlug;
    private log;
}
export {};
