export type JobsCapabilityRisk = 'read' | 'write' | 'destructive';
export type JobsCapabilityChannel = 'v1' | 'v2' | 'mcp';
export type JobsCapability = {
    scope: string;
    section: string;
    category: string;
    label: string;
    description: string;
    risk: JobsCapabilityRisk;
    channels: JobsCapabilityChannel[];
    toolName?: string;
    endpoint?: string;
    legacy?: boolean;
    defaultV2?: boolean;
    defaultMcp?: boolean;
};
export declare const JOBS_CAPABILITIES: JobsCapability[];
export declare const ALL_JOBS_SCOPES: string[];
export declare const JOBS_MCP_SCOPES: string[];
export declare const DEFAULT_JOBS_V2_SCOPES: string[];
export declare const DEFAULT_JOBS_MCP_SCOPES: string[];
export type JobsMcpScope = string;
export declare function sanitizeJobsScopes(value: unknown, fallback?: string[]): string[];
export declare function expandLegacyJobsScopes(scopes: Iterable<string>): string[];
export declare function hasJobsScope(scopes: Iterable<string>, scope: string): boolean;
