import { DataSource } from 'typeorm';
import { RegistrationService } from '../admin/registration.service';
import { SettingsService, type AiBrainEntryInput, type AiBehaviorSettings } from '../admin/settings.service';
import { CompanyPlansAdminService } from '../company-plans/company-plans-admin.service';
import { BillingSupportService } from '../payments/billing-support.service';
import { PaymentProviderManagerService } from '../payments/payment-provider-manager.service';
import { PaymentsService } from '../payments/payments.service';
import { ProductDurationService } from '../payments/product-duration.service';
export declare class McpManagementService {
    private readonly dataSource;
    private readonly registration;
    private readonly settings;
    private readonly companyPlans;
    private readonly payments;
    private readonly billing;
    private readonly productDuration;
    private readonly paymentProviders;
    constructor(dataSource: DataSource, registration: RegistrationService, settings: SettingsService, companyPlans: CompanyPlansAdminService, payments: PaymentsService, billing: BillingSupportService, productDuration: ProductDurationService, paymentProviders: PaymentProviderManagerService);
    platformSummary(): Promise<any>;
    platformAnalytics(days?: number): Promise<{
        periodDays: number;
        pageViews: number;
        uniqueVisitors: number;
        averageEngagementSeconds: number;
        sources: any;
        devices: any;
        topPages: any;
        accountAccesses: number;
        newDevices: number;
    }>;
    registrationOverview(): Promise<{
        open: boolean;
        waiting: number;
        interests: import("../admin/entities/registration-interest.entity").RegistrationInterest[];
    }>;
    registrationSetOpen(open: boolean): Promise<{
        open: boolean;
    }>;
    companiesList(input?: {
        q?: unknown;
        status?: unknown;
        limit?: unknown;
    }): Promise<any>;
    companyGet(id: string): Promise<{
        company: any;
        employees: any;
        counters: any;
    }>;
    companyCreate(actor: string, input: Record<string, unknown>): Promise<any>;
    companyUpdate(id: string, input: Record<string, unknown>): Promise<any>;
    companyAccessQueue(): Promise<any>;
    companyAccessDecide(actor: string, id: string, decisionRaw: unknown, roleRaw?: unknown, noteRaw?: unknown): Promise<any>;
    companySlugDecide(actor: string, companyId: string, decisionRaw: unknown, noteRaw?: unknown): Promise<any>;
    companyPlanGet(companyId: string): Promise<{
        company: {
            id: any;
            name: any;
        };
        current: {
            plan: import("../company-plans/company-plans.service").CompanyPlan;
            basePlan: import("../company-plans/company-plans.service").CompanyPlan;
            rank: number;
            active: boolean;
            status: any;
            currentPeriodStart: any;
            currentPeriodEnd: any;
            paidCurrentPeriodEnd: any;
            cancelAtPeriodEnd: boolean;
            provider: any;
            providerSubscriptionId: any;
            isSimulation: boolean;
            isTrial: boolean;
            trialEndsAt: any;
            trialTargetPlan: import("../company-plans/company-plans.service").CompanyPlan | null;
            hasPaidSubscription: boolean;
            purchaseMode: "SUBSCRIPTION" | "ONE_TIME" | null;
            benefitIds: import("../company-plans/company-plan-benefits").CompanyPlanBenefitId[];
            benefits: import("../company-plans/company-plan-benefits").CompanyPlanBenefitDefinition[];
            advertisingEligible: boolean;
            jobHighlightEligible: boolean;
        };
        subscription: any;
        trial: any;
        plans: any[];
    }>;
    companyPlanSet(actor: string, companyId: string, plan: unknown, currentPeriodEnd?: unknown): Promise<{
        company: {
            id: any;
            name: any;
        };
        current: {
            plan: import("../company-plans/company-plans.service").CompanyPlan;
            basePlan: import("../company-plans/company-plans.service").CompanyPlan;
            rank: number;
            active: boolean;
            status: any;
            currentPeriodStart: any;
            currentPeriodEnd: any;
            paidCurrentPeriodEnd: any;
            cancelAtPeriodEnd: boolean;
            provider: any;
            providerSubscriptionId: any;
            isSimulation: boolean;
            isTrial: boolean;
            trialEndsAt: any;
            trialTargetPlan: import("../company-plans/company-plans.service").CompanyPlan | null;
            hasPaidSubscription: boolean;
            purchaseMode: "SUBSCRIPTION" | "ONE_TIME" | null;
            benefitIds: import("../company-plans/company-plan-benefits").CompanyPlanBenefitId[];
            benefits: import("../company-plans/company-plan-benefits").CompanyPlanBenefitDefinition[];
            advertisingEligible: boolean;
            jobHighlightEligible: boolean;
        };
        subscription: any;
        trial: any;
        plans: any[];
    }>;
    usersList(input?: {
        q?: unknown;
        status?: unknown;
        limit?: unknown;
    }): Promise<any>;
    userGet(id: string): Promise<{
        user: any;
        sanctions: any;
        security: any;
    }>;
    userModerate(id: string, input: {
        status?: unknown;
        isVerified?: unknown;
    }): Promise<any>;
    userSanction(actor: string, userId: string, input: {
        type?: unknown;
        reason?: unknown;
        expiresAt?: unknown;
    }): Promise<any>;
    feeRules(kind: 'commerce' | 'auction'): Promise<any>;
    feePlanSet(kind: 'commerce' | 'auction', plan: string, input: Record<string, unknown>): Promise<{
        id: any;
        scope: any;
        plan: any;
        companyId: any;
        companyName: any;
        rateBps: number;
        percentage: number;
        minimumFeeCents: number;
        maximumFeeCents: number | null;
        enabled: boolean;
        updatedAt: any;
    }>;
    feeCompanySet(kind: 'commerce' | 'auction', companyId: string, input: Record<string, unknown>): Promise<{
        id: any;
        scope: any;
        plan: any;
        companyId: any;
        companyName: any;
        rateBps: number;
        percentage: number;
        minimumFeeCents: number;
        maximumFeeCents: number | null;
        enabled: boolean;
        updatedAt: any;
    }>;
    feeCompanyRemove(kind: 'commerce' | 'auction', companyId: string): Promise<{
        removed: boolean;
    }>;
    adsList(): Promise<any>;
    adCreate(input: Record<string, unknown>): Promise<any>;
    adUpdate(id: string, input: Record<string, unknown>): Promise<any>;
    advertisingConfigGet(): Promise<any>;
    advertisingConfigSet(input: Record<string, unknown>): Promise<any>;
    paymentsSummary(): Promise<any>;
    paymentsPerformance(): Promise<{
        products: any;
        highlights: {
            topSelling: any;
            topRevenue: any;
            topConversion: any;
        };
    }>;
    paymentsList(limit?: number): Promise<any>;
    paymentConfirm(actor: string, id: string): Promise<any>;
    paymentSimulate(actor: string, id: string): Promise<any>;
    paymentProducts(): Promise<any>;
    paymentProductUpdate(code: string, input: Record<string, unknown>): Promise<any>;
    paymentProductDurationSet(code: string, durationDays: unknown): Promise<any>;
    paymentDevModeGet(): Promise<{
        enabled: boolean;
    }>;
    paymentDevModeSet(enabled: boolean): Promise<{
        enabled: boolean;
    }>;
    billingUsersSearch(q?: string, limit?: number): Promise<any>;
    billingUserGet(userId: string): Promise<{
        user: any;
        billing: any;
        credits: Record<string, number>;
        entitlements: any;
        subscriptions: any;
        payments: any;
        creditLedger: any;
    }>;
    billingLifetimeSet(actor: string, userId: string, enabled: boolean, note?: unknown): Promise<any>;
    billingCreditSet(actor: string, userId: string, featureRaw: string, quantity: unknown, note?: unknown): Promise<{
        feature: import("../payments/payments.service").FeatureCredit;
        credits: number;
        previousCredits: number;
        delta: number;
    }>;
    billingEntitlementGrant(actor: string, userId: string, featureRaw: string, durationDays: unknown, note?: unknown): Promise<{
        feature: import("../payments/billing-support.service").TimedFeature;
        durationDays: number;
        expiresAt: any;
    }>;
    billingEntitlementRevoke(actor: string, userId: string, featureRaw: string, note?: unknown): Promise<any>;
    subscriptionActivate(actor: string, userId: string, productCode: string, durationDays?: unknown, note?: unknown): Promise<any>;
    subscriptionStatusSet(actor: string, userId: string, subscriptionId: string, statusRaw: string): Promise<any>;
    paymentProvidersList(): Promise<any[]>;
    paymentProviderRoutes(): Promise<any>;
    paymentVaultStatus(): {
        encryptedAtRest: boolean;
        algorithm: string;
        keyStorage: string;
        keyPathHint: string;
    };
    paymentProviderGet(code: string): Promise<{
        code: import("../payments/payment-provider-config.service").PaymentProviderCode;
        name: any;
        description: any;
        active: boolean;
        activeFor: any;
        configured: boolean;
        configVersion: number;
        lastHealthCheckAt: any;
        lastHealthCheckOk: any;
        lastHealthCheckMessage: any;
        lastHealthCheckDetails: any;
        activatedAt: any;
        updatedAt: any;
        config: {
            environment: string;
            clientIdConfigured: boolean;
            clientSecretConfigured: boolean;
            pixKeyConfigured: boolean;
            certificateConfigured: boolean;
            certificateFileName: any;
            certificateHasPassphrase: boolean;
            pixAutomaticEnabled: boolean;
            receiverAccountConfigured: boolean;
            publicApiBaseUrl: any;
            skipMtlsChecking: boolean;
            capabilities: string[];
            accessTokenConfigured?: undefined;
            publicKeyConfigured?: undefined;
            webhookSecretConfigured?: undefined;
            marketplaceClientIdConfigured?: undefined;
            marketplaceClientId?: undefined;
            marketplaceClientSecretConfigured?: undefined;
            marketplaceRedirectUri?: undefined;
            checkoutApi?: undefined;
            recurringApi?: undefined;
            sdk?: undefined;
        } | {
            environment: string;
            accessTokenConfigured: boolean;
            publicKeyConfigured: boolean;
            webhookSecretConfigured: boolean;
            marketplaceClientIdConfigured: boolean;
            marketplaceClientId: any;
            marketplaceClientSecretConfigured: boolean;
            marketplaceRedirectUri: any;
            publicApiBaseUrl: any;
            capabilities: string[];
            checkoutApi: string;
            recurringApi: string;
            sdk: string;
            clientIdConfigured?: undefined;
            clientSecretConfigured?: undefined;
            pixKeyConfigured?: undefined;
            certificateConfigured?: undefined;
            certificateFileName?: undefined;
            certificateHasPassphrase?: undefined;
            pixAutomaticEnabled?: undefined;
            receiverAccountConfigured?: undefined;
            skipMtlsChecking?: undefined;
        };
    }>;
    paymentProviderTest(actor: string, code: string): Promise<{
        code: import("../payments/payment-provider-config.service").PaymentProviderCode;
        name: any;
        description: any;
        active: boolean;
        activeFor: any;
        configured: boolean;
        configVersion: number;
        lastHealthCheckAt: any;
        lastHealthCheckOk: any;
        lastHealthCheckMessage: any;
        lastHealthCheckDetails: any;
        activatedAt: any;
        updatedAt: any;
        config: {
            environment: string;
            clientIdConfigured: boolean;
            clientSecretConfigured: boolean;
            pixKeyConfigured: boolean;
            certificateConfigured: boolean;
            certificateFileName: any;
            certificateHasPassphrase: boolean;
            pixAutomaticEnabled: boolean;
            receiverAccountConfigured: boolean;
            publicApiBaseUrl: any;
            skipMtlsChecking: boolean;
            capabilities: string[];
            accessTokenConfigured?: undefined;
            publicKeyConfigured?: undefined;
            webhookSecretConfigured?: undefined;
            marketplaceClientIdConfigured?: undefined;
            marketplaceClientId?: undefined;
            marketplaceClientSecretConfigured?: undefined;
            marketplaceRedirectUri?: undefined;
            checkoutApi?: undefined;
            recurringApi?: undefined;
            sdk?: undefined;
        } | {
            environment: string;
            accessTokenConfigured: boolean;
            publicKeyConfigured: boolean;
            webhookSecretConfigured: boolean;
            marketplaceClientIdConfigured: boolean;
            marketplaceClientId: any;
            marketplaceClientSecretConfigured: boolean;
            marketplaceRedirectUri: any;
            publicApiBaseUrl: any;
            capabilities: string[];
            checkoutApi: string;
            recurringApi: string;
            sdk: string;
            clientIdConfigured?: undefined;
            clientSecretConfigured?: undefined;
            pixKeyConfigured?: undefined;
            certificateConfigured?: undefined;
            certificateFileName?: undefined;
            certificateHasPassphrase?: undefined;
            pixAutomaticEnabled?: undefined;
            receiverAccountConfigured?: undefined;
            skipMtlsChecking?: undefined;
        };
    }>;
    paymentProviderActivate(actor: string, code: string, paymentType: string): Promise<{
        provider: {
            code: import("../payments/payment-provider-config.service").PaymentProviderCode;
            name: any;
            description: any;
            active: boolean;
            activeFor: any;
            configured: boolean;
            configVersion: number;
            lastHealthCheckAt: any;
            lastHealthCheckOk: any;
            lastHealthCheckMessage: any;
            lastHealthCheckDetails: any;
            activatedAt: any;
            updatedAt: any;
            config: {
                environment: string;
                clientIdConfigured: boolean;
                clientSecretConfigured: boolean;
                pixKeyConfigured: boolean;
                certificateConfigured: boolean;
                certificateFileName: any;
                certificateHasPassphrase: boolean;
                pixAutomaticEnabled: boolean;
                receiverAccountConfigured: boolean;
                publicApiBaseUrl: any;
                skipMtlsChecking: boolean;
                capabilities: string[];
                accessTokenConfigured?: undefined;
                publicKeyConfigured?: undefined;
                webhookSecretConfigured?: undefined;
                marketplaceClientIdConfigured?: undefined;
                marketplaceClientId?: undefined;
                marketplaceClientSecretConfigured?: undefined;
                marketplaceRedirectUri?: undefined;
                checkoutApi?: undefined;
                recurringApi?: undefined;
                sdk?: undefined;
            } | {
                environment: string;
                accessTokenConfigured: boolean;
                publicKeyConfigured: boolean;
                webhookSecretConfigured: boolean;
                marketplaceClientIdConfigured: boolean;
                marketplaceClientId: any;
                marketplaceClientSecretConfigured: boolean;
                marketplaceRedirectUri: any;
                publicApiBaseUrl: any;
                capabilities: string[];
                checkoutApi: string;
                recurringApi: string;
                sdk: string;
                clientIdConfigured?: undefined;
                clientSecretConfigured?: undefined;
                pixKeyConfigured?: undefined;
                certificateConfigured?: undefined;
                certificateFileName?: undefined;
                certificateHasPassphrase?: undefined;
                pixAutomaticEnabled?: undefined;
                receiverAccountConfigured?: undefined;
                skipMtlsChecking?: undefined;
            };
        };
        routes: any;
    }>;
    paymentProviderDeactivate(actor: string, paymentType: string): Promise<any>;
    aiBehaviorGet(): Promise<AiBehaviorSettings>;
    aiBehaviorSet(input: Partial<AiBehaviorSettings>): Promise<AiBehaviorSettings>;
    aiBrainList(q?: string): Promise<any>;
    aiBrainCreate(input: AiBrainEntryInput): Promise<any>;
    aiBrainUpdate(id: string, input: AiBrainEntryInput): Promise<any>;
    aiBrainDelete(id: string): Promise<{
        deleted: boolean;
        id: string;
    }>;
    private feeTable;
    private listFeeRules;
    private saveFeePlan;
    private saveFeeCompany;
    private cleanFeeRule;
    private presentFeeRule;
    private plan;
    private cents;
    private normalizeAdOwner;
    private text;
    private nullText;
    private uf;
    private dateOrNull;
    private moneyOrNull;
    private validSlug;
    private nextCompanySlug;
    private assertCompanySlugAvailable;
}
